### ISSUE TITLE
Question: ModuleNotFoundError with "-Djava.class.path=jars/*"

### ISSUE THREAD

**Issue by Xiaoven** [jpype-project/jpype#1002]
## Problem
I got an `ModuleNotFoundError: ModuleNotFoundError: No module named 'spoon'` when I set the `-Djava.class.path` as a directory `"jars/*"`. 

Project structure
```
utils
├── __init__.py
├── jars
│   └── spoon-core-9.2.0-beta-4.jar
└── parse_utils.py
```

```py
# parse_utils.py

import jpype
import jpype.imports
from jpype.types import *

JARS_PATH = 'jars/*'
jpype.startJVM(jpype.getDefaultJVMPath(),  '-Djava.class.path=' + JARS_PATH)

import spoon.Launcher as Launcher
```

### JClass and JPackage
 I found a similar problem at stackoverflow [Jpype import cannot find module in jar](https://stackoverflow.com/questions/62952002/jpype-import-cannot-find-module-in-jar) and I tried the top answer but failed.

```py
Launcher = jpype.JPackage('spoon').Launcher  # AttributeError: Java package 'spoon' is not valid
```

```py
Launcher = jpype.JClass('spoon.Launcher')  # TypeError: Class spoon.Launcher is not found
```

```py
Launcher = jpype.JClass("java.lang.Class").forName('spoon.Launcher') # java.lang.ClassNotFoundException: java.lang.ClassNotFoundException: spoon.Launcher
```

### use jar path
```py
JARS_PATH = 'jars/spoon-core-9.2.0-beta-4.jar'
```
and I got :
```
Traceback (most recent call last):
  File "ClassLoader.java", line 357, in java.lang.ClassLoader.loadClass
  File "Launcher.java", line 338, in sun.misc.Launcher$AppClassLoader.loadClass
  File "ClassLoader.java", line 424, in java.lang.ClassLoader.loadClass
  File "URLClassLoader.java", line 381, in java.net.URLClassLoader.findClass
java.lang.ClassNotFoundException: java.lang.ClassNotFoundException: com.martiansoftware.jsap.JSAPException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "org.jpype.pkg.JPypePackage.java", line -1, in org.jpype.pkg.JPypePackage.getObject
  File "Class.java", line 348, in java.lang.Class.forName
  File "Class.java", line -2, in java.lang.Class.forName0
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/audrey/Documents/GitHub/xiaoven/codegex/utils/parse_utils.py", line 16, in <module>
    import spoon.Launcher as Launcher
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "/usr/local/Caskroom/miniconda/base/envs/codegex/lib/python3.8/site-packages/jpype/imports.py", line 194, in find_spec
    if not hasattr(base, parts[2]):
java.lang.NoClassDefFoundError: java.lang.NoClassDefFoundError: com/martiansoftware/jsap/JSAPException
```

**Comment by Thrameos** [comment]
I would start with checking to see if the jar was picked up in the path.

```
import jpype
jpype.startJVM(classpath="jars/*")
print(jpype.java.lang.System.getProperty("java.class.path"))
```

My guess is there is a syntax error in your test code, or the spoon jar is missing some dependency, but nothing stands out in your example.  Do you have the required jar dependencies including ``com.martiansoftware.jsap.JSAPException`` in the jars directory?

**Comment by Xiaoven** [comment]
> I would start with checking to see if the jar was picked up in the path.
> 
> ```
> import jpype
> jpype.startJVM(classpath="jars/*")
> print(jpype.java.lang.System.getProperty("java.class.path"))
> ```
> 
> My guess is there is a syntax error in your test code, or the spoon jar is missing some dependency, but nothing stands out in your example. Do you have the required jar dependencies including `com.martiansoftware.jsap.JSAPException` in the jars directory?

Thanks for your reply!

It printed `jars/spoon-core-9.2.0-beta-4.jar`. I guess the problem is because of lacking dependencies and I will try to find them out. 

It's troublesome to find missing dependencies for jars and not as convenient as in Java, which only needs to include a dependency in **build.gradle** as below.

```groovy
dependencies {
    implementation 'fr.inria.gforge.spoon:spoon-core:9.2.0-beta-4'
    // https://mvnrepository.com/artifact/org.slf4j/slf4j-simple
    implementation group: 'org.slf4j', name: 'slf4j-simple', version: '2.0.0-alpha5'
    testCompile group: 'junit', name: 'junit', version: '4.12'
}
```

**Comment by Xiaoven** [comment]
I find the module problem still exist after I uncomment the statements used the spoon library . Here is the full code and output:

```py
    import jpype
    jpype.startJVM(classpath="jars/*")
    print(jpype.java.lang.System.getProperty("java.class.path"))

    import spoon.Launcher as Launcher

    with open(abs_path, 'r') as f:
        content = f.read()

    clazz = Launcher.parseClass(content)
```

```
Traceback (most recent call last):
  File "parse_utils.py", line 11, in <module>
    import spoon.Launcher as Launcher
ModuleNotFoundError: No module named 'spoon'
```

@Thrameos Could you please provide me some insights about this problem? Is there any syntax error in the above code?

**Comment by Thrameos** [comment]
I originally wrote a response with manually debugging, but really this is just a problem with your dependencies.  Though this isn't a jpype question, here is how to resolve the issue.

First you can use maven pluging to load all dependencies,  but I don't know that pattern.  So instead just use the ivy pattern that JPype uses.

Just place a file called ivy.xml which contains
```
<ivy-module version="2.0" xmlns:e="http://ant.apache.org/ivy/extra" xmlns:m="http://ant.apache.org/ivy/maven">
    <info organisation="test.spoon" module="jpype"/>

   <configurations defaultconf="deps">
       <conf name="deps" description="binary jars"/>
   </configurations>

   <!-- https://www.baeldung.com/java-in-memory-databases -->
   <dependencies>
        <!-- just copy the dependencies you want in here and make sure the conf attribute has deps->default -->
        <dependency org="fr.inria.gforge.spoon" name="spoon-core" rev="9.1.0-beta-9" conf="deps->default"/>
   </dependencies>
</ivy-module>
```

(dep line came from https://jar-download.com/artifacts/fr.inria.gforge.spoon/spoon-core/9.1.0-beta-9/source-code/spoon/Launcher.java)

Next add a file called resolve.sh with the contents of 
```
#!/bin/sh
wget -nc "https://repo1.maven.org/maven2/org/apache/ivy/ivy/2.5.0/ivy-2.5.0.jar" -P lib
java -jar lib/ivy-2.5.0.jar -ivy ivy.xml -retrieve 'jars/[artifact]-[revision](-[classifier]).[ext]'
```

(just copy from jpype and modify the location you want to install to from lib to jar)

Call resolve.sh and it should pull all the dependencies you need.

At least for me after running that I could run
```
import jpype
import jpype.imports
jpype.startJVM(classpath="jars/*")
import spoon.Launcher as Launcher
print(Launcher)
```
with a few warnings.  It seems to want ``org.slf4j.impl.StaticLoggerBinder`` so you will need to search the maven repos for that library and add the ivy dependency to ivy.xml and run resolve.sh once more to clear it up.    Once you do that it should just run.

The same thing will work with maven or gradle patterns though you will need to find those yourself as I only know ivy patterns.
