### ISSUE TITLE
Sybase Store Procedure output is not returned getting error when running Fetch*

### ISSUE THREAD

**Issue by sur2rock** [jpype-project/jpype#1013]
When executing the Sybase store proc, it executes fine but the SP output is not returned , I think this has to do with return multiple result set flag , which I can see in Dbeaver tool and can set this when running the query as adv parameter but when connecting via jaydebeapi , there is no option for me to set this and the SP output is not available

**Comment by Thrameos** [comment]
There is not enough context here to answer this issue.   jaydebeapi is its own project that makes use of JPype and may be able to give you a more direct answer.   If your request is about using multiple result sets with jpype.dbapi2 module I may be able to give you some pointers but I would need some sort of example.   Both jpype.dbapi2 and jaydebeapi use the Python dbapi2 specification, and I don't recall it providing for multiple result sets so it may simply be beyond the capabilities of the API.    For jpype.dbapi2 there is a property call connection which allows you to get at anything that is available in Java including stuff not defined in the Python dbapi protocol.
