### ISSUE TITLE
ImportError for JPype 1.3.0 for Python 3.9.7 Win 10

### ISSUE THREAD

**Issue by pallavi422009** [jpype-project/jpype#1014]
Installed JPype1 1.3.0 on Windows 10
Python Version: 3.9.7 64-bit

Error:

import jpype
Traceback (most recent call last):
File "", line 1, in
File "C:\Python\Python39\lib\site-packages\jpype_init_.py", line 18, in
import _jpype
ImportError: DLL load failed while importing _jpype: The specified module could not be found.

Couldn't find any solution on other platforms hence raised here.

**Comment by Thrameos** [comment]
Your installation of JPype is incomplete or corrupt.   When shipped jpype should have a directory called jpype containing ``__init__.py`` and many module files, a jar ``org.jpype.jar`` and C module ``_jpype.cpython-39-x86_64-win.dll``.   I would recommend uninstalling your current and reinstall ``JPype1`` using pip or anaconda.

See https://jpype.readthedocs.io/en/latest/install.html

**Comment by Nemo2011** [comment]
1.Use wheel
2. Use `python setup.py build` before running `install`

**Comment by WTGerber** [comment]
Will you please post a link as to where to download the visual studio build tools?

**Comment by Thrameos** [comment]
Please  read the docs  https://jpype.readthedocs.io/en/latest/install.html#windows
