### ISSUE TITLE
Error when converting a 3D Java array to numpy

### ISSUE THREAD

**Issue by cowwoc** [jpype-project/jpype#1015]
Version 1.3.0

To date I have used `np.array(javaArray)` to convert `float[]` or `float[][]` Java arrays to numpy and this has worked.

Today I needed to convert a `float[][][]` Java array to numpy and `np.array()` failed with `ValueError: could not broadcast input array from shape (5,2) into shape (5,)`.

My Java array has a shape `float[5839][5][2]`.

Am I doing anything wrong? Shouldn't this kind of conversion work?

**Comment by john-hen** [comment]
I, for one, cannot produce this issue, but maybe I'm missing something.

```python
import jpype
from jpype.types import *
import numpy

jpype.startJVM()

random_numbers = numpy.random.rand(5839, 5, 2).astype(numpy.float32)

javaArray = JArray(JFloat, random_numbers.ndim)(random_numbers)
assert repr(javaArray) == "<java array 'float[][][]'>"
assert len(javaArray) == 5839
assert len(javaArray[0]) == 5
assert len(javaArray[0][0]) == 2

numpy_array = numpy.array(javaArray)
assert numpy_array.dtype == numpy.float32
assert (numpy_array == random_numbers).all()
```

**Comment by cowwoc** [comment]
Sorry for the false alarm. I ended up discovering that numpy uses this error message to indicate that one of dimension contains more nested elements than another. For example, `javaArray[0][0]` contains a nested `array[5]` while `javaArray[0][1]` contains a nested `array[2]`.

Once I fixed that problem the error went away.
