### ISSUE TITLE
Ambiguous Overloads for functional interfaces with different argument counts

### ISSUE THREAD

**Issue by Christopher-Chianelli** [jpype-project/jpype#1016]
# Description

When a Java method have multiple overloads with functional interfaces, an Ambiguous Overloads Type Error is raised when attempting to call the method with a Python Function.

In particular, this is valid in Java:

```java
public class MyClass {
    public static String apply(Function<String, String> mapper) {
        return mapper.apply("1");
    }

    public static String apply(BiFunction<String, String> mapper) {
        return mapper.apply("1", "2");
    }

    public static void main(String[] args) {
        System.out.println(MyClass.apply(number -> "Number " + number))
        // "Number 1"
        System.out.println(MyClass.apply((number1, number2) -> "Number " + number1 + " and " + number2))
        // "Number 1 and 2"
    }
}
```

But this is not valid in Python
```python
import jpype
import jpype.imports

jpype.startJVM(classpath=['...'])


def single_arg_function(arg):
    return f'Number {arg}'


def two_arg_function(arg1, arg2):
    return f'Number {arg1} and {arg2}'


from org.acme import MyClass
assert str(MyClass.apply(single_arg_function)) == 'Number 1'
assert str(MyClass.apply(two_arg_function)) == 'Number 1 and 2'
```

```
TypeError: Ambiguous overloads found for org.acme.MyClass.apply(function) between:
public static java.lang.String org.acme.MyClass.apply(java.util.function.BiFunction)
public static java.lang.String org.acme.MyClass.apply(java.util.function.Function)
```

# Workaround

If you know exactly the functional interfaces you are using, cast to proxies using `inspect.signature`

```python
def cast(python_function):
    parameters = inspect.signature(python_function).parameters
    arg_count = len(parameters)
    if arg_count == 1:
        return JObject(python_function, Function)
    elif arg_count == 2:
        return JObject(python_function, BiFunction)
    else:
        raise Exception(f'Unsupported number of arguments: {arg_count}')


assert str(MyClass.apply(cast(single_arg_function))) == 'Number 1'
assert str(MyClass.apply(cast(two_arg_function))) == 'Number 1 and 2'
```

# Use Case

Make it easier to use Java Libraries in Python. Getting an ambiguous type error confuse Python users unfamiliar with Java, potentially causing them to abandon trying to use the technology. There are a few places in OptaPlanner (particular `Joiners`) where there are multiple overloads, same number of args, but different Functional Interfaces (with different parameter counts). Thus, it possible to do something like `Joiners.lessThan(item -> item.id, otherItem -> otherItem.item.id)` and `Joiners.lessThan((item1, item2) -> item2.id, otherItem -> otherItem.item.id)`  because the functional interfaces have a different argument count. I would like Python users to have the same experience:  `Joiners.lessThan(lambda item: item.id, lambda otherItem: otherItem.item.id)` and `Joiners.lessThan(lambda item1, item2: item2.id, lambda otherItem: otherItem.item.id)`. Currently, to achieve this behaviour, I would need to create a custom Joiners class that uses the casting workaround posted above.

# Reproducer
https://github.com/Christopher-Chianelli/issue-reproducer/tree/jpype-ambiguous-types-for-functional-interfaces-with-different-argument-counts

# Expected Behaviour

If there are overloads with the same argument counts but have functional interfaces with different argument counts, and a function is passed, inspect the function parameter count and cast it to the functional interface that have the same number of arguments. If no interface have the same number of parameters, raise a No Overload found Error. This does not solve the case where the Functional interfaces have the same parameter count, where casting must be used (the same as Java).

**Comment by Thrameos** [comment]
Why not just use the casting operator?   You should just be able to cast to Function or Bifunction to choose an overload using @.  That is what is tested in the test cases.

**Comment by Christopher-Chianelli** [comment]
Simple: I don't want to force my users to use casting operators. I am trying to hide the fact Java is even used. (A side note, the casting operator via `@` is not documented in https://jpype.readthedocs.io/en/latest ; it recommends using `JObject(python_object, type)`. Hitting this "Ambiguous overloads found" will surprise the user, and discourage them from continuing. I am fine working around it (as I work with Java and know what types to use) but plain Python users, who know nothing about Java (or the types) do not.

**Comment by Christopher-Chianelli** [comment]
(FWIW, how to extract python function argument count in C: https://stackoverflow.com/a/1117735 )

**Comment by Christopher-Chianelli** [comment]
I did an experiment with passing functions with a different number of arguments than the interface to Java:

```python
import jpype
import jpype.imports
from jpype import JImplements, JOverride, JObject

jpype.startJVM(classpath=['target/issue-reproducer-8.11.0.Final.jar'])

from java.util.function import Function, BiFunction

def single_arg_function(arg):
    return f'Number {arg}'


def two_arg_function(arg1, arg2):
    return f'Number {arg1} and {arg2}'


from org.acme import MyClass

# Accept Function
print(str(MyClass.noOverloadApply(two_arg_function)))

# Accept BiFunction
print(str(MyClass.noOverloadApply2(single_arg_function)))
```

Result: Python raises a TypeError for both:
```
print(str(MyClass.noOverloadApply2(single_arg_function)))
TypeError: single_arg_function() takes 1 positional argument but 2 were given
```

```
print(str(MyClass.noOverloadApply(two_arg_function)))
TypeError: two_arg_function() missing 1 required positional argument: 'arg2'
```

Which means making `single_arg_function` not being castable to BiFunction will not break backward compatibility (unless someone is checking the message).

I'll try an attempt at this.

**Comment by Christopher-Chianelli** [comment]
There is one extra case that need to be considered: default arguments (i.e. the following):

```
def two_arg_function(arg1, arg2=None):
    return f'Number {arg1} and {arg2}'
 
```

in which case `two_arg_function` is both a Function and a BiFunction

**Comment by Christopher-Chianelli** [comment]
Created PR https://github.com/jpype-project/jpype/pull/1017
