### ISSUE TITLE
JVM crashes when converting a single-element numpy array to a Java float[]

### ISSUE THREAD

**Issue by cowwoc** [jpype-project/jpype#1020]
Version 1.3.0
Windows 10.0.19044.1387

Apologies in advance for not having a minimal testcase but the problem looks something like this...

Given Java method:

```
class Bomb
{
  public static String explode(float[] input)
  {
    return "oops";
  }
}
```

When invoking the following Python code:

```
Bomb.explode(np.array(1010))
```

The JVM crashes with:

```
Current thread (0x0000020c950f9490):  JavaThread "main" [_thread_in_native, id=43524, stack(0x0000006959600000,0x00000069597f0000)]

Stack: [0x0000006959600000,0x00000069597f0000],  sp=0x00000069597d1090,  free space=1860k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [KERNELBASE.dll+0x34f69]
C  [VCRUNTIME140.dll+0x6480]
C  [_jpype.cp39-win_amd64.pyd+0x34c87]
C  [_jpype.cp39-win_amd64.pyd+0x3d6e3]
C  [_jpype.cp39-win_amd64.pyd+0x327d5]
C  0x0000020ca7afd621

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.jpype.manager.TypeFactoryNative.newWrapper(JJ)V+0
j  org.jpype.JPypeContext.newWrapper(J)V+16
v  ~StubRoutines::call_stub

siginfo: EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363), ExceptionInformation=0x0000000019930520 0x00000069597d1250 0x00007ffa254ada78 0x00007ffa25430000 
```

If I replace the python code with `Bomb.explode(np.array([1010]))` the problem goes away.

This is 100% reproducible on my end. Can you reproduce this on your end?

**Comment by cowwoc** [comment]
To be honest, I don't fully understand the meaning of `np.array(100)` but if you dig into https://stackoverflow.com/q/70344433/14731 people are providing various explanations. All I know is that I had a typo in my python code and it caused the JVM to crash ;) So it would be nice to fix this.

**Comment by Thrameos** [comment]
Hmm.  I was not able to replicate it with my copy of 1.3.  

```
import jpype
import numpy as np
jpype.startJVM()
a=np.array(1010)
jpype.JFloat[:](a)
```

Gives
```
Traceback (most recent call last):
  File "test4.py", line 6, in <module>
    jpype.JFloat[:](a)
ValueError: Array size invalid
```

Perhaps it is specific to calling a method.  I will have to try again later.

**Comment by Thrameos** [comment]
I tried with call code and it does fail but not in the a segfault.  Instead it gets.

**Comment by cowwoc** [comment]
@Thrameos Here is a minimal testcase:

Java code:
```
package com.company;

public class Testcase
{
	public static void run(float[] input)
	{
	}
}
```

Python code:
```
import jpype
import numpy as np

jpype.startJVM()
Testcase = jpype.JClass("com.company.Testcase")
a = np.array(101)
Testcase.run(a)
```

**Comment by cowwoc** [comment]
@Thrameos I'm not sure if you saw my last comment. If I don't hear back within another day I am going to assume you do not receive notifications for closed issues and will open a new issue containing the minimal testcase. Kind regards.

**Comment by Thrameos** [comment]
Sorry not sure why the issue got closed.   Must have misclicked on the browser.  Yes I have replicated the issue.  Fix should happen over the winter vacation as I am currently occupied with a work delivery.

**Comment by cowwoc** [comment]
Sounds good. Thank you.
