### ISSUE TITLE
Kotlin objects not working as singletons

### ISSUE THREAD

**Issue by Cheeseboy8020** [jpype-project/jpype#1036]
am trying to use a kotlin object from jpype in python as a singleton. When I try to call any methods I get this: ```TypeError: No matching overloads found for *static*``` I tried importing with ```from package import Singleton``` and ```jpype.Jpackage(package).Singleton```

**Comment by Christopher-Chianelli** [comment]
When you import a class in JPype, you get the class, not an instance of the class. The error tells you it cannot find a static method, which means you are calling the method on the class versus an instance of the class.

There is a static field `INSTANCE` that Kotlin generates for singletons. Thus, to use Kotlin singletons in JPype, do this:

```
from package import Singleton as SingletonClass
Singleton = SingletonClass.INSTANCE

Singleton.someMethodOnSingleton()
```
