### ISSUE TITLE
How do I investigate code that kills the kernel?

### ISSUE THREAD

**Issue by NicolasRouquette** [jpype-project/jpype#1038]
I am starting JPype with a classpath that contains a [Gradle wrapper jar](https://docs.gradle.org/current/userguide/gradle_wrapper.html)

The idea is to call Gradle from jpype.

Roughly, this is:

```python
# Import module
import jpype

# Enable Java imports
import jpype.imports

# Pull in types
from jpype.types import *

jpype.startJVM(classpath = ['gradle/wrapper/gradle-wrapper.jar'])
from org.gradle.wrapper import GradleWrapperMain
GradleWrapperMain.main(["tasks"])
````

I would expect to see the usual gradle list of tasks available for the project.
Instead, the jupyterlab notebook tells me that the kernel crashed and has restarted; there is no output at all.

How do I get more visibility into what is going on to find out what causes the crash?

**Comment by NicolasRouquette** [comment]
For example, I can clone this repository: https://github.com/opencaesar/metrology-vocabularies

Then start jupyter lab and in a notebook copy/paste the python code above in a new notebook (I called it `Gradle.ipynb`)

After the last output:

```
BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed
```

I see the messages:

```
[I 2022-03-17 17:07:28.333 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), new random ports
[W 2022-03-17 17:07:28.333 ServerApp] kernel 7e962b22-6570-4cab-ab07-f22668c3b0bc restarted
[W 2022-03-17 17:07:28.334 ServerApp] kernel 7e962b22-6570-4cab-ab07-f22668c3b0bc restarted
[I 2022-03-17 17:07:28.349 ServerApp] Starting buffering for 7e962b22-6570-4cab-ab07-f22668c3b0bc:aedcb622-4851-4215-b255-5e6647b36fc4
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 2c282eb0-ea94-41aa-9783-5297f77f46b4
```

And the browser shows a modal dialog that the kernel crashed and restarted:

![image](https://user-images.githubusercontent.com/2359166/158913197-f33ee96a-d217-4026-9d17-ba029f097329.png)

Any ideas what's going on and how can I troubleshoot this?

**Comment by Thrameos** [comment]
I would recommend trying from the command line to see if there is some kind of dialog.  I suspect that Gradle is simply calling "exit()" when  you call main.   As python and java are running in the same process calling exit in Java would terminate Python.  So it may not be a crash.

**Comment by NicolasRouquette** [comment]
Thanks again for your prompt response. This makes sense.... I'll see if there is some option to prevent that.

**Comment by NicolasRouquette** [comment]
Hum.... looking at the version of trhe wrapper used in that project (6.5.1), the wrapper does not call java's `System.exit()`

https://github.com/gradle/gradle/blob/v6.5.1/subprojects/wrapper/src/main/java/org/gradle/wrapper/GradleWrapperMain.java#L38:L67

**Comment by NicolasRouquette** [comment]
hum... but the `org.gradle.launcher.GradleMain` could presumably call `exit()`:

https://github.com/gradle/gradle/blob/v6.5.1/subprojects/wrapper/src/main/java/org/gradle/wrapper/BootstrapMainStarter.java#L35

**Comment by NicolasRouquette** [comment]
indeed , it's Gradle that calls `exit()`:

https://github.com/gradle/gradle/blob/v6.5.1/subprojects/bootstrap/src/main/java/org/gradle/launcher/bootstrap/ProcessBootstrap.java#L38

**Comment by Thrameos** [comment]
Happy to help.  Hope you can find a solution.
