### ISSUE TITLE
Developer discussions on JPype: Open the GitHub Dicussions tab, a google forum, dev mailing list, or a zulip chat.

### ISSUE THREAD

**Issue by ge0ffrey** [jpype-project/jpype#1049]
A GitHub issue isn't always the best way to discuss complex things or share experiences. A GitHub Dicussions tab, a google forum, dev mailing list, or a zulip chat can do wonders.

The easiest way to fix this issue is to go into Github Settings, menu time General, and check the checkbox Discussions:
![Selection_1172](https://user-images.githubusercontent.com/176880/163575053-0000b300-c8ba-4d11-89d4-1fa6c5a71227.png)

And then link it from the jpype.org README.

**Comment by Thrameos** [comment]
@marscher Would you mind looking over this issue?

**Comment by ge0ffrey** [comment]
@Thrameos Thanks Karl.
Christopher has some interesting OptaPy benchmarks to share - about the cost of running a Python lambda inside Java code in a JVM thousands (ideally hundreds of thousands) times per second. For example `Joiners.equal(lambda lesson: lesson.timeslot)` in:

```
return constraint_factory \
            .forEach(LessonClass) \
            .join(LessonClass,
                [
                    # ... in the same timeslot ...
                    Joiners.equal(lambda lesson: lesson.timeslot),
                    # ... in the same room ...
                    Joiners.equal(lambda lesson: lesson.room),
                    # ... and the pair is unique (different id, no reverse pairs) ...
                    Joiners.lessThan(lambda lesson: lesson.id)
                ]) \
            .penalize("Room conflict", HardSoftScore.ONE_HARD)
```

**Comment by Thrameos** [comment]
Hmm, no response from @marscher yet.

**Comment by marscher** [comment]
Hi, sorry for the delay. I've enable discussions already on GH, but it is not yet linked in your documentation/README file.

**Comment by ge0ffrey** [comment]
Thank you @marscher! I 'll close this issue.

**Comment by ge0ffrey** [comment]
> not yet linked in your documentation/README file.

PR to add link in README: https://github.com/jpype-project/jpype/pull/1058
