### ISSUE TITLE
String concatenation with JChar causes segfault

### ISSUE THREAD

**Issue by hx2A** [jpype-project/jpype#1053]
When I attempt to use the `+` operator to concatenate a JChar and a Python string I get a seg fault:

``` python
In [1]: import jpype

In [2]: jpype.__version__
Out[2]: '1.3.0'

In [3]: jpype.startJVM()

In [4]: jpype.JChar("x")
Out[4]: 'x'

In [5]: jpype.JChar("x") + "test"
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000000, pid=11156, tid=11156
#
# JRE version: OpenJDK Runtime Environment 21.9 (17.0.2+8) (build 17.0.2+8)
# Java VM: OpenJDK 64-Bit Server VM 21.9 (17.0.2+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  0x0000000000000000
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/jim/Projects/ITP/pythonprocessing/py5generator/core.11156)
#
# An error report file with more information is saved as:
# /home/jim/Projects/ITP/pythonprocessing/py5generator/hs_err_pid11156.log
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=java-17-openjdk&version=34
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)
```

Reversing the order of the operands gives a `TypeError: cast of null pointer` exception.

The workaround in both cases is to use `str`:

``` python
In [5]: "test" + str(jpype.JChar("x"))
Out[5]: 'testx'

In [6]: str(jpype.JChar("x")) + "test"
Out[6]: 'xtest'
```

There may be a good reason why that operation is not allowed and using `str` is a simple enough workaround, but I wouldn't expect this to trigger a segfault.

My computer is using Fedora Linux, python 3.8.12, and OpenJDK Java 17

**Comment by Thrameos** [comment]
Definitely something requiring repair.

Testing 
"foo"+JChar("x") => works "foox"
JChar("x")+"foo" => fails segfault
JChar("x") + 1 => works 121
1 + JChar("x") => fails "null pointer"
"foo" + JChar("x") => fails "null pointer"
JChar(1)+JChar("x") => fails
JChar('x')-1 => works
1-JChar('x') => fails


It appears that the code is calling a bad slot and it also does not consider that Python would call add with the argument order reversed.    I will have to check this for every possible operation with jchar.   Should be fixed shortly.

**Comment by hx2A** [comment]
That was quick. Thank you! Will this make it in the 1.3.1 release?
