### ISSUE TITLE
jpype1 v1.4.0 release not on conda-forge

### ISSUE THREAD

**Issue by ctrueden** [jpype-project/jpype#1072]
Is anyone working on getting jpype 1.4.0 onto conda-forge? It looks like the [jpype1-feedstock](https://github.com/conda-forge/jpype1-feedstock/) needs [some TLC](https://github.com/conda-forge/jpype1-feedstock/pull/43), so the regro-cf-autotick-bot never filed a PR for the 1.4.0 release.

**Comment by Thrameos** [comment]
@marscher Can you look into this?   I haven't touched the conda before, and my work load is currently to high to investigate.

**Comment by marscher** [comment]
Usually the conda-forge bot opens up pull requests for newly uploaded PyPI packages. I need to investigate. I do not think it has something to do with the pypy pr.

**Comment by ctrueden** [comment]
Thanks @marscher for your help. Having jpype 1.4.0 on conda-forge is important for the bioimaging community. If there's anything I can do on my side, just let me know.

**Comment by ctrueden** [comment]
For anyone else interested in this issue, the PR to follow is conda-forge/jpype1-feedstock#44.
