### ISSUE TITLE
Fork + OpenConnection

### ISSUE THREAD

**Issue by jovans2** [jpype-project/jpype#1077]
Hello, I am trying to do the following:
Python script:
                       Parent process loads the jar file 
                       Child processes created through fork execute methods from the jar
Java function:
                       Access http://google.com via HttpURLConnection 

When I load the jar and execute function within the same process everything works as expected. 
When I load the jar and execute other functions that do not create URLConnections everything works as expected.
However, when I try to load the jar in the parent and execute HTTP-call function inside the children system gets blocked. There are no exceptions or errors, just infinitely waiting. 

Could you please advise how to proceed?
Thank you!

**Comment by Thrameos** [comment]
I believe it is documented in the documents that Java itself does not support operation though a "fork".   If you want to use multiprocessing with Java, then try to use "spawn".   You will need to start a new JVM in each child.    There is code for this in test/jpypetest.
