### ISSUE TITLE
Bug: datetime.strptime not working correctly after calling startJVM

### ISSUE THREAD

**Issue by LukasZahradnik** [jpype-project/jpype#1078]
## Bug description

Hello, I found a weird behavior of the standard Python `datetime` module after starting up the JVM. Namely, I found out that using `strptime` with a format containing the `%B` modifier does not work.

## Steps to reproduce the behavior

```python
import jpype
import datetime

# This line works correctly -> 2020-10-27 00:00:00
print(datetime.datetime.strptime("27 October 2020", "%d %B %Y"))

jpype.startJVM()

# This line (which is the same as the previous one) throws
# ValueError: time data '27 October 2020' does not match format '%d %B %Y'
print(datetime.datetime.strptime("27 October 2020", "%d %B %Y"))
```

## Expected behavior

In both cases, I should get the correct datetime without any exception.

## Environment

```
Python 3.9.7
JPype1 1.4.0
```

**Comment by Thrameos** [comment]
No idea why this would be the case.   Perhaps it is a common library that both Python and Java are using.

I will have to think some more and get back to you.

**Comment by LukasZahradnik** [comment]
Okay, thanks!

I did some more debugging, and I found out that before calling `startJVM`, the [locale_time object here](https://github.com/python/cpython/blob/4e796f56465f7264ddba63c8396d2649e098b617/Lib/_strptime.py#L321) has the language set to `(None, None)` (months and days names are set to the English version). After calling the `startJVM` function, the language is suddenly set to `('cs_CZ', 'UTF-8')` - which is my actual language on my machine, and it also sets a month, days, etc. names to their Czech version, and therefore it cannot be parsed.

So I thought that maybe the language set in Java is `cs_CZ`, and it somehow synced python; however, when I check the Java default locale, I get `en_US`.

```python
import jpype.imports
import java.util.Locale
import java.lang

print(java.util.Locale.getDefault())  # en_US
print(java.lang.System.getProperty("user.country"), java.lang.System.getProperty("user.language"))  # US en
```

**Comment by Thrameos** [comment]
Sounds like the best we can do us document the interaction.   Both python and java are using the C library.  When Java is starting it is initializing the locale.  Python is then getting those settings.

**Comment by LukasZahradnik** [comment]
Do you think it would be feasible for jpype to store locales before starting up a JVM and then setting locales back (maybe have an argument flag to turn it on/off)?

**Comment by Thrameos** [comment]
It is possible, but I am not really an expert on locales.   What need to be preserved before and after starting the JVM?

**Comment by LukasZahradnik** [comment]
As I checked [before](https://github.com/jpype-project/jpype/issues/1078#issuecomment-1164685194), all categories of locale (except for `LC_CTYPE`) were set to a different value after the JVM startup.

This snippet preserves all categories of locales and, after the JVM startup, sets them back to their original value. However, I am also not an expert on locales.

```py
import locale


categories = [
    locale.LC_CTYPE, locale.LC_COLLATE, locale.LC_TIME, locale.LC_MONETARY, locale.LC_MESSAGES, locale.LC_NUMERIC
]

locales = {category: locale.getlocale(category) for category in categories}

jpype.startJVM()

for category, locale_value in locales.items():
    locale.setlocale(category, locale_value)
```

I haven't found anything else that would need to be preserved.

**Comment by Thrameos** [comment]
Okay see if the PR addresses your issue.   If it does then I will send it to the maintainer for review.

**Comment by Thrameos** [comment]
It looks like LC_MESSAGES is missing on windows.   I guess we can skip that one.
