### ISSUE TITLE
Incorrect JRE requirement >=7, should be >=8

### ISSUE THREAD

**Issue by stippingerm** [jpype-project/jpype#1083]
Doc at https://jpype.readthedocs.io/en/latest/install.html tells 

> JPype source distribution includes a copy of the Java JNI header and precompiled Java code, thus the Java Development Kit (JDK) is not required. JPype has been tested with Java versions from Java 1.7 to Java 13.

However running on JRE 1.7
```sh
ubuntu@dcs-master:~$ java -version
java version "1.7.0_201"
OpenJDK Runtime Environment (IcedTea 2.6.17) (7u211-2.6.17-0ubuntu0.1)
OpenJDK 64-Bit Server VM (build 24.201-b00, mixed mode)
```

and trying to start `jpype` gives
```python
>>> import jpype
>>> jpype.startJVM()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../anaconda3/lib/python3.9/site-packages/jpype/_core.py", line 226, in startJVM
    _jpype.startup(jvmpath, tuple(args),
SystemError: java.lang.UnsupportedClassVersionError: org/jpype/classloader/DynamicClassLoader : Unsupported major.minor version 52.0
```

where version 52.0 corresponds to Java 8 (or 1.8)

Installing Java 8 solves the incompatibility. This confirms that either the doc should be updated or the jpype class header downgraded to major.minor version 51.0

**Comment by Thrameos** [comment]
It may still be possible to compile a library for the older Java versions, but the build process is currently tasked to Java 1.8 (which is also the only one available on the cloud where we build.)     If you try to build and it still fails then we should update the documentation.

**Comment by marscher** [comment]
we should update the documentation, as we currently only test JDK8.
