### ISSUE TITLE
distutils will be deleted in Python 3.12

### ISSUE THREAD

**Issue by marscher** [jpype-project/jpype#1085]
https://peps.python.org/pep-0632/#migration-advice

I'm working on a PR for this. But there is no rush, the release schedule for Python 3.12 is October 2023.

**Comment by Thrameos** [comment]
I think I addressed this in the py3.11 patch.  Or at least those portions that gave a warning during testing.

**Comment by marscher** [comment]
Sorry if I didn't catch this. Could you please point to the relevant PR and close this one?
