### ISSUE TITLE
Keeps running after JDBC signon cancel

### ISSUE THREAD

**Issue by JipSogeti** [jpype-project/jpype#1088]
When running the code below I'm presented with a popup asking for my username and password.

![Schermafbeelding 2022-09-06 115341](https://user-images.githubusercontent.com/94383160/188605686-c2afe15f-7501-43d1-aa95-16aadad82e88.png)

If I press cancel then an SQLException is raised: `java.sql.java.sql.SQLException: java.sql.SQLException: The application server rejected the connection. (Signon was canceled.)`. I added a try block and allow it to pass on exception, so the print statement is executed. However the python script never quits.

```python
import os
import jpype
import jpype.dbapi2

import urllib.request
from pathlib import Path

jt400_version = "11.0"
jt400_jar_filename = f"jt400-{jt400_version}.jar"
jt400_jar_url = f"https://repo1.maven.org/maven2/net/sf/jt400/jt400/{jt400_version}/{jt400_jar_filename}"

classpath = os.path.join(os.getcwd(), "jt400-11.0.jar")

if Path(classpath).is_file():
    print(f"Already exists: {jt400_jar_filename}")
else:
    urllib.request.urlretrieve(jt400_jar_url, classpath)

jpype.startJVM(classpath=classpath)

try:
    jpype.dbapi2.connect("jdbc:as400://localhost", driver="com.ibm.as400.access.AS400JDBCDriver")
except:
    pass

print("test")
```

How can I allow the python script to exit when the end of the file is reached? 

I've tried adding this to the bottom of the script:

```python
jpype.java.lang.Thread.detach()
jpype.shutdownJVM()

jpype.java.lang.Thread.detach()
jpype.java.lang.System.exit(0)
```

But still the python script never exits.

**Comment by Thrameos** [comment]
I wrote back on this topic this morning, but it appears that it didnt get posted.

The most likely issue us that the driver started a non daemon thread that must be terninated or set to daemon before proceeding to JVM shutdown.   If the driver is open source you should find the thread launch.  If not you will need to call Java to get the list of available running threads.  Hopefully the driver writers did not eat the interrupt message, or you will find this very difficult (though not impossible depending your technical skill.)  If they did eat interrupt, your options are limited to calling eith the Java exit method or the Java halt/terminate method.  These will exit without returning to python so they are generally discouraged.    

This is not a JPype bug as JPype is following the defined JVM protocols.  You can find the shutdown sequence as well as the available user hooks in the org.jpype module under natice/java in the JPypeContext object.   In there we attempt to interrupt every non deamon thread which should have allowed shutdown to proceed.  If they ate it then they have to provide a way to safely terminate in their documentation or you will need to find a way to covert it to a daemon.

**Comment by JipSogeti** [comment]
Thanks a lot for replying, glad it's not a but with jpype! I found a workaround: not showing the popup at all by setting `prompt` to `false`: `jdbc:as400://$AS400_HOST;naming=sql;errors=full;libraries=$AS400_DBNAME;prompt=false` according to [this article](https://access.redhat.com/solutions/2074443).
