### ISSUE TITLE
Instantiate a Python class implementing a Java interface from Java

### ISSUE THREAD

**Issue by JRosenkranz** [jpype-project/jpype#1089]
I am looking to instantiate an instance of a python class implementing a Java Interface as follows:

## java inteface

```java
interface MyInterface {
     int call(int input);
     void doSomething();
}
```

## python class implementing  java interface
```python
@JImplements("my.package.MyInterface")
class MyPythonImplementation:
     
     @JOverride
     def call(self, input):
          # some python implementation here

     @JOverride
     def doSomething(self):
          # some python implementation here
```

Then I would like to do something like this:

## java method instantiating python implementation of java interface

```java
public void myJavaMethod() {
     MyInterface myObject = new MyPythonImplementation();

     // call the underlying python implementation
     myObject.doSomething();
}
```

Im assuming the above (myJavaMethod) cannot be done as shown. Is there a way this can be achieved with reflection? Or some other method of accessing this underlying implementation? I know that I can instantiate the class in python and pass it to java, but I am wondering if it is also somehow possible to access directly through java (something like a builder exists in java and when it is called (from java), if it sees the python class implementation in the jvm, it will instantiate that)

**Comment by Thrameos** [comment]
You can do that or something close.   The only issue is that you can't call "new" directly to get a Python object.  Instead use the java.util.function.Supplier as a stub to implement your new function.

In Python
```
@jpype.JImplements("java.util.function.Supplier")
class MySupplier(object):
      @jpype.JImplements
      def get(self):
          // Create a new instance
          return MyPythonImplementation()

# install the hook
MyFactory.supplier = MySupplier()
```

In Java
```
public class MyFactory
{
    public static Supplier<MyInterface> supplier;
}

public void myJavaMethod() 
{
     // Call Python to get a new object
     MyInterface myObject = MyFactory.supplier.get();

     // call the underlying python implementation
     myObject.doSomething();
}
```

I use this pattern to install plotting routines into Java libraries I am debugging.   Note the supplier pattern is only needed if you need a fresh object each time.   The generic java.util.function library provides lots of hooks that you can use to extend Java into Python.

For simple auditing work I use this pattern.
```
@jpype.JImplements("java.util.function.Consumer")
class MyPlotRoutine(object):
     @jpype.JImplements
     def accept(self, obj):
         # do plotting here
         return

MyClass.audit = MyPlotRoutine()
```

In Java
```
public class MyClass
{
    public static Consumer<AuditData> audit = null;
 
    public void process(Blah blah)
    {
      ....

      // if an audit is requested convert the state into AuditData and call Python
      if (audit!=null)
      {
          // Call Python to plot state
          audit.accept(new AuditData(blah, args)):
      }
      ...
}
```

**Comment by JRosenkranz** [comment]
Works perfectly for me. Thanks!
