### ISSUE TITLE
Zulu's openjdk8 cannot use jpype

### ISSUE THREAD

**Issue by howdypl** [jpype-project/jpype#1090]
![Uploading image.png…]()

**Comment by howdypl** [comment]
<img width="681" alt="image" src="https://user-images.githubusercontent.com/38419273/189916603-d04dcead-9320-478d-86cc-9247e5817f1d.png">

**Comment by howdypl** [comment]
Arm architecture

**Comment by Thrameos** [comment]
Not sure I can be much assistance on this one.   Does the Python and JVM have the same machine architectures?  Multiple threads indicate that this is a bug of some kind in the JVM and not necessarily tied to the JPype.   I would suggest moving to a later version of the JVM to see if it works there.

**Comment by marscher** [comment]
Could you please try to compile JPype yourself using the JDK on the target system? So set the environment variable JAVA_HOME to your JDK and then invoke pip install https://github.com/jpype-project/jpype

I suspect that our shipped jni.h may be the cause of this.
