### ISSUE TITLE
Java 17 Support

### ISSUE THREAD

**Issue by Robbie-Palmer** [jpype-project/jpype#1097]
JPype errors when trying to run with JRE v17

```
Error occurred during initialization of VM
Unable to load native library: 
```

JPype currently supports up to Java 13
> JPype has been tested with Java versions from Java 1.7 to Java 13

Opening this issue to track Java 17+ support

**Comment by Thrameos** [comment]
I will have to investigate.

**Comment by astrelsky** [comment]
I have used jpype with jdk17 without a problem. You may need to provide some more information regarding your operating system and the exact jvm you are trying to use.

**Comment by Robbie-Palmer** [comment]
Ah sorry, it happened a couple of times but now I can't reproduce
It is now working with my freshly installed JRE v17
