### ISSUE TITLE
Release for Python 3.11

### ISSUE THREAD

**Issue by Thrameos** [jpype-project/jpype#1099]
- [x] Start from the release branch
      ``git checkout release``
- [x] Make a new branch for the release cycle
      ``git checkout -b releases/{version}``
- [x] Merge the current master with the release
      ``git pull origin master``
- [x] Start a release
      ``bumpversion release``
- [x] Edit doc/CHANGELOG.rst
- [x] Send the release to be evaluated
      ``git push``
- [x] Verify CI on azure
- [x] Manually trigger a ``jpype.release`` on azure
      If successful, download the artifacts for publication.
- [x] Advance the release pointer
      ``git checkout release``
      ``git merge releases/<version>``
- [x] Publish the release
  - Add draft release on github
  - Attach the artifacts to the release.
- [x] Start master on a new cycle
  - Use a PR to pull release back to master
  - ``git checkout master``
  - ``git checkout -b cycle``
  - ``git merge release``
  - ``bumpversion patch``
  - Use PR to insert the cycle in master

**Comment by Thrameos** [comment]
@marscher  Not sure how many tries I will have to take for this release.  There appears to be a problem with some of the the pinned versions not working with Python3.11.   Hopefully unpinning them will work.   If not I will have to come up with a new testing solution.

**Comment by Thrameos** [comment]
Looks like the release will clear.   I should be able to release tomorrow morning.

**Comment by Thrameos** [comment]
It appears that the linux image does not have 3.11 available.   I can distribute the rest and then try to get those built later.

**Comment by Thrameos** [comment]
@marscher It seems like we need to change to manylinux2014 image to get Python 3.11.   I can change to this for all future builds.  But for now I am just updating the release script for a one off run.   I am not sure if I need to split the build so that pre 3.11 goes with the manylinux2010 image.  If you have some insight I can get it setup for our future releases.

Assuming everything looks good, the ball is in your court to push this to PyPi.  Given the level of changes required for 3.11, I don't think one day after the release is too bad given that we have to wait for the azure image to be updated before we can release.

**Comment by marscher** [comment]
Thanks! PyPI push of wheels and source dist has been done.

**Comment by marscher** [comment]
Conda-forge support for 3.11 will be added by their bot soon. It has to pick up the PyPI push first.
