### ISSUE TITLE
On python 2.6 JavaException class is not used at all

### ISSUE THREAD

**Issue by marscher** [jpype-project/jpype#112]
noticed that as I rewrote the exception test.

**Comment by baztian** [comment]
Can you elaborate on this please? What do you mean by "class is not used at all". Why especially in Python 2.6?
I've had a similar problem with JavaException and Python 2.6. See https://code.google.com/p/unittest-ext/issues/detail?id=90 Don't know why that test failed.

**Comment by marscher** [comment]
Am 12.03.2015 um 21:11 schrieb baztian:
> Can you elaborate on this please? What do you mean by "class is not used
> at all". Why especially in Python 2.6?
> I've had a similar problem with JavaException and Python 2.6. See
> https://code.google.com/p/unittest-ext/issues/detail?id=90 Don't know
> why that test failed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/originell/jpype/issues/112#issuecomment-78595043>.
>
This has only been an observation. The class is not being used to handle 
exceptions raised in the jvm. I think this borks exception handling for 2.6.
