### ISSUE TITLE
__eq__ for comparable should use equals()?

### ISSUE THREAD

**Issue by michi42** [jpype-project/jpype#1120]
Currently JPype's implementation of `__eq__` uses `compareTo()` if one of the objects implements `Comparable`. However, this leads to problems when comparing objects of two different classes, as `compareTo()` usually does not handle this case, e.g. for Enums which implement `compareTo()` only among objects of the same class.

Also, in Java it is only recommended - but not strictly required - that `compareTo()` is consistent with `equals()`.

Is there a reason why not to use `equals()` for comparing any object?

Example:
```python
import jpype as jp
jp.startJVM()
jp.java.time.temporal.ChronoUnit.SECONDS.equals(jp.java.util.concurrent.TimeUnit.SECONDS)
# >>> False
jp.java.time.temporal.ChronoUnit.SECONDS == jp.java.util.concurrent.TimeUnit.SECONDS
```
The last line crashes with:
```
Traceback (most recent call last):
  File "Enum.java", line 55, in java.lang.Enum.compareTo
Exception: Java Exception
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
java.lang.java.lang.ClassCastException: java.lang.ClassCastException
```

**Comment by Thrameos** [comment]
Hmm.  seems like an issue.   So should we always use ``equals()``?  I though that equals was supposed to be strict and ``compareTo`` was supposed to be more lenient but it looks like this is the opposite case.   Looking at the documentation I would not have expected the ClassCastException, but I think that fixing it to always use equals (or !equals) would be safest.

**Comment by michi42** [comment]
Java `Object` defines `equals(Object)`, which is supposed to accept any other object to test for equality. If the two objects are of different classes, `equals()` shall not throw but instead just return `false` (or `true` in case they are of different classes but nevertheless considered "equal" e.g. different implementations of `Set` containing the same elements).

On the other hand, `Comparable<T>` implements `compareTo(T)` which is only expecting other objects of type `T`. Often enough, it is uses as in `class Foo implements Comparable<Foo>`, i.e. only allowing comparisons with itself. In Java this is checked at compile time...

So yes, I'm tempted to say that `__eq__` should always use `equals()` (and `__neq__` likewise). `compareTo()` should only be used for `__lt__`, `__le__`, `__gt__` and `__ge__`. At least, that's what I would naively expect.

**Comment by michi42** [comment]
Thanks a lot, indeed that fixes the enum case for me.

However, when testing, I found another weird case: comparing to a python `int` gives a `SystemError: Fail in conversion`. Comparing to a `JInt` segfaults (examples below). I don't think this is related to the fix though.

For what the other (comparison) operators are concerned, I would expect exceptions. Python types behave the same: `"M" == 42` is well-defined (=false), but `"M" < 42` raises TypeError.

```
>>> import jpype as jp
>>> jp.startJVM()
>>> jp.java.time.temporal.ChronoUnit.SECONDS == 42
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: Fail in conversion

>>> jp.java.time.temporal.ChronoUnit.SECONDS == jp.JInt(42)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f83332ba8c0, pid=5098, tid=5098
#
# JRE version: OpenJDK Runtime Environment Zulu11.60+19-CA (11.0.17+8) (build 11.0.17+8-LTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu11.60+19-CA (11.0.17+8-LTS, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x59b8c0]  AccessInternal::PostRuntimeDispatch<G1BarrierSet::AccessBarrier<1097844ul, G1BarrierSet>, (AccessInternal::BarrierType)2, 1097844ul>::oop_access_barrier(void*)+0x0
```

**Comment by Thrameos** [comment]
Yes, I found the same issue while looking at the coverage report.   It wasn't entirely unrelated the issue is that in the line before the switch statement it fails to check if the type is primitive before dereferencing as an object.   I added more test cases.

Hopefully it will hit all the paths in coverage.   Otherwise I will need to try again.

Thanks for testing!
