### ISSUE TITLE
Access Java Enum .name() when a .name property is defined

### ISSUE THREAD

**Issue by MrFizzyBubbs** [jpype-project/jpype#1123]
When attempting to access a Java Enum that has a `.name` property, the `.name()` method appears to be overwritten when using JPype. Both `.name` and `toString()` return `"none"` for `Slot.NONE`. Is there anyway to return the Enum's name in this instance? ie. `Slot.NONE -> "NONE"`. A simplified example of this is provided below (actual file available [here](https://github.com/kolmafia/kolmafia/blob/main/src/net/sourceforge/kolmafia/equipment/Slot.java)).

```java
public enum Slot {
  NONE("none");

  public final String name;

  Slot(String name) {
    this.name = name;
  }
}
```

```python
from my.jar import Slot

Slot.NONE.name  # returns "none"
Slot.NONE.toString()  # returns "none"
```

**Comment by MrFizzyBubbs** [comment]
Adapting the information I found on this [SO post](https://stackoverflow.com/questions/19121961/jpypes-properties-access-shadows-method-with-property-name), I was able to fetch the desired method with the code below.

```python
name_method = [method for method in Slot.class_.getMethods() if method.getName() == "name"][0]
name_method.invoke(Slot.NONE)  # returns "NONE"
```

**Comment by Thrameos** [comment]
There is something wrong with your example.  When I tested it with "toString()" I got "NONE".  Your class must be overrided both name() and toString().  

Assuming that the issue is just that "name" is not currently accessible (because it was a method in parent and is a field in the child) you can just call the parent method directly.

```
import jpype
import jpype.imports
jpype.startJVM(classpath=".")
import java
import java.lang.Enum

# Get the misbehaving class
Slot = jpype.JClass("Slot")

# Get the parent class name method (we can do this by reflection if there were some horrible class with both fields and methods with the same symbol)
name = java.lang.Enum.name

# Call the method with an explicit "this"
print(Slot.NONE) # ==> prints "none"
print(str(Slot.NONE)) # ==> prints "none"
print(Slot.NONE.toString()) # ==> prints "none"
print(name(Slot.NONE))  #  ==> prints "NONE"
```

**Comment by Thrameos** [comment]
I guess we can look over the possibility of doing better on collisions between methods and fields in the class builder process.   In Java you can have fields that have the exact same identifier as methods.  In those cases the method should hide the method.  

I did some testing and all the cases that I ran the method always hid the field.   But your case in which the parent declared the method but the child declared the field the conflict resolver failed to resolve it resulting in the method being hidden.   So there may be an issue with the conflict resolver failing to check the base classes before deciding to send a field to the Python type description.   

Either way the solution I sent should work.
