### ISSUE TITLE
JPype not implicity converting int to Java Integer for Java function call

### ISSUE THREAD

**Issue by MrFizzyBubbs** [jpype-project/jpype#1124]
I am attempting to pass a Python int to a Java function that accepts a java.lang.Integer.  I would expect the this to work since the [user guide](https://jpype.readthedocs.io/en/latest/userguide.html) states "Methods accepting an integer primitive will take either an Java integer primitive or a Python `int`...". However, I am getting a TypeError when attempting to do so on JPype 1.4.1 as shown below. 

```python
> FamiliarDatabase.isVariableType(1)
```

> TypeError: No matching overloads found for *static* net.sourceforge.kolmafia.persistence.FamiliarDatabase.isVariableType(int), options are: public static final boolean net.sourceforge.kolmafia.persistence.FamiliarDatabase.isVariableType(java.lang.Integer)

**Comment by Thrameos** [comment]
java.lang.Integer is not a primitive but instead is a boxed type.  So the user manual is correct.  Try adding a cast ``jpype.JInt(1) ``.  That type can then be boxed.  The ambiguity is that boxed types require a known size, but Python int is arbitrary size.

**Comment by MrFizzyBubbs** [comment]
My apologies, I was not familiar with boxed types. I've been porting my code over from `pyjnius` where this sort of conversion was performed automatically behind the scenes. Is there an option to do something similar in JPype or is casting  the only solution?

**Comment by marscher** [comment]
I think JPype offers such an option.
