### ISSUE TITLE
use with Java making use of jogl, other native code.

### ISSUE THREAD

**Issue by JoePfeiffer** [jpype-project/jpype#1125]
I'm trying to make use of ,https://github.com/SilentSys/orhelper , a Python package built on top of jpype to add scripting to https://github.com/openrocket/openrocket

Unfortunately, the particular class I need access to in OpenRocket makes use of OpenGL libraries, which are (near as I can tell -- if I'm wrong please tell me) written in native code.  I have been unable to find any information on how to set jpype up to get access to these libraries, or native code libraries in general.  Any help would be very appreciated.

I've opened an issue over on orhelper, https://github.com/SilentSys/orhelper/issues/10 , which contains more details.

**Comment by Thrameos** [comment]
This is a dependency issue well outside of jpype.   Dependency issues on third party libraries are not something I can resolve.
