### ISSUE TITLE
Python 3.11 compatibility

### ISSUE THREAD

**Issue by marscher** [jpype-project/jpype#1129]
We are currently using a private C-API of Python, which has been removed in Python 3.11. 
Namely the function `_PyObject_GC_Malloc` is now gone. We use it in `native/python/pyjp_value.cpp: In function ‘PyObject* PyJPValue_alloc(PyTypeObject*, Py_ssize_t)’` to allocate a Python object with a some extra space for the wrapped Java type.

There is a detailed discussion of the possible replacements/workarounds: https://discuss.python.org/t/equivalent-of-pyobject-gc-malloc-in-python-3-11/25919 
However the problem there is more related to a complicated class hierarchy. But it could give us some hints.

**Comment by marscher** [comment]
sorry, my bad. This was already fixed.

**Comment by Thrameos** [comment]
Yes I did address this one, but I have to make another attempt in 3.12 when then add the replacement API.
