### ISSUE TITLE
CI runs only for JDK11?

### ISSUE THREAD

**Issue by marscher** [jpype-project/jpype#1130]
I was just wondering if we need to add more JDK majors (e.g. version 20 just has been released) to our testing matrix. Just experienced a segfault when running our testsuite with jdk20.

**Comment by marscher** [comment]
The available Microsoft agents provide Java 8, 11, and 17. So I added a mixture of these in #1131

**Comment by Thrameos** [comment]
Sounds good.   I am not sure why we would have much difference, but it is best to test.
