### ISSUE TITLE
Failing to call a class that is compiled using JDK11 

### ISSUE THREAD

**Issue by lakshmiravalir** [jpype-project/jpype#1139]
When I am trying to create a object using Jpype,

```my_class = jpype.JClass("java.lang.Class").forName('com.java.example.SampleJavaClass')```
I am getting SampleJavaClass has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0", I know that this is due to using different JDK versions, however I am using JDK11 to build the jar and using it in Python 3.7. So, Is there any way to resolve this?

**Comment by Thrameos** [comment]
Your java runtime must be the same version or later version than the compiler use to build the jar.

Fixes for this issue:
- Change the Java run time to JDK 11 or later using JAVA_HOME
- Recompile the jar either with an older Java version or with the later version set to compile for an older binary format.

The second option will only work if the java source code does not use Java 11 features or libraries.  Thus I would tend to recommend the first.   Java 8 is rather old.
