### ISSUE TITLE
Does JPype support JPortable?

### ISSUE THREAD

**Issue by mexaros** [jpype-project/jpype#1173]
I have a custom utility built in python. Based on some client specific requirements, I need to add functionality to support a call to a set of java libraries (specifically dfc.jar). The problem i am running into is that the client server does not have java installed on the machine and we are not able to install it. To circumvent this i have placed Jportable on the server and modified my code to point to the location where java.exe resides. 

I am getting errors stating: 
OSError: [WinError 126] JVM DLL not found: C:\JavaPortable\App\Java\bin\java.exe
[87684] Failed to execute script 'main' due to unhandled exception!

I have confirmed that jvm.dll exists in C:\JavaPortable\App\Java\bin\server\
I have also ensured that dfc.jar was included in the compiled code via pyinstaller

Is the issue simply that JPortable is not compatible w/ JPype?

I have included an excerpt from the script below:
`import jpype
import os

executable_dir = os.path.dirname(os.path.abspath(__file__))
java_executable_path = r"C:\JavaPortable\App\Java\bin\java.exe"
dfc_library_path = os.path.join(executable_dir, "dfc.jar")
 
jvm_options = [
    "-Djava.class.path=" + dfc_library_path,
    "-Xmx512m"
]
 jpype.startJVM(java_executable_path, *jvm_options)`

**Comment by Thrameos** [comment]
JPype uses libjvm.dll/.so not the java.exe binary.   Your problem is likely that you pointed the JAVA_HOME to the executable rather than to the base directory for a java install.   Normally it looks for $JAVA_HOME/lib/server/libjvm.dll or such.   Ass for the compatibility of JPortable, that is really an unknown.  If it supports a valid JNI framework it will work.  If not it will bust.

My suggestion is use the JVM library path directly rather than having it search for one when testing.  Ie.

jpype.startJVM(“C:\My\Path\To\Libjvm.dll”)

**Comment by mexaros** [comment]
Thank you so much for your quick reply. Am i correct you mean jvm.dll(there is no libjvm.dll in JPortable)? Assuming so, I updated the script as follows however i still yield the same result.

`import os
import jpype

executable_dir = os.path.dirname(os.path.abspath(__file__))
#java_executable_path = r"C:\FCI\JavaPortable\App\Java\bin\java.exe"
java_executable_path = r"C:\JavaPortable\App\Java\bin\server\jvm.dll"
dfc_library_path = os.path.join(executable_dir, "dfc.jar")

jvm_options = [
    "-Djava.class.path=" + dfc_library_path,
    "-Xmx512m"
]

jpype.startJVM(java_executable_path, *jvm_options)`

**Comment by Thrameos** [comment]
It depends on the contents of the dll.  The one shipped with other jvm are under lib/server and must contain the symbol JNI_CreateJavaVM.  Without that symbol JPype can't start.   

I am surprised the error message would be the same.

**Comment by mexaros** [comment]
We performed a fresh install of java and bypassed the whole Jportable issue. This seemed to resolve the issue. Thank you!
