### ISSUE TITLE
Trouble starting JVM while pointing to a specific jar

### ISSUE THREAD

**Issue by dmorales6m** [jpype-project/jpype#1175]
I've developed a custom utility in Python that leverages JPype for accessing the Document Foundation Class via the dfc.jar file. Locally, my utility operates as expected without any issues. However, I've encountered a problem when deploying and running it on a client server machine. Specifically, the utility crashes when attempting to start the JVM with the classpath pointed at the dfc.jar file.

Currently the utility is just trying to connect to a Documentum Server, I have compiled to an .exe using pyinstaller and placed the dfc.jar file under the same directory in a folder titled 'dfc_jar'.

Here's the code snippet where the utility fails on the server:

      def start_jvm(self):
          exe_dir = os.path.dirname(sys.executable)
          jar_path = os.path.join(exe_dir, r"dfc_jar\dfc.jar")
          
          jpype.startJVM(jpype.getDefaultJVMPath(), "-Djava.class.path=" + jar_path) # CRASHING HERE.
          
          if jpype.isJVMStarted():
            print("JVM started successfully with default JVM.")
 
 
I have Verified the path to dfc.jar on the server is correct.
Tried adjusting JVM start-up parameters and classpath formatting to no avail.

Are there known compatibility issues with JPype when accessing specific jar files like dfc.jar on server environments?
Is there a recommended approach to diagnose or log more detailed information about the failure to start the JVM in such cases?

I greatly appreciate any insights, suggestions, or guidance the community can offer.
Thank you for your time and assistance!

**Comment by Thrameos** [comment]
I am not sure what you mean by crash. It did't find the jar? It segfaulted? 

 Also use the classpath keyword rather than setting it manually.  Manual setting is not portable across architectures as the path separator changes.
