### ISSUE TITLE
jpype.getDefaultJVMPath() returns None

### ISSUE THREAD

**Issue by rutvi-zymr** [jpype-project/jpype#118]
```
jpype.getDefaultJVMPath() returns None 
```

for following configuration

```
Jdk version: jdk1.7.0_72
python version: 2.7
Windows 64 bit
```

JAVA_HOME is set.

if we provide hard coded path of JVM in following statement

```
jpype.startJVM("C:\Program Files\Java\jdk1.7.0_72\jre\\bin\client\jvm.dll", "-ea", "-Djava.class.path=%s" % classpath)
```

python crashes.

Java is of 64 bit and python version is 32 bit. This might be a reason of crash.
Correct me if I am wrong.

Thanks

**Comment by marscher** [comment]
mixing 64 bit java with a 32bit python interpreter does not work. The path of JAVA_HOME is being considered, but are you also sure it exists? (If it would exist, it should be returned).

**Comment by rutvi-zymr** [comment]
Thanks for you help.

On another machine (which is windows 32 bit),

    jpype.getDefaultJVMPath()
    
returns following path-

    C:\Program Files\Java\jre7\bin\client\jvm.dll

Although JAVA_HOME is set to -
   
    C:\Program Files\Java\jdk1.6.0_43

does jpype.getDefaultJVMPath() consider JAVA_HOME?

**Comment by marscher** [comment]
it considers it and looks for jvm.dll in this path (if it exists). Does your jdk1.6.0_43 have a 'server' directory beneath?

**Comment by rutvi-zymr** [comment]
echo %JAVA_HOME%

prints

    C:\Program Files\Java\jdk1.6.0_43

Yes, jdk1.6.0_43 has server directory-

    C:\Program Files\Java\jdk1.6.0_43\jre\bin\server

**Comment by baztian** [comment]
@rutvi-zymr and @marscher what does a server directory indicate. Noticing that the server directory you list here is under jre...

**Comment by marscher** [comment]
Am 12.03.2015 um 21:16 schrieb baztian:
> @rutvi-zymr <https://github.com/rutvi-zymr> and @marscher
> <https://github.com/marscher> what does a server directory indicate.
> Noticing that the server directory you list here is under jre...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/originell/jpype/issues/118#issuecomment-78597992>.
>
I've noticed that gnu classpath based implementation do not work with 
jpype. So we exclude them during jmv.[so, dll] searching.

**Comment by Thrameos** [comment]
I believe this issue has been superseded in master with the architecture check.
