### ISSUE TITLE
jpype.imports not working accroding on linux user

### ISSUE THREAD

**Issue by juszynsk** [jpype-project/jpype#1183]
I have problem with usage of jpype.imports on my linux docker environment. I am trying to load activemq client jar file using below code:
```
import os
import jpype
import jpype.imports

classpath = f'{str.join(":", ["/home/ubuntu/Desktop/tests/jars/"+name for name in os.listdir("/home/ubuntu/Desktop/tests/jars")])}'
jpype.startJVM(jpype.getDefaultJVMPath(), "-ea", ('-Djava.class.path=' + classpath))

import org.apache.activemq.command.ActiveMQTextMessage as TextMessage
text_message = TextMessage()
print(text_message)
```

When I am using non root user account I receive:

`ModuleNotFoundError: No module named 'org.apache'`

but when I use root account than everything is fine and I receive java class object:

`ActiveMQTextMessage {commandId = 0, responseRequired = false, messageId = null, originalDestination = null, originalTransactionId = null, producerId = null, destination = null, transactionId = null, expiration = 0, timestamp = 0, arrival = 0, brokerInTime = 0, brokerOutTime = 0, correlationId = null, replyTo = null, persistent = false, type = null, priority = 0, groupID = null, groupSequence = 0, targetConsumerId = null, compressed = false, userID = null, content = null, marshalledProperties = null, dataStructure = null, redeliveryCounter = 0, size = 0, properties = null, readOnlyProperties = false, readOnlyBody = false, droppable = false, jmsXGroupFirstForConsumer = false, text = null}
`

When I use non-root user account I am still able to load class using jpype.JClass like below:

```
jclass = jpype.JClass("org.apache.activemq.command.ActiveMQTextMessage")
print(jclass())
```

Could You help me , am I missing something ?

**Comment by juszynsk** [comment]
Running below code:

```
jpype.startJVM(classpath=("/home/ubuntu/Desktop/tests/jars/*"))
print(jpype.java.lang.System.getProperty("java.class.path"))
```

On both users I receive

/home/ubuntu/Desktop/tests/jars/activemq-all.jar

**Comment by Thrameos** [comment]
Does activemq-all contain orge.apache?  If not then there is your problem.   If the classpath does not contain all the required Jars it can't possibly work.
