### ISSUE TITLE
Lost in the java & python type system 

### ISSUE THREAD

**Issue by dingiso** [jpype-project/jpype#1187]
Hi everyone, 

I am using jpype to call java functions. However, the function signature is not matched. I am trying to fix but it still wrong. 
Can someone help me to figure out? 

The java function is as below: 
( sorry about it, this function is too long and many self-defined types, but I have carefully handled them)

```java
public FidPopulateResult createNewLibraryFromPrograms(FidDB fidDb, String libraryFamilyName,
			String libraryVersion, String libraryVariant, List<DomainFile> programDomainFiles,
			Predicate<Pair<Function, FidHashQuad>> functionFilter, LanguageID languageId,
			List<LibraryRecord> linkLibraries, List<String> commonSymbols, TaskMonitor monitor)
			throws MemoryAccessException, VersionException, CancelledException,
			IllegalStateException, IOException {
```

The wrong message output by python is as below:

```python
TypeError: No matching overloads found for 
ghidra.feature.fid.service.FidService.createNewLibraryFromPrograms(ghidra.feature.fid.db.FidDB,
str, str, str, list, NoneType, ghidra.program.model.lang.LanguageID,
NoneType, list, ghidra.util.task.ConsoleTaskMonitor), 

options are:
public ghidra.feature.fid.service.FidPopulateResult 
ghidra.feature.fid.service.FidService.createNewLibraryFromPrograms(ghidra.feature.fid.db.FidDB,
java.lang.String, java.lang.String, java.lang.String, java.util.List, java.util.function.Predicate, ghidra.program.model.lang.LanguageID,
java.util.List, java.util.List, ghidra.util.task.TaskMonitor)
throws 
ghidra.program.model.mem.MemoryAccessException,ghidra.util.exception.VersionException,ghidra.util.exception.CancelledException,java.lang.IllegalStateException,java.io.IOException
```

The code I used to call the function 

```python 
# fidDb: ghidra.feature.fid.db.FidDB
# name: str 
# file: DomainFile 
# langID: ghidra.program.model.lang.LanguageID
result_ = service.createNewLibraryFromPrograms(fidDb, 
                name, "1.0", "", [file], None, langID, None, [], monitor)
```

The type error comes out, as we can see there are two parameters do not have same type:
- Parameter 8:  `NoneType vs java.util.List` one best practice of this function in ghidra give this parameter a `null`, so I think it's all right since jpype can change None to required type
- Parameter 6: `NoneType vs java.util.function.Predicate` similar with above 
- Parameter 10: `TasMonitor vs ConsolTaskMonitor`  this ConsoleTaskMonitor is a subclass of TaskMonitor, and I think it's not wrong because I have use the same parameter in other function which also takes a TaskMonitor as parameter 
- Other `List` parameter: I do not know if the type of the list element will make the type check fail, but I think their type is right
- Other: `java.util.String vs str' I think this could be done by jpype

If everyone could help me or give me some advice, I will fully appreciate it.

Best Regards, 
Dingisoul

**Comment by Thrameos** [comment]
That is a very complex call.   Your best bet would be to force casting on each argument and determine which casting operator failed.   

To use a cast apply the "@" operator.   

Ie.     java.lang.String@"hello"   would force the type of the argument to be java.lang.String rather than a Python string. 

My guess is some automatic conversion that you are assuming doesn't work.   It may be fixed by casting, or it may tell you the conversion is not possible.   But either way it should move you towards a solutions.

**Comment by dingiso** [comment]
Thanks, I have found the solution, jpype will not convert python list to java list in this situation, after I change the original `[file]` 
 to `java.util.ArrayList([file])` , it goes OK.
Best Regards,
Dingisoul
