### ISSUE TITLE
Silent failure of jpype.startJVM when classpath is passed

### ISSUE THREAD

**Issue by dawidkalwa** [jpype-project/jpype#1209]
When I tried this method of passing my jar file to classpath:

jpype.startJVM(classpath='informix-jdbc-complete-4.50.4.1.jar')

I have this output:
INFO - JDBC driver found at informix-jdbc-complete-4.50.4.1.jar
DEBUG - Initializing database connection...

and nothing else, simply silently exit from python and back to the shell prompt

then I tried this:

jpype.startJVM()
jpype.addClassPath('informix-jdbc-complete-4.50.4.1.jar')

output:
JDBC driver found at informix-jdbc-complete-4.50.4.1.jar
2024-08-08 12:27:52,725 - DEBUG - Initializing database connection...
2024-08-08 12:27:53,099 - INFO - JVM started successfully.
JVM Classpath: 

ERROR - An error occurred: java.lang.ClassNotFoundException: com.informix.jdbc.IfxDriver
Traceback (most recent call last):
  File "org.jpype.JPypeContext.java", line None, in org.jpype.JPypeContext.callMethod
Exception: Java Exception

I tried many different jars and absolute and relative path to this jar. I have no idea, why this library cannot read this jar. JVM Classpath: <- is empty

@https://github.com/jpype-project/jpype/issues/1126

**Comment by marscher** [comment]
the classpath has to be passed to startJVM. It is not possible to change it later on.
