### ISSUE TITLE
License not being recognized by git badge is preventing use of jpype within my company

### ISSUE THREAD

**Issue by clajo04** [jpype-project/jpype#1210]
My company will automatically approve pypi packages that use a pre-approved set of oss licenses - however, because jpype's license is not correctly identified by the git license badge, the automated system is preventing adoption of the latest versions of jpype.

**Comment by Thrameos** [comment]
Do ypu know how to fix this?  It was recognized before.

**Comment by clajo04** [comment]
Unfortunately, I don't - I've forked the repo and looked to see if I could figure it out but it is beyond my ken. 

My suspicion is the formatting of the license file - it appears to be in markdown, while others I've seen have just been plain text.

**Comment by Thrameos** [comment]
I guess we could just copy over a text version from a project that it is recognizing properly.   You can try by copying it into your fork and then pulling up the fork page on a browser.   If it recognizes that the markdown was the issue.  If not, I guess we will have to find some community posts.  I hope it isn’t looking through the repo and finding some file that isn’t marker properly or has a public domain notice that is causing the license tool to think there is a mixed license of some kind.

**Comment by clajo04** [comment]
I decided to give it a another go and I was able to determine that the issue is resolved if the current markdown (?) formatted LICENSE file is replaced with the ascii text available here: https://www.apache.org/licenses/LICENSE-2.0.txt (trimming off the instructional block at the end, although that wasn't strictly necessary).   I had previously tried to rename the LICENSE file to LICENSE.md but that didn't help.  

I did notice that the NOTICE file is in the same markdown format, although not indicated by the instruction block on the license file.  That file does not seem to have any effect on the output of the licensee program, which git uses to identify the license applied. 

I don't see a guide for contributors, and I'm pretty new at OSS contributions - if it's acceptable I could create a pull request for this change, or I am perfectly okay with someone more seasoned doing that, as long as it gets done.

**Comment by clajo04** [comment]
@Thrameos 

I've created a pull request (https://github.com/jpype-project/jpype/pull/1211) for this issue - I'm a little bit concerned, because when I made this change to my fork I still see a GitHub badge that doesn't correctly identify the license.  However, I noticed that the badge in the readme explicitly references this (jpype-project) repo rather than my fork, so my theory is that once the PR is merged, it should resolve correctly.    My creation of a PR kicked off a bunch of checks, which I must say I don't have the experience to interpret and/or correct. 

If there's more work I need to do to have my PR reviewed, please let me know.

**Comment by clajo04** [comment]
@Thrameos 

Okay- I updated the readme in my fork to refer to my version of the project.  The git license badge for my repo on that branch now updates correctly and shows the license to be Apache-2.0.  So I'm much more confident now that once the PR is merged, the badge will update appropriately.

**Comment by Thrameos** [comment]
Sounds good I will merge this in.
