### ISSUE TITLE
#1195 broke use of -Djava.system.class.loader

### ISSUE THREAD

**Issue by astrelsky** [jpype-project/jpype#1222]
The classpath cannot be set after the JVM has started when a system class loader has been specified or you will get a ClassNotFoundException.

Of course, `-Djava.class.path=` can be explicitly specified as well as the system classloader. It was just unexpected for it to not be finding the classloader when the classpath was specified.

**Comment by Thrameos** [comment]
I think I will need more to replicate this.

**Comment by astrelsky** [comment]
> I think I will need more to replicate this.

```py
jpype.startJVM(None, "-Djava.system.class.loader=org.MyClassLoader", classpath=["jar_containing_MyClassLoader"])
```
As of #1195 jpype will start the jvm with the provided arguments and then add to the classpath. This will result in an error when starting the JVM because it cannot find the specified class for the system class loader.

**Comment by Thrameos** [comment]
I believe we lost something in that PR as extra args got dropped from startJVM.  Will fix.
