### ISSUE TITLE
DeprecationWarning: jpype._core.isThreadAttachedToJVM is deprecated

### ISSUE THREAD

**Issue by liyangzbx** [jpype-project/jpype#1223]
DeprecationWarning: jpype._core.isThreadAttachedToJVM is deprecated, use java.lang.Thread.isAttached instead
  if not jpype.isThreadAttachedToJVM():

![image](https://github.com/user-attachments/assets/e4598695-fc28-4fdc-a1c6-511d2cac4d7a)

**Comment by Thrameos** [comment]
Yes the call is deprecated.  Contact the package that cslls it "jaydebeAPI".
