### ISSUE TITLE
Fix jpype.org

### ISSUE THREAD

**Issue by Thrameos** [jpype-project/jpype#1247]
Currently I am getting that it has an invalid certificate and thus blocked by my employer.

**Comment by astrelsky** [comment]
I get instantly redirected to the github project.

**Comment by marscher** [comment]
I think the domain and redirect was done by @originell back in the day.

**Comment by originell** [comment]
Yes it was! Oh noes!

**Comment by Thrameos** [comment]
I didn't get blocked this time, so I am guessing it is good.   It jumps through the redirect so quickly I can't stop it to check the certificate.

**Comment by marscher** [comment]
Thanks for the quick fix @originell
