### ISSUE TITLE
/usr/bin/ld: cannot find -ldl FreeBSD

### ISSUE THREAD

**Issue by minimatronik** [jpype-project/jpype#127]
Hello. Please help:
My system PC-BSD 10.1.1(FreeBSD with desktop), i try to install jpype via pip and "python setup.py install". Always get this error:
/usr/bin/ld: cannot find -ldl
c++: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'c++' failed with exit status 1
I try to set my enviroment "JAVA_HOME" in system, and in file setup.py:
# java_home = os.getenv('JAVA_HOME', '')

java_home = '/usr/local/openjdk7'

I install it in virtual env. I don't find any python-devel \ python-dev in FreeBSD ports.
That my full log:
[env] [minimatronik@minimatronik-localhost] ~/Documents/PROJECT/develop-eggs/JPype1-0.5.7% python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to JPype1.egg-info/requires.txt
writing JPype1.egg-info/PKG-INFO
writing top-level names to JPype1.egg-info/top_level.txt
writing dependency_links to JPype1.egg-info/dependency_links.txt
reading manifest file 'JPype1.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
no previously-included directories found matching 'test/classes'
writing manifest file 'JPype1.egg-info/SOURCES.txt'
installing library code to build/bdist.freebsd-10.1-RELEASE-p17-amd64/egg
running install_lib
running build_py
creating build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7
creating build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/_windows.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/_refdaemon.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/_jproxy.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/JClassUtil.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/_jexception.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/_jobject.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/_jclass.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/_linux.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/_pykeywords.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/nio.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/_darwin.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/_jvmfinder.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/reflect.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/_jarray.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/_jpackage.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/_gui.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/_core.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/_jcollection.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/_properties.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/__init__.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
copying jpype/_jwrapper.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype
creating build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype/awt
copying jpype/awt/__init__.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype/awt
creating build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype/awt/event
copying jpype/awt/event/**init**.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype/awt/event
copying jpype/awt/event/WindowAdapter.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpype/awt/event
creating build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpypex
copying jpypex/**init**.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpypex
creating build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpypex/swing
copying jpypex/swing/AbstractAction.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpypex/swing
copying jpypex/swing/pyutils.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpypex/swing
copying jpypex/swing/**init**.py -> build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/jpypex/swing
running build_ext
building '_jpype' extension
creating build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7
creating build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native
creating build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common
creating build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_platform_win32.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_platform_win32.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_objecttypes.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_objecttypes.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_typename.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_typename.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_arrayclass.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_arrayclass.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_platform_linux.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_platform_linux.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_class.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_class.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_methodoverload.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_methodoverload.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_field.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_field.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_javaenv_autogen.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_javaenv_autogen.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_classbase.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_classbase.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_method.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_method.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_array.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_array.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_javaenv.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_javaenv.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_jniutil.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_jniutil.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_env.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_env.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_invocationhandler.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_invocationhandler.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_voidtype.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_voidtype.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_proxy.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_proxy.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_monitor.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_monitor.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_object.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_object.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_primitivetypes_autogen.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_primitivetypes_autogen.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_primitivetypes.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_primitivetypes.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_referencequeue.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_referencequeue.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_typemanager.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_typemanager.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/common/jp_reference.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_reference.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/python/py_monitor.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/py_monitor.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/python/jpype_memory_view.c -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/jpype_memory_view.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/python/jpype_javaarray.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/jpype_javaarray.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/python/jpype_javaclass.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/jpype_javaclass.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/python/py_method.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/py_method.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/python/py_field.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/py_field.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/python/jpype_javanio.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/jpype_javanio.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/python/py_class.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/py_class.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/python/jpype_python.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/jpype_python.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/python/jpype_module.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/jpype_module.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/python/pythonenv.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/pythonenv.o -ggdb
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -Inative/common/include -Inative/python/include -I/usr/local/openjdk7/include -I/usr/local/openjdk7/include/linux -I/usr/local/include/python2.7 -c native/python/py_hostenv.cpp -o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/py_hostenv.o -ggdb
c++ -shared -pthread -Wl,-rpath,/usr/lib:/usr/local/lib -Wl,-rpath=/usr/lib:/usr/local/lib -fstack-protector build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_platform_win32.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_objecttypes.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_typename.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_arrayclass.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_platform_linux.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_class.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_methodoverload.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_field.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_javaenv_autogen.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_classbase.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_method.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_array.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_javaenv.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_jniutil.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_env.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_invocationhandler.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_voidtype.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_proxy.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_monitor.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_object.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_primitivetypes_autogen.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_primitivetypes.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_referencequeue.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_typemanager.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/common/jp_reference.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/py_monitor.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/jpype_memory_view.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/jpype_javaarray.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/jpype_javaclass.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/py_method.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/py_field.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/jpype_javanio.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/py_class.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/jpype_python.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/jpype_module.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/pythonenv.o build/temp.freebsd-10.1-RELEASE-p17-amd64-2.7/native/python/py_hostenv.o -L/usr/local/lib -ldl -lpython2.7 -o build/lib.freebsd-10.1-RELEASE-p17-amd64-2.7/_jpype.so
/usr/bin/ld: cannot find -ldl
c++: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'c++' failed with exit status 1
[env] [minimatronik@minimatronik-localhost] ~/Documents/PROJECT/develop-eggs/JPype1-0.5.7% 

P.S. the first time the installation was completed error, because file jni_md.h set in 
/usr/local/openjdk7/include/freebsd/jni_md.h
not in
/usr/local/openjdk7/include/jni_md.h,
so i moved it.

**Comment by marscher** [comment]
It looks like the detection for FreeBSD in setup does not work 
correctly, as libdl is not used

     if sys.platform.startswith('freebsd'):

so I suspect that this does not hold for your system. Can you please 
provide the output of sys.platform?

**Comment by minimatronik** [comment]
>>> import sys
>>> sys.platform
'freebsd10'
>>> 
right?

**Comment by minimatronik** [comment]
i add this in setup.py:
elif sys.platform.startswith('freebsd'): 
    platform_specific['libraries'] = ['dl']
    if found_jni:
        platform_specific['include_dirs'] += [os.path.join(java_home, 'include', 'freebsd')]

the same error

**Comment by minimatronik** [comment]
Sorry, all work!
I add this:
elif sys.platform.startswith('freebsd'): 
    #platform_specific['libraries'] = ['dl']
    if found_jni:
        platform_specific['include_dirs'] += [os.path.join(java_home, 'include', 'freebsd')]

And i find this in your code on github, so i downloaded not updated code via pypi:
https://pypi.python.org/pypi/JPype1
Thanks!

**Comment by marscher** [comment]
#128 fixes issue with jni_md.h
