### ISSUE TITLE
Compilation fails on OS X Yosemite (again?)

### ISSUE THREAD

**Issue by eriophora** [jpype-project/jpype#141]
Compilation fails with error: 

c++: error: x86_64: No such file or directory
c++: error: i386: No such file or directory
c++: error: unrecognized option '-arch'
c++: error: unrecognized option '-arch'
error: command 'c++' failed with exit status 1

I don't think I've ever compiled anything with Yosemite that wasn't a huge headache.

**Comment by marscher** [comment]
guess this is the output of a recent clang compiler? I think we've already got different compiler support in our setup.py, but it seems like it treats clang and gcc the same.

**Comment by mfouesneau** [comment]
Just compiled it. The main issue was to update to xcode 7.0 for proper library paths.

**Comment by kbabyk** [comment]
And for me it says:
/usr/include/sys/cdefs.h:680:2: error: Unsupported architecture
#error Unsupported architecture

Did somebody see such issue before?
