### ISSUE TITLE
pypy support

### ISSUE THREAD

**Issue by sils** [jpype-project/jpype#146]
Our continuous build reports that installing your package on pypy3 doesn't seem to work which is sad.

https://circleci.com/gh/coala-analyzer/coala/1610 , see node 3 which is pypy.

Known issue? Is this correctable?

**Comment by baztian** [comment]
I knew that before as I've also tried it out of curiosity. But it's a new issue on github. Thanks for reporting.

It should definitely be correctable. A good starting point for you should be https://bitbucket.org/pypy/compatibility/wiki/Home We could then add pypy to our travis ci build matrix.

**Comment by marscher** [comment]
It seems PyPy does not support memory views (or the c-api is different). 
Try to disable the Numpy feature explicitly and check if it works.

**Comment by baztian** [comment]
I've tried disabling Numpy without success.

    $ python setup.py --disable-numpy install
    ...
    setup.py:152: FeatureNotice: Turned OFF Numpy support for fast Java array access  FeatureNotice)
    building '_jpype' extension
    ...
    native/common/jp_primitivetypes_autogen.cpp:1317:46:   required from here
    native/common/jp_primitivetypes_autogen.cpp:64:77: error: ‘PyMemoryView_GetContiguous’ was not declared in this scope
         PyObject* memview = PyMemoryView_GetContiguous(sequence, PyBUF_READ, 'C');
                                                                                 ^
    native/common/jp_primitivetypes_autogen.cpp:76:54: error: ‘PyMemoryView_GET_BUFFER’ was not declared in this scope
      Py_buffer* py_buff = PyMemoryView_GET_BUFFER(memview);
                                                          ^
    error: command 'cc' failed with exit status 1

**Comment by marscher** [comment]
see #166

**Comment by Thrameos** [comment]
Currently fixed in devel.  The test don't pass because the memory clean up routines in PyPy are lazy rather than aggressive, but other than that all is working.
