### ISSUE TITLE
Failed run a method which use third-party jar

### ISSUE THREAD

**Issue by lianying526** [jpype-project/jpype#151]
Who can help me,thank you very much!
I create a class in my maven project on IntelliJ-IDEA IDE.
There are two method in the class ,one called sayhello which is just to print "hello",the other called function and used third-party jar

> package pushpackage;
> import a;
> import b;
> import b;
> import d;
> 
> public class PushClass {
>    public  void function() {
>        Sender sender = new Sender()
>        Message msg = new IOSMessage.IOSBuilder();
>        TParam tp = new TokenParam();
>        sender.sendWithT(tp, msg);
>    }
> 
>  public  void sayhello(){
>        System.out.print("hello");
>   }
> }

then I export a jar
In pyhton file，

> import jpype
> import os.path
> jarpath = os.path.join(os.path.abspath('.'), '/Project/myjava/')
> jpype.startJVM(jpype.getDefaultJVMPath(),"-ea","-Djava.class.path=%s"%(jarpath + 'HelloPush.jar'))
> PushJClass = jpype.JClass("pushpackage.PushClass")
> obj = PushJClass()
> obj.sayhello()
> obj.function()

when it run 

> obj.sayhello()

it succeed,but

> obj.function()

failed without error information. it started a new python progress but never stoped

**Comment by baztian** [comment]
How do you know that it failed if you don't get an error?

**Comment by baztian** [comment]
Are there any dependent jars required by HelloPush.jar? Is IOSMessage, Sender and so on in HelloPush.jar included?
