### ISSUE TITLE
App crashing in Win 7 on startJVM

### ISSUE THREAD

**Issue by EricE** [jpype-project/jpype#162]
My script runs without an error from the command line but when I run it after creating a single file executable with PyInstaller it crashes without generating an exception that I can catch (Win 7/64, Python 2.7.10/32):

```
jar = getattr(sys, '_MEIPASS', os.getcwd()) + os.sep + 'ojdbc6.jar'  # So PyInstaller knows where to find the jar file
args = '-Djava.class.path=%s' % jar

print 'jaydebeapi version = ' + jaydebeapi.__version__
print 'jpype version = ' + jpype.__version__
print args

jvm_path = jpype.getDefaultJVMPath()
print "JVM Path: " + jvm_path
try:
    jpype.startJVM(jvm_path, args)

except Exception, e:
    print e.message
    print e.args
    sys.exit()
```

In the command window I get:

```
jaydebeapi version = 0.2.0
jpype version = 0.6.0
-Djava.class.path=C:\Temp\_MEI141242\ojdbc6.jar
JVM Path: C:\Program Files (x86)\Java\jre7\bin\client\jvm.dll
```

At this point I immediately get a window "Agile test has stopped working"

I'm not a sw developer and I'm struggling to figure out how to debug this further, any suggestions?  I tried hard coding the jar path to point outside of the temp directory created by PyInstaller but it still failed.

This used to work with a previous version of jpype, pyinstaller and probably java in that the application would run (and query an Oracle database).

Edit:
I found that I have an older version of _jpype.pyd in the directory where I'm running the command line version.  This was left over with problems I was having with the older PyInstaller not finding it.  However, when I deleted the _jpype.pyd file, the command line version dies on the same startJVM line.  Put it back and the command line version runs...  I looked in the temp folder created by PyInstaller and it has the new version of _jpype.pyd.  Unfortunately I can't recover the version, last time I used it was around May of 2015.

Edit 2:
I went back to jpype 0.5.7 with no luck.  The _jpype.pyd file is a different size than the one that is working (working=340k), I found a 0.5.4 zipfile on my system, maybe it came from that install?  I've probably done a horrible thing but it works so...  I renamed the _jpype.pyd file in the JPype1-0.5.7-py2.7-win32.egg directory, moved the 340k one there and I'm now working both at the command line, IDE and my single file PyInstaller exe...  I tried installing 0.5.4 but I don't have the JDK anymore and I didn't want to potentially break anything by installing it.  I'm only doing queries to an Oracle database using their OJDBC6.jar file.

**Comment by Thrameos** [comment]
This thread is very out of date and likely not relevant to the current master.
