### ISSUE TITLE
Python str to byte array (using JArray) conversion seems broken in Python 2.6

### ISSUE THREAD

**Issue by DaWalker** [jpype-project/jpype#169]
In Python 2.6, converting a Python byte string (str) to a JArray of type JByte results in an array of 0x01 bytes instead of the original characters.

The length matches, but all the bytes are 0x01 instead of the chars from the original string.

Example:

```
>>> import jpype
>>> jpype.startJVM(jpype.getDefaultJVMPath())
>>> ByteArray = jpype.JArray(jpype.JByte)
>>> python_string = 'Hello world!'
>>> bytes = ByteArray(python_string)
>>> len(bytes) == len(python_string)
True
>>> str(bytes) == python_string
False
>>> str(bytes)
'\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01'
>>>
>>> # What we got:
>>> [b for b in bytes]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
>>>
>>> # What we expected:
>>> [ord(c) for c in python_string]
[72, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 33]
```

In the meantime, here is a workaround using intermediate array:

```
>>> import array
>>> python_array = array.array('b', python_string)
>>> str(python_array)
"array('b', [72, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 33])"
>>> bytes[:] = python_array
>>> len(bytes) == len(python_string) == len(python_array)
True
>>> str(bytes) == python_string == python_array.tostring()
True
>>> [b for b in bytes]
[72, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 33]
```

My version info:

```
$ pip show jpype1

---
Metadata-Version: 1.0
Name: JPype1
Version: 0.6.1
Summary: A Python to Java bridge.
Home-page: https://github.com/originell/jpype/
Author: Luis Nell
Author-email: cooperate@originell.org
License: License :: OSI Approved :: Apache Software License
Location: /usr/lib64/python2.6/site-packages
Requires:

$ python
Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

$ cat /proc/version
Linux version 2.6.32-504.el6.x86_64 (mockbuild@c6b9.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) ) #1 SMP Wed Oct 15 04:27:16 UTC 2014

$ java -version
java version "1.7.0_85"
OpenJDK Runtime Environment (rhel-2.6.1.3.el6_7-x86_64 u85-b01)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)
```

**Comment by DaWalker** [comment]
Testing with the other basic and built-in sequence types as input values to ByteArray reveals further problems:

 - 'hello' - BROKEN: all 0x01s
 - r'hello' - BROKEN: all 0x01s
 - b'hello' - BROKEN: all 0x01s
 - range(5) - OK
 - xrange(5) - OK
 - bytearray - BROKEN: traceback:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib64/python2.6/site-packages/jpype/_jarray.py", line 101, in _jarrayInit
        self, _jpype.newArray(self.__class__.__javaclass__, sz))
    TypeError: an integer is required

 - unicode('hello') - BROKEN: all 0x01s
 - ['h', 'e', 'l', 'l', 'o'] - OK
 - ('h', 'e', 'l', 'l', 'o') - OK
 - array('b', [104, 101, 108, 108, 111]) - BROKEN: same traceback as above

**Comment by DaWalker** [comment]
Additionally, creating a JArray(JByte) of appropriate size seems broken in many instances too. e.g.

    >>> ByteArray = jpype.JArray(jpype.JByte)
    >>> bytes = ByteArray(5)
    >>> bytes[:] = 'hello'
    >>> str(bytes)
    '\x01\x01\x01\x01\x01'

**Comment by marscher** [comment]
Thanks for the detailed report. Are you using the NumPy extension? If 
so, try disabling it to pin the origin of the bug.

**Comment by marscher** [comment]
Probably the data type is too large to fit the Python one.

**Comment by DaWalker** [comment]
Thanks for the quick response. Yes, I do have numpy installed. After uninstalling numpy, I get:

    ImportError: numpy.core.multiarray failed to import
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "dtsearch.py", line 35, in <module>
        import jpype as _jpype
      File "/usr/lib64/python2.6/site-packages/jpype/__init__.py", line 17, in <module>
        from ._jpackage import *
      File "/usr/lib64/python2.6/site-packages/jpype/_jpackage.py", line 18, in <module>
        import _jpype
    ImportError: numpy.core.multiarray failed to import

After a 'pip uninstall jpype1' / 'pip install jpype1', that traceback disappears, but I get the same behaviour as above:

e.g.
    >>> import dtsearch
    >>> import jpype
    >>> ByteArray = jpype.JArray(jpype.JByte)
    >>> ByteArray('hello')
    <jpype._jarray.byte[] object at 0x7f12b377bdd0>
    >>> str(_)
    '\x01\x01\x01\x01\x01'

**Comment by marscher** [comment]
you would then have to reinstall jpype, because it enables the extension 
during build time.

**Comment by DaWalker** [comment]
OK, but after reinstalling, I still get the same broken behaviour of all 0x01 bytes intead of the string's chars, without numpy.

**Comment by marscher** [comment]
Ok, thank you. This restricts the origin of this a bit.

**Comment by justussc** [comment]
i think the problem here is that for 2.7+ in JPByteType::setArrayRange we use `setViaBuffer<jbyteArray, jbyte>` while for 2.6 we fall back to getting each item individually with `PySequence_GetItem` and then convert it with `PyInt_AS_LONG`. for a `PyStringObject` it seems that `PySequence_GetItem` returns another `PyStringObject` and that one cannot be converted to long. as PyInt_AS_LONG doesn't include error checking we get this behaviour.

not sure what is the best way of fixing this. that there is no error checking whatsoever is anyway a problem. currently one can call this with a sequence of arbitrary objects and it would run through fine.

**Comment by DaWalker** [comment]
Iterating over a string should yield a sequence of strings, each being a single character from the original string. It would seem that the correct thing to do here would be to do some type checking, and convert byte strings of length 1 to their byte integer values similar to what builtin_ord() does, (e.g. PyBytes_Check(), length==1 check, then convert with (long)(unsigned char)*PyBytes_AS_STRING()/PyInt_FromLong() ). From a (very) brief look at the source, it looks like there is a conversion error handler already in place, but simply the wrong version of the function is being called (PyInt_AS_LONG, which does no checks, instead of PyInt_AsLong(), which does). I will try to get some time to take a look at the source over the next couple of weeks, see if I can fix this myself. Probably a generic PyObject-to-byte routine is needed that can support a few more basic types, and can be extended in the future.

**Comment by justussc** [comment]
there is already code that does this. i am not familiar enough with jpype to be sure why we have all these setRange, setArraySlice etc functions. but if we pass a string to a method that expects a `byte[]` we go through `JPArrayClass::convertToJava` which properly converts a PyStringObject using `PyBytes_AsStringAndSize`. for example the following works also w/ python 2.6:
```
        python_string = 'Hello world!'
        ByteArray = jpype.JArray(jpype.JByte)
        bytes = ByteArray(len(python_string))
        # call java.io.ByteArrayInputStream(byte[])
        stream = jpype.java.io.ByteArrayInputStream(python_string)
        stream.read(bytes, 0, len(python_string))
        print (str(bytes))
```
i don't know if we cannot use the same code path for construction of arrays because of the numpy optimizations? this is a bit inconsistent.

**Comment by Thrameos** [comment]
Support of Python 2 series has bee dropped.  Array conversions are improved.
