### ISSUE TITLE
Fix Crash in Multithread

### ISSUE THREAD

**Issue by originell** [jpype-project/jpype#18]
@tcalmant reported via mail that he found jpype crashing in multi-threading environments. I put this here because I think it's better to have it publicly in the bug tracker than in emails :)

> A fatal error has been detected by the Java Runtime Environment:
> 
>  SIGSEGV (0xb) at pc=0x000000010007168a, pid=828, tid=40963
> 
> JRE version: OpenJDK Runtime Environment (7.0-b01) (build 1.7.0-u40-unofficial-b1)
> Java VM: OpenJDK 64-Bit Server VM (24.0-b50 mixed mode bsd-amd64 compressed oops)
> Problematic frame:
> C  [Python+0x6e68a]  subtype_dealloc+0xda
> 
> Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
> 
> If you would like to submit a bug report, please include
> instructions on how to reproduce the bug and visit:
>   http://icedtea.classpath.org/bugzilla
> The crash happened outside the Java Virtual Machine in native code.
> See problematic frame for where to report the bug.

He fixed it in [one of his commits](https://github.com/tcalmant/jpype-py3/commit/9f5599262ccc353edf112ce54ff169e7ffc06009)

Now we only need to test this with the changes from #17. Sadly I can't reproduce the error myself as it seems. So help is appreciated! :)

**Comment by zhihuizheng** [comment]
I met a similar problem, and it shows that
A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f48ea89d83b, pid=12678, tid=139951138658048
#
# JRE version: Java(TM) SE Runtime Environment (7.0_40-b43) (build 1.7.0_40-b43)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.0-b56 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libpthread.so.0+0x683b]  __pthread_init_static_tls+0x5b
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

I try code 
```if not jpype.isThreadAttachedToJVM():
        jpype.attachThreadToJVM()
but it doesn't work.

What's the problem really is?
