### ISSUE TITLE
No matching overloads found Java methods with boolean

### ISSUE THREAD

**Issue by arthurtalkgoal** [jpype-project/jpype#186]
Hi 

I got **_No matching overloads found**_ for my boolean args:

```
IDependencyParser enableDeprelTranslator(boolean enable);
```

from the call:

```
MyParser.enableDeprelTranslator(java.lang.Boolean(0));

> RuntimeError: No matching overloads found. at native/common/jp_method.cpp:121

```

The other variable types has no such problem.

**Comment by justussc** [comment]
you should be able to pass it exactly as to java.lang.Boolean(boolean). jpype does not do automatic unboxing.

    MyParser.enableDeprelTranslator(False)

**Comment by arthurtalkgoal** [comment]
Hi @justussc ,

I tried ***MyParser.enableDeprelTranslator(False)*** and different ways but no succeed. it's strang:

```
MyParser.enableDeprelTranslator(False);
RuntimeError: No matching overloads found. at native/common/jp_method.cpp:121

boolean=False
MyParser.MyenableDeprelTranslator( java.lang.Boolean(boolean));
RuntimeError: No matching overloads found. at native/common/jp_method.cpp:121
```
Please forgive me if my question does not make sense 

Thanks a lot

**Comment by justussc** [comment]
is `MyParser` an instance of your parser class? i have no problem calling methods with a single boolean parameter. one thing you could look at is the output of `MyParser.enableDeprelTranslator.matchReport()` and to make sure that `MyParser.enableDeprelTranslator` is indeed a `JavaBoundMethod`.

**Comment by tryingfox** [comment]
Maybe you should init MyParser, try this:

> MyParser().enableDeprelTranslator(False);

**Comment by Thrameos** [comment]
Boxed types are now derived from python primitives.  Thus although it does not unbox directly, it will use duck typing to get the correct value.  Thus this is fixed in master.
