### ISSUE TITLE
numpy ndarray --> byte array --> java method taking byte[]

### ISSUE THREAD

**Issue by toloudis** [jpype-project/jpype#188]
Sorry for asking for support here, but I am having trouble with setting up a byte array to pass to a Java method.  This is on Mac OSX 10.11.6, python 2.7.10, java 1.8.0_102.  I have tried both a fresh build of jpype, and also the PyPi install.

I am starting with a numpy array of arbitrary data type. I need to get it into a byte array to pass to java as a binary blob, essentially.  I want to do something like this:

```
buf = np.frombuffer(np.ascontiguousarray(mynumpyarray, mynumpydtype).data, np.uint8)
jbytearr = jpype.JArray(jpype.JByte)(buf.data) # or buf.tolist()  or buf ????
myjavaclass.SendByteArray(jbytearr)

```

I do not have control over the myjavaclass interface, so I am assuming it is correct for now and I know it takes byte[].

When I run this code, my python script freezes and the java icon pops up in the mac dock until i kill the python script.

**Comment by justussc** [comment]
is it possible that your java class is trying to do something with swing? i ran into a similar behaviour just recently (and it was a mac only problem, it blocket on loading the awt.dylib ). there is some way out using `jpype.setupGuiEnvironment` but that will block your mainthread.

**Comment by marscher** [comment]
I think you would have to allocate the JArray with a proper size first, before passing the buffer.

**Comment by Thrameos** [comment]
Works for me in 0.7.
``` 
import jpype
import numpy as np
jpype.startJVM()
mynumpyarray =np.array([1,2,3,4])
mynumpydtype = np.int32
buf = np.frombuffer(np.ascontiguousarray(mynumpyarray, mynumpydtype).data, np.uint8)
jbytearr = jpype.JArray(jpype.JByte)(buf.data) # or buf.tolist()
print(len(jbytearr))
print(jbytearr[:])

```
