### ISSUE TITLE
intermittent crashes of JVM on startup (Debian Linux with Python 3.5.1)

### ISSUE THREAD

**Issue by jhidding** [jpype-project/jpype#190]
Hi,

I'm not sure what's happening. Sometimes when I start a Python script that uses JPype, the JVM immediatly crashes with the following message:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f2dad336a76, pid=15323, tid=0x00007f2d01c7d700
#
# JRE version: OpenJDK Runtime Environment (8.0_102-b14) (build 1.8.0_102-8u102-b14.1-2-b14)
# Java VM: OpenJDK 64-Bit Server VM (25.102-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [_jpype.cpython-35m-x86_64-linux-gnu.so+0x5ea76] JPMethod::findOverload(std::vector<HostRef*, std::allocator<HostRef*> >&, bool)+0x76
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /mnt/Knolselderij/johannes/Code/noodles/hs_err_pid15323.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```

I can give the error-file if that helps.

**Comment by marscher** [comment]
sometimes? So not every time? It crashes during finding an overload of a method, which it shouldn't so details would be needed to fix this.

**Comment by jhidding** [comment]
Details:
I'm using JPype in [pyxenon] (http://github.com/nlesc/pyxenon), which wraps [Xenon] (http://github.com/nlesc/Xenon), a front-end for cluster computing schedulers like Slurm. This is happening in a multi-threaded environment (which could explain the irregular behaviour). I've only seen this particular crash running Nosetests on the [Noodles project](http://github.com/nlesc/noodles). Here's the log-file.
[hs_err_pid29754.zip](https://github.com/originell/jpype/files/541145/hs_err_pid29754.zip)

**Comment by marscher** [comment]
Did you bind jpype to the current Python thread?

**Comment by kewywwq** [comment]
I also get the same error on Centos 7.3 with python2.7.
Are this issue fixed now?

**Comment by Thrameos** [comment]
I am going to assume this problem is corrected.  Release 0.7 contains proper support for threading which was missing in 0.6 series.
