### ISSUE TITLE
No matching overloads found for java.o.File

### ISSUE THREAD

**Issue by sanketdiwale** [jpype-project/jpype#191]
Hi all,

I have a few classes defined in java all packaged into a jar file.
For the purposes of simplicity lets say the classes are called classA and classB.

classA has a method "public classB load(java.o.File file)", i.e. it has a public method that takes a java.io.File object and returns an object of type classB.

I have the started the JVM with class path set to point to the jar file and am able to call methods from the classes defined in the jar.
However when I try to call method load(...) described above from classA, I get a runtime error saying:
"RuntimeError: No matching overloads found. at native/common/jp_method.cpp:121"

The method is valid and runs when used directly from java. In python2.7, I can observe the matchReport() output for the "load" method and it gives an output:

'Match report for method load, has 1 overloads.\n  Lnet/sf/project/classB; (Ljava/io/File;) ==> NONE\n'

Does anyone know what I might be doing wrong. I am using the v0.6.1 of jpype with python2.7 on Mac OSx Yosemite (10.10.5).

Best,
Sanket

**Comment by marscher** [comment]
I dont think java.io.File is wrapped by an Python equivalent. Maybe create a wrapper method which accepts a String and create the file within the method?

**Comment by sanketdiwale** [comment]
Thanks @marscher , I tried that. I changed by method to accept a string of type java.lang.String  and changed the return value of the function to void just to check where the problem maybe lying (ideally I need to return the custom class classB mentioned before). So now the method interface looks like 
"void load(String name) { ... }".

If I call the method from python now as : load("xyz").
I still get the same error as before saying, "RuntimeError: No matching overloads found. at native/common/jp_method.cpp:121"

I  also tried passing the string argument as load('xyz') or load(JString('xyz')), but I keep getting the same error. Is there a specific way in which the string argument must be passed?

Best,
Sanket

**Comment by marscher** [comment]
mhm, actually str should be autoboxed in java.lang.String and vice versa... Maybe you should make you method public? ;)

**Comment by sanketdiwale** [comment]
Unfortunately it is already a public method.

Which is why I am dumbfounded.

Best,
Sanket

**Comment by Thrameos** [comment]
This behavior has not been seen in a while.  With the current API both File and Path seem to work properly.  We will be adding an enhancement to convert an `os.path` to `java.io.File` and `java.nio.file.Path` automatically.  

I am closing this request for now.
