### ISSUE TITLE
Testcode as Documentation

### ISSUE THREAD

**Issue by originell** [jpype-project/jpype#20]
As suggested in #18 by @tcalmant:

> Maybe we should open an issue on both our forks, in order to prepare a small set of test scripts in Python 2 and 3, in order ensure compatibility and detect this kind of derivation.
> It could also be used as sample code for users of jPype.

**Comment by Thrameos** [comment]
With auto attachment of threads this one has been corrected.  Thus sadly our oldest issue must now be closed.
