### ISSUE TITLE
Auto attachThreadToJVM

### ISSUE THREAD

**Issue by baztian** [jpype-project/jpype#203]
Why do I have to call attachThreadToJVM explicitly? Would it make sense to delegate this to jpype doing it automatically? Or are there any cases where I don't want to attach a thread?

Or is it a performance issue to always attach the thread? Maybe there's a lightweight way to check that could be used by jpype to make the decision?

**Comment by mikea1729** [comment]
This seems to be necessary, or at least it's one way to stop NULL pointer deref crashing... See #217

**Comment by marscher** [comment]
Actually one has to take care to detach the currently attached thread, otherwise one will cause memory leaks https://stackoverflow.com/questions/26534304/android-jni-call-attachcurrentthread-without-detachcurrentthread#26534926

**Comment by Thrameos** [comment]
This is currently implemented in master.
