### ISSUE TITLE
Windows binaries without anaconda

### ISSUE THREAD

**Issue by baztian** [jpype-project/jpype#204]
It would be nice to build and publish binaries for windows not requiring anaconda. It distracts some users to have to install anaconda and complicates installation process if you are not using anaconda.

**Comment by marscher** [comment]
agreed. Please go ahead and create them on Appveyor (deploying via twine to Pypi) - I don't have the time at the moment.

**Comment by marscher** [comment]
@baztian Could you create encrypted Appveyor credentials to publish the wheels on PyPI?

**Comment by Thrameos** [comment]
Currently building the binaries for 64 bit.
