### ISSUE TITLE
Not converting adding primitive type int to collections properly

### ISSUE THREAD

**Issue by edchu** [jpype-project/jpype#208]
Hello -
I was hoping you would be able to help pinpoint where the type conversion goes wrong.  Please see this short example:
`arrayList = JClass('java.util.ArrayList')()`
`arrayList.add(123)`
`arrayList.iterator().next()`

The output of the call to `arraylist.iterator().next()` shows the returned object is type Long.  I would expect that it would be type Integer. 

The same code in prior versions of Jpype it returned type Integer.

Modifying the example to `arrayList.add(123l)` and `arrayList.add(123.0)` return Long and Double respectively as expected.

Any help would be much appreciated
Thank you

**Comment by marscher** [comment]
sorry for the late reply. Do you have numpy installed, when running this example?

**Comment by Thrameos** [comment]
This behavior is correct.  Python ints are equal to java longs in Python3 and thus need to be made into java Long when placed on a generic object.  The behavior is currently different for Python2 where both int and long exist.  

In general you should specify the type of object when converting a python primitive to a java object by using the appropriate wrapper type.

```
arrayList.add(jpype.JInt(123))
```
