### ISSUE TITLE
Jpype on Windows 2016 Server

### ISSUE THREAD

**Issue by loehndorf** [jpype-project/jpype#221]
I currently run a couple of tests with Jpype under different versions of Windows. While Jpype works fine on Windows 2012 Server, I cannot start the JVM through Jpype on Windows Server 2016. In both cases, I cloned the git repo and built it from source. JAVA_HOME points to the correct path.
Does anyone have a clue what could have possibly gone wrong?

System setup:
- Windows 2016 Server 64-bit
- JRE 1.8 64-bit
- Visual C++ Built Tools
- Anaconda 64-bit w/ Python 3.6

<img width="1134" alt="screen shot 2017-06-03 at 24 31 01" src="https://cloud.githubusercontent.com/assets/1458662/26747110/fa69a248-47f3-11e7-962d-2e2752674f0c.png">

**Comment by marscher** [comment]
I think you are the first one to test jpype on this OS. Sad it does not work. Can you really confirm the dll is really existent in the given path from get_default_jvm?

**Comment by loehndorf** [comment]
I found a workaround. You simply need to add “C:\Program Files\Java\[JRE PATH]\bin” to the environmental (system) variable “Path”. This was not necessary before.

**Comment by loehndorf** [comment]
To answer your question: Yes, it is in there.

**Comment by Thrameos** [comment]
I wonder should it be our policy to automatically add ``$JAVA_HOME\bin`` to the env variable prior to launching the JVM.  We can remove it after JVM is started.  It may help solve this type of problem.  Unfortunately I can't test the solution.

If we should consider just moving this to our documentation page and closing this ticket.
