### ISSUE TITLE
Pytest conversion

### ISSUE THREAD

**Issue by Thrameos** [jpype-project/jpype#236]
I tried running pytest in place of nosetests.  The conversion is fairly minimal for the cygwin branch.  I was able to get all tests to run and produce a similar output with...

```bash
python -m pytest -v --junitxml=nosetests.xml test/jpypetest/__init__.py
```
I will wait until the pull requests are in so that I can rebase properly before converting.  There are a lot of addition tests in the test directory.  Most appear to be python2 or inoperable.  What is the plan for those?

**Comment by marscher** [comment]
👍 those are mostly old stubs, move them to _legacy_stubs or something if you don't mind.

**Comment by Thrameos** [comment]
Will do when I play with the appveyor and travis patterns.

**Comment by Thrameos** [comment]
Hmm, this one seems to have fallen of my radar.  Perhaps I should make another run at it for release 0.7
