### ISSUE TITLE
startJVM() crashes in windows 10, Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by mansoorfayyaz** [jpype-project/jpype#239]
My python crashes while running a simple jpype program. Im running jpype using python 3.6, 32bit with a 32bit jre on windows 10. When I run the following code, python crashes when running from command line. When I debug it in pyCharm CE, it gives the following error at startJVM()

Process finished with exit code -1073741819 (0xC0000005)

Any solutions or suggestions?
Thanks

```
from jpype import *
startJVM('C:\\Program Files (x86)\\Java\\jre1.8.0_131\\bin\\client\\jvm.dll', "-ea")
java.lang.System.out.println("hello world")
shutdownJVM()
```

**Comment by Thrameos** [comment]
It looks a lot like the error that one gets when mixing 32bit and 64bit environments.   Please verify that the python3.6 is 32bit in PyCharm.   After that next step would be to try to capture the failure point with a debugger.  Without the entry point it will be hard to trace down.

**Comment by NamsooCho** [comment]
I has same problem.
I am running Ubuntu 16.04(64bit), OpenJDK8(64bit), Python3.5(64bit), Jpype(rebuilded).
My system had worked well.
It didn't work suddenly yesterday, without any change except Ubuntu update.

**Comment by hurcy** [comment]
I have same problem.
Ubuntu 16.04(64bit), OracleJDK8(64bit), Python2.7, 3.5(64bit)
This problem started couple of days before. Compiled jpype in my environment makes same problem.

**Comment by Thrameos** [comment]
Hmm.  Perhaps on of the recent patches has introduced a bug.  Unfortunately, I can't replicate this bug.  If someone could be so kind as pulling the git at "07845b026af01b70f08cab54cea51068e7fe714d" and confirm if it is a recent change or something earlier.  I will try to get a virtual machine to replication the problem.

**Comment by Thrameos** [comment]
Please use "ulimit -c unlimited", then run gdb on the core.  I believe that ubuntu linux-image-4.10.0 has a bug that is preventing multiple JDKs from starting properly.

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1699772

**Comment by Thrameos** [comment]
More on the issue.

https://stackoverflow.com/questions/44719488/segmentation-fault-when-starting-jvm-using-jpype
