### ISSUE TITLE
getClass can fail because of java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by michi88** [jpype-project/jpype#240]
This is issue is mainly here for future googlers.

getClass can silently fail with the underlying error `java.lang.UnsupportedClassVersionError` although it will only throw `java.lang.RuntimeException: Class xxx not found`.

To actually see the error you need to turn on tracing (taken from [here](https://sourceforge.net/p/jpype/support-requests/5/)):
- uncomment line 23 in file src/native/common/include/jpype.h
- python setup.py build -f
- python setup.py install -f

The problem in my case was that I was compiling using java 1.8 but jpype found an old java 1.6 from the `/urs/bin/java` binary as I didn't set the `JAVA_HOME` environment variable.

It would probably save people a lot of time if we could actually expose the `java.lang.UnsupportedClassVersionError` thrown without the tracing enabled.

see: https://sourceforge.net/p/jpype/support-requests/5/
handy tool for different java versions: http://www.jenv.be/

**Comment by Thrameos** [comment]
This defect has been addressed by #550
