### ISSUE TITLE
Some trouble with MacOS and running a GUI

### ISSUE THREAD

**Issue by akmaier** [jpype-project/jpype#256]
Dear all,

we are able to run some GUI using jpype using the setupGuiEnvironment() functions. On Windows and linux systems we have very nice interprocess communication. However on MacOS, we have some trouble. As discussed in several internet posts, we are only able to do this from the main thread. The main thread then gets stuck in the run loop and we are not able to execute any other python code anymore. Probably our GUI also lacks some callbacks, etc.

Do you guys have any hints on how to deal with this issue?

The GUI is essentially ja JFrame...

Best,

Andreas

This Is our code:
``` python
from jpype import  *
import time

def run():
    print ('Thread started')
    try:
        print (repr(java.awt.Frame))
        gui = JPackage("edu").stanford.rsl.apps.gui
        gui.ReconstructionPipelineFrame.main(JArray(JString)(''))
    except JException as ex:
        print (ex)
    print ('Thread ended')
    
startJVM(getDefaultJVMPath(), "-Djava.class.path=conrad_1.0.6.jar", "-Xmx8G", "-Xmn7G")
java.lang.System.out.println("Starting CONRAD GUI");
setupGuiEnvironment(run)
java.lang.System.out.println("Started CONRAD GUI");
shutdownJVM()
```

**Comment by marscher** [comment]
you need to switch threads with Jpype: https://jpype.readthedocs.io/en/latest/userguide.html#threading

**Comment by akmaier** [comment]
I have a new version. Now "Thread ended" is displayed. However "Started CONRAD GUI" does not appear...

`from jpype import  *
import time

def run():
    print ('Thread started')
    try:
        attachThreadToJVM()
        print (repr(java.awt.Frame))
        gui = JPackage("edu").stanford.rsl.apps.gui
        gui.ReconstructionPipelineFrame.main(JArray(JString)(''))
        time.sleep(10)
        shutdownGuiEnvironment()
        detachThreadFromJVM()

    except JException as ex:
        print (ex)
    print ('Thread ended')
    

startJVM(getDefaultJVMPath(), "-Djava.class.path=/Users/maier/Desktop/conrad_1.0.6.jar", "-Xmx8G", "-Xmn7G")

java.lang.System.out.println("Starting CONRAD GUI");

setupGuiEnvironment(run)

java.lang.System.out.println("Started CONRAD GUI");

shutdownJVM()`

**Comment by akmaier** [comment]
This. version also produces an interesting error:
´´´ python
from jpype import  *
import time
import threading

def run():
    print ('Thread started')
    try:
        attachThreadToJVM()
        print (repr(java.awt.Frame))
        gui = JPackage("edu").stanford.rsl.apps.gui
        gui.ReconstructionPipelineFrame.main(JArray(JString)(''))
        time.sleep(10)
        shutdownGuiEnvironment()
        detachThreadFromJVM()

    except JException as ex:
        print (ex)
    print ('Thread ended')

def gui():
    attachThreadToJVM()
    setupGuiEnvironment(run)

startJVM(getDefaultJVMPath(), "-Djava.class.path=/Users/maier/Desktop/conrad_1.0.6.jar", "-Xmx8G", "-Xmn7G")

java.lang.System.out.println("Starting CONRAD GUI");

thread = threading.Thread(target=gui);
thread.start()
java.lang.System.out.println("Started CONRAD GUI");
shutdownJVM()
´´´

The error is:
´´´
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/maier/Documents/laptop siemens/repos/java_workspace/PyCONRAD/examples/start_conrad.py", line 22, in gui
    setupGuiEnvironment(run)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jpype/_gui.py", line 29, in setupGuiEnvironment
    AppHelper.runConsoleEventLoop()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyObjCTools/AppHelper.py", line 241, in runConsoleEventLoop
    nextfire = nextfire.earlierDate_(soon)
AttributeError: 'NoneType' object has no attribute 'earlierDate_'
´´

**Comment by matrixx567** [comment]
Hy,

I think, I had the same problem using Jpype in a multithreaded Java application.
You can try my fix from pull request #244.

Greets Martin

**Comment by akmaier** [comment]
The problem occurs only on MacOS. On Windows and Linux the code executes nicely....

**Comment by marscher** [comment]
On 23.08.2017 00:50, akmaier wrote:
> The problem occurs only on MacOS. On Windows and Linux the code executes nicely....
> 
that's sad, unfortunately I don't have access to OSX (only headless), so 
you would have to debug this yourself.

**Comment by Thrameos** [comment]
Closing this thread for now due to lack of activity.
