### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by runhwguo** [jpype-project/jpype#258]
when run java program over, return to python, once use input(), it will lead to 'OSError: [Errno 9] Bad file descriptor'

Traceback (most recent call last):
  File "/Users/runhwguo/PycharmProjects/Test/auto_script.py", line 248, in <module>
    menuNo = input()
OSError: [Errno 9] Bad file descriptor

Python3.6
Jpype 0.6.2

**Comment by marscher** [comment]
thanks for your report. Could you please provide a script reproducing the error?

**Comment by Thrameos** [comment]
Closed as out of date and unable to replicate.
