### ISSUE TITLE
Documentation lacks code samples and information about collections mapping

### ISSUE THREAD

**Issue by afayes** [jpype-project/jpype#262]
Documentation lacks code samples and information about collections mapping.

```
ls = java.util.ArrayList()
ls.add(1)
# cannot use python list methods e.g. ls.append(2)
print ls[0] # can use indexing to access element like python list - interesting - doc does not mention this
```

```
mp = java.util.HashMap()
mp.put("key", 1)
mp["key2"] = 2 # can set value through index - interesting - doc does not mention this
print c["key2"] # can access value through index - interesting - doc does not mention this
```

I am sure there are more interesting details that I do not know and is neither mentioned in the docs

**Comment by marscher** [comment]
I'd be happy to merge a PR for this :)

**Comment by afayes** [comment]
I read the documentation from here: http://jpype.readthedocs.io/en/latest/
which is the link on READ.me

There appears to be some documentation here: https://github.com/originell/jpype/tree/master/doc
although it looks like source files to build documentation - looks like a work in progress

**Comment by afayes** [comment]
I used Py4J and their documentation has lots of code samples and information about collections support and mapping: https://www.py4j.org/contents.html

**Comment by Thrameos** [comment]
Collections documentation has been improved in the next release, though there is not much to say on the topic.   Currently JPype has wrapped collections such as Map, List, Iterable, and Set to the corresponding type in Python.   Converting is as simple to call the Python or Java type as a copy constructor.   Thus we should not require as detailed documentation as py4j.

```
     l1 = ['a','b','c']
     l2 = JClass('java.util.ArrayList')(l1)
     l3 = list(l2)
```
