### ISSUE TITLE
Move to Organization

### ISSUE THREAD

**Issue by originell** [jpype-project/jpype#307]
As requested by @marscher, I am going to move this repository to it's own organization, so we can have proper team management. Nice to see something grow to this size.

The initial request happened in #304. I am opening this issue so we don't spam the other conversation full of details when it comes to this.

Moving the repository should be easy, as github stores a redirect. However, I am still investigating all the effects this will have.

Bigger Subtasks:

- [x] PyPi Account Accesses for trusted people
- [ ] Setting up the right account types at the necessary CI services
- [x] Check ReadTheDocs Account Access

Please add any other tasks you find missing @marscher. I am hoping to be able to do this sometime this weekend.

**Comment by marscher** [comment]
We should also add conda-forge maintainers to https://github.com/conda-forge/jpype1-feedstock/ to be able to merge new versions. There is nothing more I can think of at the moment. Thanks for your time setting this up @originell! 
The side-effects will be that CI services/readthedocs will also have to be moved to the new address, but maybe there is some kind of automatism to handle the move. We will see after the move what will need extra maintenance.

**Comment by Thrameos** [comment]
@originell any action on this issue?  I know marscher is currently busy, but I am not sure where this request is currently.

**Comment by originell** [comment]
@Thrameos great timing. Work is a bit slow these days, so I'm sure I will find some time to make this happe :) was pretty busy until a week ago

**Comment by Thrameos** [comment]
Anything you need from me?

**Comment by originell** [comment]
Nope, I think I should be fine. Will simply add all you guys to the orga.

Then we should move the project. But I'll write here when we are at that point :)

**Comment by originell** [comment]
@Thrameos how do you feel about `jpype-python` as name for the organization (marscher proposed it)? `jpype` is already taken, sadly.

**Comment by marscher** [comment]
@jpype Mr. Pyper would you mind appending the R of your name to your username for the sake of this project? :)

**Comment by Thrameos** [comment]
I am fine with `jpype-python` or `org.jpype` or `jpype-project`.  I personally like following the java convention on package names and putting a TLD, but I realize I am in very small minority in the java world.  Besides not sure if dot is allowed in the name on github.  

I am guessing that the organization name shares the same space as the user names, thus Justin Pyper is our conflict because John Pyper already had the R.  Though not sure you are likely to get a response from Justin given he made just two commits in 2015.

**Comment by originell** [comment]
@marscher @Thrameos you should've received invites to our organization by now. 

I am not sure if we should transfer the repo over or if we should simply create a new one and push as new origin.

Pros for a new repo:

- Fresh Start
- old issues cleaned

Cons for a new repo:

- Pull Requests need to be sent somewhere else
- Issues are gone
- Redirect will be done manually (empty repo, only readme with link to new repo)

In either case we will need to update all CI configs (and other tools).

I don't have that much overview right now. I will do whatever you two decide is best. Personally, I'm more of a "fresh start" person

**Comment by originell** [comment]
BTW if you agree to this.. I would love to:

- Sponsor a domain (jpype.com or jpype.org, whatever you prefer)
- I'm sure I could get a colleague of mine to make us a logo

Let's put this baby on more professional feet ;-)

**Comment by marscher** [comment]
Thank you for setting this up. I vote for transferring the repository,
because I do not want to loose anything.

The website and logo stuff is awesome!

**Comment by Thrameos** [comment]
Great work originell.  I will join once I can set up two phase authentication.    Yes, we should transfer the history.  I am all for jpype.org.  My employer lacks a enough common sense such that my participation in .com even if it were just a name that I recommend using org.  

We can decide later whether to copy the development project/issues in my repo copy into main project.

**Comment by originell** [comment]
@Thrameos I would wait with repo transfer until you have organization access. So we can be sure everything is in the clear. When will you be able to add 2FA?

I just bought `jpype.org` and enabled a redirect to this repo for now :)

**Comment by Thrameos** [comment]
Sorry I should have done it this weekend.  I will try again tonight to sign up for 2FA.

**Comment by Thrameos** [comment]
Okay I should now be in the project.

**Comment by originell** [comment]
Amazing! Thanks :) 

I will start the transfer tomorrow, because that's when I am in front of the computer the entire day – in case something goes awry

**Comment by marscher** [comment]
On 17.07.2018 08:52, Luis Nell wrote:
> Amazing! Thanks :) 
> 
> I will start the transfer tomorrow, because that's when I am in front of the computer the entire day – in case something goes awry
> 
Do not worry, so far every repo transfer I have performed went smoothly.
The only hassle will be setting up CI again. Luckily most of the
configurations are self consistent within the files.

**Comment by originell** [comment]
transfer complete :) I will leave the CI stuff up to you guys. I hope it works with the orga permissions.

Other things:

- who needs pypi access? 
- who needs readthedocs access?

I already contacted my design colleague for a logo. might take a while, but we will get something. I was thinking in the direction of bridges or peace-pipes. Any other input is very welcome!

**Comment by marscher** [comment]
I would like to have access to both services. Thanks!

**Comment by originell** [comment]
@marscher you already have owner access for quite some time now ;-) (https://pypi.org/manage/project/jpype1/collaboration/ and https://readthedocs.org/dashboard/jpype/users/)

**Comment by marscher** [comment]
ah sure, I got this wrong :)

**Comment by originell** [comment]
if that's it I think we can close this issue?

**Comment by Thrameos** [comment]
I think the rest is on marscher with regard to the CI.   Though it would be nice it I had privilege to close requests, assign tasks and manage git project milestones and such.  But I will leave that to the current maintainer to grant.

**Comment by marscher** [comment]
I'd suggest to give @Thrameos this permission! He has done outstanding work for this project in the past. Are you ok with that @originell?

Travis should have asked @originell for permission, as I requested it before being part of the organization (sorry). For Appveyor I changed the repo URL, which should be sufficient. RTD is fixed too.

**Comment by marscher** [comment]
@originell it seems like you need to approve Travis CI. I can not, because I send the request prior being a member.

**Comment by originell** [comment]
I'm perfectly fine with that! Saw the tons of amazing work! 👏 @Thrameos 

@marscher Just found the email via search. Approved it!

**Comment by marscher** [comment]
Thanks, although I have permissions on the organization, I still lack the permission on this repo to enable CI.

**Comment by originell** [comment]
@marscher but shouldn't you be able to give yourself the rights then O.o? Does it work now?

guys, behold.. here's a first quick sketch for a logo.

![jpype-logo](https://user-images.githubusercontent.com/23529/43145093-d41cf74e-8f5e-11e8-934f-461eb848db17.jpg)

Colors are the java red and the python blue :)

**Comment by marscher** [comment]
The logo looks great. I'm just a bit confused about the "extra" J (Python's logo is two color namely blue and yellow, shall we include these as well?). I was also think about something like a Snake drinking a Java coffee :) but I guess this is too sketchy - unserious?!

I can not access the organisation settings nor the repo settings - or blind...

**Comment by Thrameos** [comment]
So you are thinking more like this?

![image](https://user-images.githubusercontent.com/29045329/43159519-68cc4142-8f37-11e8-8f61-9ad6e8ba9ef3.png)

**Comment by marscher** [comment]
On 24.07.2018 20:48, Karl Nelson wrote:
> So you are thinking more like this?
exactly ;)
> 
> ![image](https://user-images.githubusercontent.com/29045329/43159519-68cc4142-8f37-11e8-8f61-9ad6e8ba9ef3.png)
> 
>

**Comment by originell** [comment]
@marscher wait I'll check the permissions.

ad logo: sounds nice. I also like the illustration idea. Though I'm not sure my colleague can do such things :D The thing with the J-jpype makes sense.

**Comment by originell** [comment]
@marscher @Thrameos ahh it appears that I still had to make you guys owners of the organization. you should now have all the permissions. huuuuuuge responsibilities!!

**Comment by Thrameos** [comment]
Okay I used my new found power to chop the issue back log down by a page.  I will convert some of the enhancement requests to cards for the development project when I have time.   Some were pretty crusty and I haven't seen the behavior in a while so I closed those that I believe have been corrected.  I think we should close anything that isn't on the will fix list which is waiting for a response from the user more than a year.  I assigned stuff which was on my radar to myself.   Anything that does not have an assignee still needs to be examined and either tagged for fixing or resolved.

**Comment by Thrameos** [comment]
What remains on this thread to do?

**Comment by marscher** [comment]
We can add the logo to the sphinx documentation. Another issue, which arises presumably from the organisation transfer, is the lack for Appveyor ci reports.

**Comment by originell** [comment]
@marscher I'm going to close this issue and open up a new one for myself about the logo (#396). Related to that, I'll also try to create a new README that seems more welcoming.

The lack of CI Reports,… can I help with that? If so, open up a new issue for me please.
