### ISSUE TITLE
access sikulixapi.jar on macOS

### ISSUE THREAD

**Issue by toney9527** [jpype-project/jpype#336]
I tried to use Jpype1 to automate GUI with 'sikulixapi.jar' on macOS.
This package works well when I imported it  on my java project, but had problem when I used Jpype1 to access it.

Here is my code:
`from jpype import *

startJVM(get_default_jvm_path(), '-ea', r'-Djava.class.path=somepath/sikulixapi.jar')
Screen = JClass('org.sikuli.script.Screen')
s = Screen()
`
When the code ran into 'Screen = JClass('org.sikuli.script.Screen')', my program was in deadlock. Not any responses unless ending the python process.

OSX: 10.12(x64)
python: 3.6
Jpype1: latest
JDK: 1.8.0_171(x64)

I'm looking forward to your suggestions，thanks.

**Comment by toney9527** [comment]
I got the sikulixapi.jar on this site:
https://launchpad.net/sikuli/sikulix/1.1.2

**Comment by Thrameos** [comment]
Best guess, the jar was trying to unpack a series of dll or shared libraries during the load phase the lead to an internal deadlock or some other failure.  It is not a pure jar code but is attempting to push native libraries into the system and then execute them.  I would recommend trying to run the command using pure java first to see if the error is coming from within the jpype layer or the java.  Based on the type of actions I am seeing it do I am guessing that the behavior is correct.  Jpype called the class loader on the class object and it never returns because it an internal deadlock in the jar. 

When I tried it hit an internal problem and failed with a reasonable error code.
```$ python3 testSik.py
java.io.IOException: Access is denied
        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.io.File.createTempFile(File.java:2024)
        at java.io.File.createTempFile(File.java:2070)
        at org.bridj.Platform.createTempDir(Platform.java:710)
        at org.bridj.Platform.<clinit>(Platform.java:227)
        at org.bridj.BridJ.register(BridJ.java:191)
        at org.sikuli.util.SysJNA$WinKernel32.<clinit>(SysJNA.java:23)
        at org.sikuli.script.RunTime.addToWindowsSystemPath(RunTime.java:1034)
        at org.sikuli.script.RunTime.libsExport(RunTime.java:992)
        at org.sikuli.script.RunTime.init(RunTime.java:738)
        at org.sikuli.script.RunTime.get(RunTime.java:312)
        at org.sikuli.script.RunTime.get(RunTime.java:122)
        at org.sikuli.script.RunTime.get(RunTime.java:337)
        at org.sikuli.script.Region.<clinit>(Region.java:23)
Traceback (most recent call last):
  File "testSik.py", line 3, in <module>
    sik = jpype.JClass('org.sikuli.script.Screen')
  File "/home/nelson85/devel/open/jpype/jpype/_jclass.py", line 91, in __new__
    return _JClassNew(args[0])
  File "/home/nelson85/devel/open/jpype/jpype/_jclass.py", line 147, in _JClassNew
    javaClass = _jpype.PyJPClass(arg)
jpype._jclass.UnsatisfiedLinkError: org.bridj.Platform.sizeOf_ptrdiff_t()I
```

Simple code like the following should be all that jpype is executing.   We just load the class and then list the declared methods and fields.  If you can do this successfully from within pure java then it could be a jpype issue.   If it is a jpype issue, I would recommend recompiling with TRACING enabled and submit the trace log here.  
```
public class MyTest
{
   public static void main(String[] args)
   {
      Class screenClass = java.lang.Class.forName("org.sikuli.script.Screen");
      // Then test code to list declared methods and fields
   }
}
```

**Comment by toney9527** [comment]
Hi,
I did it successfully within pure java on Mac and also successful on Windows used the same python code. 
The tracing info stoped here.
```
 </B> <!-- JPTypeManager::findClass -->
</B> <!-- JPypeModule::findClass -->
<B msg="PyJPClass::__dealloc__" >
</B> <!-- PyJPClass::__dealloc__ -->
<B msg="PyJPClass::__dealloc__" >
</B> <!-- PyJPClass::__dealloc__ -->
<B msg="PyJPClass::__dealloc__" >
</B> <!-- PyJPClass::__dealloc__ -->
<B msg="JPJavaEnv::NewGlobalRef" >
  <M>JPJavaEnv::NewGlobalRef : 4299319200 => 4351100704</M>
</B> <!-- JPJavaEnv::NewGlobalRef -->
<B msg="JPJavaEnv::NewGlobalRef" >
  <M>JPJavaEnv::NewGlobalRef : 4299319280 => 4351100744</M>
</B> <!-- JPJavaEnv::NewGlobalRef -->
<B msg="JPJavaEnv::NewGlobalRef" >
  <M>JPJavaEnv::NewGlobalRef : 4299319288 => 4350995328</M>
</B> <!-- JPJavaEnv::NewGlobalRef -->
<B msg="JPypeModule::findClass" >
  <M>JPypeModule::findClass : org.sikuli.script.Screen</M>
  <B msg="JPTypeManager::findClass" >
    <M>JPTypeManager::findClass : org.sikuli.script.Screen</M>
```  
I would like to offer you a jar copy if you want, thanks.

**Comment by Thrameos** [comment]
Hmm,  seems like the exact same jar that I tried to run with.  The failure point is at the find class method in jni.  The fact that it worked fine on a PC from python makes me suspect that it is something they have placed in the dynamic native routines.  

I do not currently have access to a Mac.  My route to debugging this would be to get the source code for the jar and adding some information to try to trace down the loader routine.   JPype just called the jni find class routine and waited for a response which did not happen, so it must be on the java side.  Also you may want to verify that  JVM used by python is the same as the one you tested with for pure python.

**Comment by AlwaysLearning-1992** [comment]
> I got the sikulixapi.jar on this site:
> https://launchpad.net/sikuli/sikulix/1.1.2

I meet the same issue. do you have any solutions yet?

**Comment by AlwaysLearning-1992** [comment]
> I tried to use Jpype1 to automate GUI with 'sikulixapi.jar' on macOS.
> This package works well when I imported it on my java project, but had problem when I used Jpype1 to access it.
> 
> Here is my code:
> `from jpype import *
> 
> startJVM(get_default_jvm_path(), '-ea', r'-Djava.class.path=somepath/sikulixapi.jar')
> Screen = JClass('org.sikuli.script.Screen')
> s = Screen()
> `
> When the code ran into 'Screen = JClass('org.sikuli.script.Screen')', my program was in deadlock. Not any responses unless ending the python process.
> 
> OSX: 10.12(x64)
> python: 3.6
> Jpype1: latest
> JDK: 1.8.0_171(x64)
> 
> I'm looking forward to your suggestions，thanks.

I meet the same issue. do you have any solutions yet?

**Comment by Thrameos** [comment]
Unfortunately it remains as it is.  I can't debug something that works for me.
