### ISSUE TITLE
Some problem in converting "HashMap" to any data structure in python

### ISSUE THREAD

**Issue by Fridgi** [jpype-project/jpype#339]
I invoke a method to return a "HashMap" type variable in Java. And I need this variable in my python code. Just like below,

The Java code is `HashMap<String, String> result = factory.ner(str);` which returns a "HashMap" variable result. Then I want to use jpype to start JVM and invoke factory.ner() then get the "HashMap" return value. 

So, here is the question, I cannot find any data structure to hold this "HashMap" object in python. The error says that 
`RuntimeError: No matching overloads found for ner in find. at native\common\jp_method.cpp:127`

It seems that there is no data structure in python to hold the return object in Java. So what should I do to hold the "HashMap" object? I've read the document of jpype, there are some type conversions from python object to java object, so how can a java object be transferred into python object?

**Comment by Fridgi** [comment]
Thanks, I know what you mean. But the error still occurs. 

Here's the case,
`HashMap<String, String> result = factory.ner(String);`  
can be executed well in native JVM.

However, I want to write a python interface of the java code. The python code can be simplified below,

`startJVM(getDefaultJVMPath())`
`factory = JPackage("org").fnlp.nlp.cn.CNFactory.getInstance("fnlp/models")`
`line = 'Some Chinese Here'`
`factory.ner(line) #ERROR occurs in this line` 
`shutdownJVM()`

Then the error says that
`RuntimeError: No matching overloads found for ner in find. at native\common\jp_method.cpp:127`
It is obvious that I use the same param (a string) between java and python code, and 'factory' is a 'org.fnlp.cn.CNFactory' object, so what's the problem....

**Comment by Thrameos** [comment]
I think I see the problem.  The method you are trying to access is a static and the type of that you are trying to access is an object instance.  The version you are using requires class instances for statics and object instances for methods.

Thus,
`public static HashMap<String, String> ner(String s)` callable on `JClass('fnlp.nlp.cn.CNFactory')`
`public String tag2String(String input)`  callable on `JClass('fnlp.nlp.cn.CNFactory').getInstance()`

Try...
```
startJVM(getDefaultJVMPath())
factory = JClass('fnlp.nlp.cn.CNFactory')
line = 'Some Chinese Here'
factory.ner(line) #ERROR occurs in this line
shutdownJVM()
```

Hopefully this will solve your issue.

The ability to access statics from an object instance part of our development branch.

**Comment by Fridgi** [comment]
Sorry, it is still not working yet...
Because I need `getInstance()` to pass `fnlp/models` to the instance of the `org.fnlp.nlp.cn.CNFactory`

I've tried the code you modified above, 

`startJVM(getDefaultJVMPath())`
`factory = JClass('org.fnlp.nlp.cn.CNFactory')`
`line = 'Some Chinese Here'`
`factory.ner(line)`
`shutdownJVM()`

And another error occurs...
`TypeError: 'NoneType' object is not callable`
That means "factory" is a class, not an object. Maybe python doesn't allow we use a class to access static method in this way. 

It seems a little bit wired, I can't understand why the method `ner()` of class `org.fnlp.nlp.cn.CNFactory` is designed to be a 'static' method even though the class need an instance to pass the info of the 'model'.

What's more, the static method in java can be accessed through an instance like below

`CNFactory factory = CNFactory.getInstance("fnlp/models");`
`HashMap<String, String> result = factory.ner(str);` 

and with a warning of IntelliJ  IDEA 

`static member 'org.fnlp.nlp.cn.CNFactory.ner(java.lang.String)' accessed via an instance reference`

**Comment by Thrameos** [comment]
If you need both the class and the instance then just get them both as variables.

```
startJVM(getDefaultJVMPath())
Factory = JClass('org.fnlp.nlp.cn.CNFactory')
factoryModels = factory.getInstance("fnlp/models")
line = 'Some Chinese Here'
Factory.ner(line)
result = factoryModels.tag2String(line)
shutdownJVM()
```

I can't figure out the NoneType because you did not provide any context as to what line was executed on the fail.

I do recommend you check the signatures of the java code to make sure you don't have something funny.  It seems really odd to have a static method in a factory that is expected to be used from get instance.

Yes in Java you can access with a static with a warning.  In JPype 0.6 it is currently an error to try to access a static from an object.  JPype 0.7 will allow statics to be called on objects without issue.  The technical issue is that python used bound methods on object instances and functions on classes.  Thus the JPype object placed the statics into the meta class so that they could be bound methods.  Unfortunately that means they are not in the object instance lookup table, hence you get the error no overload found.

**Comment by Thrameos** [comment]
For reference I use HashMaps as returns all the time.   The problem has something to do with the signatures of the java code.   If you don't want to have 2 variables you should also be able to get to the static using `factory.__class__.ner(line)`  because in python the class and its methods are available through `__class__` member.

**Comment by Fridgi** [comment]
Thanks, I'm not familiar with java so I need to acquire some java knowledge. 
The java code is not written by me, I just want to write an python interface of it.
And the signatures of the java code is quite the same I've referred before.

`public static HashMap<String, String> ner(String s)`

And the README of java code lists the using of the method "ner()"

`import org.fnlp.nlp.cn.CNFactory;`
`CNFactory factory = CNFactory.getInstance("models");`
`HashMap<String, String> result = factory.ner(str);`

That is, after writing these code in the IntelliJ IDEA, there is a warning in the code

`static member 'org.fnlp.nlp.cn.CNFactory.ner(java.lang.String)' accessed via an instance reference`

It is really confusing that when I use the `JClass('org.fnlp.nlp.cn.CNFactory')` to invoke static method `ner()`, the error in the line `Factory.ner(line)`  is 

`TypeError: 'NoneType' object is not callable`

In addition, when I use the `JClass('org.fnlp.nlp.cn.CNFactory').getInstance('fnlp/models')`, the error is,

`RuntimeError: No matching overloads found for ner in find. at native\common\jp_method.cpp:127`

I fail to use both methods to invoke 'ner()'......

Fortunately, I found an another solution of my code to replace the method 'ner()'. This problem is really frustrating, and thanks for instructing me, I learnt a lot from digging into the java and python code deeply. And if you have any new ideas about the problem, just tell me, THANKS.

**Comment by Thrameos** [comment]
I checked with the latest version.  I had no issue executing.

```
Factory = jpype.JClass('org.fnlp.nlp.cn.CNFactory')
line = 'Some Chinese Here'
Factory.ner(line)
```

However, the return type is a NULL pointer hence it is equal to None.  It seems like you solved it so no need to dig further.  Good luck in your project.
