### ISSUE TITLE
Segfault on startJVM - Django 2.0 - Celery 4.2

### ISSUE THREAD

**Issue by Xyleroth** [jpype-project/jpype#341]
Hey. I keep running into a segfault error using a Django application with Celery. The Celery process fires off a task using Jpype and hits a segfault attempting to start the JVM. I can run this process successfully outside of celery. 

Here are the import versions: 
Jpype1 == 0.6.3
Django == 2.0.7
Celery == 4.2.1

System: MacOS High Sierra

Firing off a task in the web application with the following code 

    print(jpype.getDefaultJVMPath())
    print(jpype.isJVMStarted())
    if not jpype.isJVMStarted():
        print("Starting JVM...")
        jpype.startJVM(
            jpype.getDefaultJVMPath(), '-ea'
            )

Gives me this output: 

[2018-08-15 09:56:31,139: WARNING/ForkPoolWorker-8] /Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home/lib/jli/libjli.dylib
[2018-08-15 09:56:31,140: WARNING/ForkPoolWorker-8] False
[2018-08-15 09:56:31,141: WARNING/ForkPoolWorker-8] Starting JVM...

**A fatal error has been detected by the Java Runtime Environment:**
**SIGSEGV (0xb) at pc=0x00007fff50c619d7, pid=36049, tid=515**

... (There's a massive stack track that I'll avoid putting in for now). 

Like I said earlier, outside of Celery, I can run JPype fine. If I enter the console separately and enter the above commands, the JVM works without issue. 

I also created a separate test using only Celery and a task containing the code with JPype and that worked successfully. Somehow when it runs in the Django instance, I'm running into this issue. 

I don't know if anyone else has encountered an issue similar to this. If I could get some pointers on what causes the seg fault issue generally, that may help me identify what might be going on. I'm betting it's some type of environment issue.

I appreciate any help / guidance you can give on this issue.

**Comment by Thrameos** [comment]
Barring attempting to run with tracing turned on I can't see much reason for a fail.   Perhaps there is an incompatible jvm being called.

**Comment by Xyleroth** [comment]
I'll try using Java 8.0 and update with the results. Currently I'm on Java 10.

**Comment by Thrameos** [comment]
Java 10 is not currently covered by our test matrix.  Thus you may be encountering a new issue.

**Comment by Xyleroth** [comment]
Just solved it by creating a docker container (ubuntu image) containing Java 8, celery and Django. So it was indeed an environment issue. Thanks for the help!
