### ISSUE TITLE
how to dispose a JClass

### ISSUE THREAD

**Issue by blckhm** [jpype-project/jpype#349]
Is there any built-in method for disposing a jclass from jpype? Or setting value null for garbage collector

**Comment by Thrameos** [comment]
The JClass is a cached instance shared by all objects of the class and thus will persist until the jvm is exited.  Objects created from JClass live with the same scope as the python object.  Thus any python method that removes a Python object (del, local scoping, or set to a new value) will schedule the item for garbag collection.  There are no garentees when it will be collected.  But there are ways to force the collection.  You can find examples of this in our leak check test cases under 'test/jpypetests'.

**Comment by blckhm** [comment]
Thank you
