### ISSUE TITLE
Google search for JPype points to sourceforge.

### ISSUE THREAD

**Issue by Thrameos** [jpype-project/jpype#357]
@originell The sourceforge version looks very out of date.  Any hope of getting the page to redirect to here?

**Comment by marscher** [comment]
Maybe the original author @devilwolf could help us with this?

**Comment by jbfaden** [comment]
I was playing with an old jpype for months before I thought to check if the project had been moved over to github.  Happy to see it's still active!

**Comment by originell** [comment]
Woah sorry for not seeing this issue.

I haven't heard from Steve (devilwolf) in ages. I will try to reach him via email. Let's hope we can get an answer back. Other than that, what would probably help is a website. We already own the jpype.org domain. so maybe putting a github page behind that would work.

I will have some time available next week where I can take a shot at this. Maybe it helps with our ranking.

**Comment by jbfaden** [comment]
This is a really important project for me, keep up the good work!  We've been using similar bridges from IDL and Matlab for years, to provide access to our Java plotting software (Autoplot) and this already providing similar functionality to SciPy users.

**Comment by originell** [comment]
to keep everyone updated: steve answered to my email (i have @marscher in CC as well, so it's not a closed thing). He will have a look and see what he can do :)

**Comment by DevilWolf** [comment]
I have updated the Sourceforge project to point to the new Jpype org domain. There isnt much more I can do at this point. Anyone landing on the JPype page on sourceforge will see in the describe that the project and moved, and be greeted witha  big button saying redirecting them here. 

Hopefully this will help. You guys are doing amazing work on this project. If there is even anything I can do to help, please let me know.

**Comment by originell** [comment]
@DevilWolf thanks a lot! Any chance you could also put a notice on http://jpype.sourceforge.net/index.html ?

**Comment by Thrameos** [comment]
@DevilWolf Have you had a chance to look it this issue?

**Comment by Thrameos** [comment]
Well there is a not so obvious moved button but it still gets 45 downloads a week for ancient code.   I guess we will close this for now.
