### ISSUE TITLE
Disable automatic type conversion in order to continuously calling java method?

### ISSUE THREAD

**Issue by passerbythesun** [jpype-project/jpype#373]
I would like to do some string processing in a continuous way, e.g., `java.lang.String(" some string").trim().replaceAll("regex", "replacement")`, so that `re` module is not needed and code consistency with java side is better.

But I find that `trim()` returns unicode type, which result in an `AttributeError: 'unicode' object has no attribute 'replaceAll'` error. 

To my understanding, Java`trim()` returns `java.lang.String` type, so this should be the effort of automatic type conversion of java string to python unicode. Is it right?

If so, how to disable automatic type conversion in this situation? Or if not, is there another way to do so?

**Comment by Thrameos** [comment]
Fixed and tested in 0.7.
