### ISSUE TITLE
getClassPath interprets the path on import

### ISSUE THREAD

**Issue by Thrameos** [jpype-project/jpype#375]
I get different behaviors depending on the order for 

```
import os
os.environ['CLASSPATH']='mypath'
import jpype
print(jpype.getClassPath())
```

and

```
import os
import jpype
os.environ['CLASSPATH']='mypath'
print(jpype.getClassPath())
```

Apparently the CLASSPATH is  being cached at the start rather than interpreted when the getClassPath is called.

**Comment by marscher** [comment]
Agreed it would add more flexibility, when the paths is read when 
getClassPath is invoked.
