### ISSUE TITLE
Test directory cleanup

### ISSUE THREAD

**Issue by Thrameos** [jpype-project/jpype#378]
We have a lot of code in the test directory which is very outdated or not relevant to the current api.  Most are not actually tests but rather code evaluating something during development.  We should just delete these or update them and make them samples.

**Comment by marscher** [comment]
At least we should move these files into a subfolder which name indicates that these stubs are not meant to be used as regular tests. I would not waste much time on updating these.

**Comment by marscher** [comment]
fixed by #379
