### ISSUE TITLE
JPype importer interferes with https://github.com/python/cpython/blob/2708578736d1aa15685495e9b94b827a8e185a8c/Lib/pickle.py#L94

### ISSUE THREAD

**Issue by KOLANICH** [jpype-project/jpype#384]
https://github.com/python/cpython/blob/2708578736d1aa15685495e9b94b827a8e185a8c/Lib/pickle.py#L94

I guess we need to move them into an own namesapace, like `jtypes`

**Comment by Thrameos** [comment]
Not sure I understand the problem.  We are to raise ImportError so the behavior is correct.  We are trying to march jython on imports.

**Comment by KOLANICH** [comment]
Not quite, #384 fixes that.
