### ISSUE TITLE
pip install JPype1-py3

### ISSUE THREAD

**Issue by terna** [jpype-project/jpype#390]
Just an info: in Linux (Ubuntu 18.04) a solved the problems in linking java installing this specific version of Jpype: https://pypi.org/project/JPype1-py3/

Done with
pip install JPype1-py3

Best, Pietro

**Comment by marscher** [comment]
Thanks for sharing this. Note that py3 branch is officially dead and has been merged into this project. If you do not share the specifics (like build logs, failing and succeeding, produced via pip install -v), there is nothing we can do in order to improve this.
