### ISSUE TITLE
Issue in installation on OSX 10.14.1

### ISSUE THREAD

**Issue by samarthaggarwal** [jpype-project/jpype#391]
I have java version 11.0.1
I have set $JAVA_HOME = /Library/Java/Home
then I cloned the git repo
next I ran the command : sudo python3 setup.py install
the installation was successful but when I opened a python interactive shell and tried to import jpype, i got the following error

>>> import jpype
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jpype/__init__.py", line 17, in <module>
    from ._jpackage import *
  File "jpype/_jpackage.py", line 18, in <module>
    import _jpype
ImportError: No module named _jpype

**Comment by marscher** [comment]
That is very weird. I can not reproduce this. Do you have the same environment for ipython3?

**Comment by Thrameos** [comment]
Is this still an issue?
