### ISSUE TITLE
when I shutdown jvm and then restart it later in same process,I got "OSError: JVM is already started"

### ISSUE THREAD

**Issue by songkang1993** [jpype-project/jpype#393]
I want to start jvm when request in, and shutdown jvm at request out, it wrong.
How can I do it?

**Comment by songkang1993** [comment]
**if I shutdown jvm and use "jpype.JClass", it will tell me :**

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fa4d37ce190, pid=70472, tid=0x00007fa4d50c7700
#
# JRE version: OpenJDK Runtime Environment (8.0_191-b12) (build 1.8.0_191-8u191-b12-0ubuntu0.16.04.1-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.191-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [_jpype.cpython-35m-x86_64-linux-gnu.so+0x29190]  JPJavaEnv::FindClass(char const*)+0x20
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/edz/projects/pfsource/test/hs_err_pid70472.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
bash: line 1: 70472 Aborted                 env "PYCHARM_HOSTED"="1" "PYTHONUNBUFFERED"="1" "PYTHONIOENCODING"="UTF-8" "PYCHARM_MATPLOTLIB_PORT"="49245" "JETBRAINS_REMOTE_RUN"="1" "PYTHONPATH"="/home/edz/projects:/home/edz/projects/pfsource/handlers:/home/edz/projects/pfsource:/home/edz/.pycharm_helpers/pycharm_matplotlib_backend" '/usr/bin/python' '-u' '/home/edz/projects/pfsource/test/var_test.py'

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by marscher** [comment]
Read the documentation. Restarts are not supported (by JVM/JNI implementation).
