### ISSUE TITLE
error: Microsoft Visual C++ 10.0 is required. Get it with "Microsoft Windows SDK 7.1":

### ISSUE THREAD

**Issue by jpainam** [jpype-project/jpype#394]
Hi,
i'm trying to install jpype,  using this command `python setup.py --ant=D:\apache-ant-1.9.13\bin\ant.bat install` but ends up having this error
```python
error: Microsoft Visual C++ 10.0 is required. Get it with "Microsoft Windows SDK 7.1":
```
I'm using Windows 10 and I have most of the Visual C++ Redistributable installed. Trying to installed SDK 7.1. I Have this error again
```python
Some Windows SDK components require the RTM .NET Framework 4. Setup detected a pre-release version of .NET Framework 4. If you continue with Setup, these components will not be installed. If you want to install these components, click Cancel, then install the .NET Framework 4 from https://go.microsoft.com/fwlink/?LinkID=187668 and then rerun Setup.

Click OK to continue.
```
What can be the problem. Thank you

**Comment by jpainam** [comment]
Using `pip install JPype1-py3` solved the problem of installing jpype

**Comment by jpainam** [comment]
Hi. After following the installation procedure to install `JPype1` from source and install Microsoft Build Tools 2015 Update 3.
I have this error
```python
building '_jpype' extension
error: Microsoft Visual C++ 10.0 is required. Get it with "Microsoft Windows SDK 7.1": www.microsoft.com/do
wnload/details.aspx?id=8279
```
Thank you for help

**Comment by Thrameos** [comment]
Python modules require a specific version of Visual studio as per the documentation.
