### ISSUE TITLE
Issue when installing jpype on aix

### ISSUE THREAD

**Issue by gascoj** [jpype-project/jpype#399]
Hi Team,
I am finding the following error when installing the package on python3.6 on AIX

    gcc gcc -maix64 -pthread -bI:/opt/freeware/lib/python3.6/config-3.6m/python.exp -L. -L/usr/include -L/opt/freeware/include -L/usr/lib/threads -L/opt/freeware/lib64 -L/opt/freeware/lib -L/usr/lib64 -L/usr/lib -L. -L/usr/include -L/opt/freeware/include -L/usr/lib/threads -L/opt/freeware/lib64 -L/opt/freeware/lib -L/usr/lib64 -L/usr/lib build/temp.aix-7.1-3.6/native/common/jp_array.o build/temp.aix-7.1-3.6/native/common/jp_arrayclass.o build/temp.aix-7.1-3.6/native/common/jp_class.o build/temp.aix-7.1-3.6/native/common/jp_classbase.o build/temp.aix-7.1-3.6/native/common/jp_env.o build/temp.aix-7.1-3.6/native/common/jp_field.o build/temp.aix-7.1-3.6/native/common/jp_invocationhandler.o build/temp.aix-7.1-3.6/native/common/jp_javaenv.o build/temp.aix-7.1-3.6/native/common/jp_javaenv_autogen.o build/temp.aix-7.1-3.6/native/common/jp_jniutil.o build/temp.aix-7.1-3.6/native/common/jp_method.o build/temp.aix-7.1-3.6/native/common/jp_methodoverload.o build/temp.aix-7.1-3.6/native/common/jp_monitor.o build/temp.aix-7.1-3.6/native/common/jp_object.o build/temp.aix-7.1-3.6/native/common/jp_objecttypes.o build/temp.aix-7.1-3.6/native/common/jp_platform_linux.o build/temp.aix-7.1-3.6/native/common/jp_platform_win32.o build/temp.aix-7.1-3.6/native/common/jp_primitivetypes.o build/temp.aix-7.1-3.6/native/common/jp_primitivetypes_autogen.o build/temp.aix-7.1-3.6/native/common/jp_proxy.o build/temp.aix-7.1-3.6/native/common/jp_reference.o build/temp.aix-7.1-3.6/native/common/jp_referencequeue.o build/temp.aix-7.1-3.6/native/common/jp_typemanager.o build/temp.aix-7.1-3.6/native/common/jp_typename.o build/temp.aix-7.1-3.6/native/common/jp_voidtype.o build/temp.aix-7.1-3.6/native/python/jpype_javaarray.o build/temp.aix-7.1-3.6/native/python/jpype_javaclass.o build/temp.aix-7.1-3.6/native/python/jpype_javanio.o build/temp.aix-7.1-3.6/native/python/jpype_memory_view.o build/temp.aix-7.1-3.6/native/python/jpype_module.o build/temp.aix-7.1-3.6/native/python/jpype_python.o build/temp.aix-7.1-3.6/native/python/py_class.o build/temp.aix-7.1-3.6/native/python/py_field.o build/temp.aix-7.1-3.6/native/python/py_hostenv.o build/temp.aix-7.1-3.6/native/python/py_method.o build/temp.aix-7.1-3.6/native/python/py_monitor.o build/temp.aix-7.1-3.6/native/python/pythonenv.o -L/opt/freeware/lib64 -o build/lib.aix-7.1-3.6/_jpype.so
    gcc: error: gcc: No such file or directory
    gcc: error: unrecognized command line option '-bI:/opt/freeware/lib/python3.6/config-3.6m/python.exp'
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-z5apshuj/JPype1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-8n1f9iaf/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-z5apshuj/JPype1/

can you please guide me on whats wrong ? Thanks in advance

**Comment by Thrameos** [comment]
I haven't access to an AIX system.  It should be as easy as "python3 setup.py install".  Do you have gcc installed or have you set the compiler?
