### ISSUE TITLE
Compile Fails on RHEL 5 Python 3.6.8 JPype1 0.6.3

### ISSUE THREAD

**Issue by EdLipson5117** [jpype-project/jpype#401]
Doing a non-root install of python and then adding modules as PIP is blocked.
Python was built
./configure --prefix=/rootpathobfuscated/python/Python-3.6.8 --enable-shared

Java set to (this java works with other python build from when I could use pip to get the files).
bash-3.2$ echo ${JAVA_HOME}
/usr/java/jre1.7.0_79

setup was run: from JPype1-0.6.3.tar.gz:
bash-3.2$ python setup.py install >/tmp/JPype1_setup_error.out
setup.py:67: UserWarning: Falling back to provided JNI headers, since your provided JAVA_HOME "/usr/java/jre1.7.0_79" does not provide jni.h
  ' JAVA_HOME "%s" does not provide jni.h' % java_home)
warning: no previously-included files matching '*.pyc' found anywhere in distribution
no previously-included directories found matching 'test/classes'
[JPype1_setup_error.zip](https://github.com/jpype-project/jpype/files/2971255/JPype1_setup_error.zip)

In file included from /rootpathobfuscated/python/Python-3.6.8/Include/Python.h:8,
                 from native/common/jp_env.cpp:24:
/rootpathobfuscated/python/Python-3.6.8/pyconfig.h:1481:1: warning: "_POSIX_C_SOURCE" redefined
In file included from /usr/include/stdint.h:26,
                 from native/jni_include/jni.h:43,
                 from native/common/include/jpype.h:87,
                 from native/common/jp_env.cpp:17:
/usr/include/features.h:154:1: warning: this is the location of the previous definition
In file included from /rootpathobfuscated/python/Python-3.6.8/Include/Python.h:8,
                 from native/common/jp_env.cpp:24:
/rootpathobfuscated/python/Python-3.6.8/pyconfig.h:1493:1: warning: "_XOPEN_SOURCE" redefined
In file included from /usr/include/stdint.h:26,
                 from native/jni_include/jni.h:43,
                 from native/common/include/jpype.h:87,
                 from native/common/jp_env.cpp:17:
/usr/include/features.h:156:1: warning: this is the location of the previous definition
In file included from /rootpathobfuscated/python/Python-3.6.8/Include/Python.h:8,
                 from native/common/jp_proxy.cpp:18:
/rootpathobfuscated/python/Python-3.6.8/pyconfig.h:1481:1: warning: "_POSIX_C_SOURCE" redefined
In file included from /usr/include/stdint.h:26,
                 from native/jni_include/jni.h:43,
                 from native/common/include/jpype.h:87,
                 from native/common/jp_proxy.cpp:17:
/usr/include/features.h:154:1: warning: this is the location of the previous definition
In file included from /rootpathobfuscated/python/Python-3.6.8/Include/Python.h:8,
                 from native/common/jp_proxy.cpp:18:
/rootpathobfuscated/python/Python-3.6.8/pyconfig.h:1493:1: warning: "_XOPEN_SOURCE" redefined
In file included from /usr/include/stdint.h:26,
                 from native/jni_include/jni.h:43,
                 from native/common/include/jpype.h:87,
                 from native/common/jp_proxy.cpp:17:
/usr/include/features.h:156:1: warning: this is the location of the previous definition
/usr/bin/ld: cannot find -lpython3.6m
collect2: ld returned 1 exit status
error: command 'g++' failed with exit status 1

**Comment by Thrameos** [comment]
Do you have the python development package installed as well as the python runtime?
