### ISSUE TITLE
Pycharm not importing jpype

### ISSUE THREAD

**Issue by prituja** [jpype-project/jpype#402]
Hi,
I am using python 3.6 v and  jdk1.8.0_201. I am using PyCharm IDE and had installed jpype1 0.6.3 version. 
Is jpype1 same as jpype?  As "import jpype" is not recognised in the IDE. 
Hope someone can help. 
Thank you.

**Comment by originell** [comment]
Hey @prituja,
just a quick question: what do you mean by `is not recognised in the IDE`? What errors do you get when you try to run your python file?

**Comment by prituja** [comment]
Hi @originell 
Please check the attached image. It throws an error startJVM is not defined.
![image](https://user-images.githubusercontent.com/24406666/54577233-ed82b880-4a35-11e9-9a1d-8f9807ca0c0f.png)
Thanks

**Comment by originell** [comment]
mh that's weird. could you maybe try installing the latest master from github?

```
$ pip install git+https://github.com/jpype-project/jpype.git#egg=jpype
```

**Comment by prituja** [comment]
I get the requirement is already satisfied when I try to install from GitHub and I get the same error.

**Comment by originell** [comment]
hey,
ah yeah sorry, you will first have to uninstall the package before you can pull the latest github source:

```
$ pip uninstall jpype1
$ pip install git+https://github.com/jpype-project/jpype.git#egg=jpype
```

I hope that works now :D
