### ISSUE TITLE
set callback for java function

### ISSUE THREAD

**Issue by PraflyGod** [jpype-project/jpype#404]
I had a java function whose parameter is a callback function. And I want to call that java function.
How can I achieve that using jpype? Please help me.

**Comment by Thrameos** [comment]
Assuming the callback is an interface then create a JProxy that implements the interface, create an instance of the JProxy and then feed the proxy instance to the method.  The exact formulation of how to do with is in the test code for proxies.

Once we release version 0.7 it will be much easier as all that is required is creating a python class with the appropriate annotations.  In some cases such as if the interface is marked in java as a functional interface, it will be automatic.  All that is required will be to place an object with the call interface defined.

--Karl

**Comment by PraflyGod** [comment]
Thanks for that. I will check the example and will give the feedback.

**Comment by Thrameos** [comment]
0.7 is on master now.  Release shortly.  The new docs should cover your usage.
