### ISSUE TITLE
macos 10.14 error native/common/include/jpype.h:107:10: fatal error: 'map' file not found

### ISSUE THREAD

**Issue by pandeng0108** [jpype-project/jpype#415]
python2.7安装JPype1 - 0.6.3先提示：
![image](https://user-images.githubusercontent.com/48948730/57514877-fca22a80-7343-11e9-95fd-ed861335b7f9.png)

执行setup.py前执行：export CFLAGS='-stdlib=libc++' 但是又报 error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
![image](https://user-images.githubusercontent.com/48948730/57514853-eb591e00-7343-11e9-966c-c4d049bb4bf8.png)
辛苦帮忙看下什么原因，困扰很久了

**Comment by Thrameos** [comment]
The issue appears to be that C++ is not properly installed on your system.  You appear to have a working C compiler but not C++.  The first error message says that libstdc++ headers are missing.  It gave you a switch to pass to clang, but that switch is only implemented on OS 10.7.   Hence, the second failure.  Not sure why a mac would suggest a switch that isn't usable on the installed version, but it appears that is what it did.  

So suggestions in order of simplicity:
- Use a packaging system to get a prebuilt version of JPype.   For example, anaconda can be installed on a mac and provided Python and JPype. 

-  See if you can install the proper C++ headers for Mac OS 10.6.  I am not sure exactly what the procedure is for installing mac packages.  I believe it is xcode.  https://www.ics.uci.edu/~pattis/common/handouts/macclion/clang.html

- Upgrade your system to a later version of Max OS 10.7 (last resort)

BTW my coworker loved the chrome translation... "hard to help see what causes, trouble for a long time"

**Comment by NancyGu** [comment]
I installed Anaconda, and update macos to 10.14, but the problem still existed.
according to Thrameos, I found the warning : 
![WechatIMG7](https://user-images.githubusercontent.com/32775720/58221888-bc30ac80-7d46-11e9-8358-39eb6ddf6748.jpeg)

Macos has updated libc++, it led to the missing
I tried this and solved the problem:
https://stackoverflow.com/questions/53033202/cvxpy-stlibc-installation-error-on-macos-mojave
`CFLAGS=-stdlib=libc++ pip install cvxpy
export MACOSX_DEPLOYMENT_TARGET=10.10`

**Comment by Thrameos** [comment]
If you have anaconda you should be able to bypass the whole issue with

conda install -c conda-forge jpype1

Using the binary will save you from needing to build from source.

The message is telling you the same thing as before.  You have C installed, but C++ libraries/header are missing.  Not sure how to install them, but you will need to consult a MacOs forum.  Once you can compile C++ code with statements like ``#include <map>`` and ``#include <string>``.  It is possible that I am misinterpreting the error.  I you can successfully compile, test C++ code using std library but it is only failing in JPype then it could be an issue with setup.py.

Thus my suggestion, try the binary version.  If that does not work try manually compiling some C++ code yourself.  If that works paste the C++ code, the command line you used to compile it, and the complete command that failed so I can look at the options used by the compiler.

**Comment by NancyGu** [comment]
OK，thanks for ur detailed explanation. I learned more.
