### ISSUE TITLE
User Guide v2

### ISSUE THREAD

**Issue by Thrameos** [jpype-project/jpype#432]
My coworker feels that our current guide is poorly organized.  It is in random order, doesn't define terms, is *not* compelling, and buries the most important information.

He recommends reordering it something like

- Introduction
  - What and why JPype
  - Use cases examples
  - Limitations
- Basic usage
  - Definition of terms (Class, ClassFactory, wrapper, etc)
  - Importing and Class factories
  - Class, fields, methods, overloading , casting
  - Type conversions
  - Arrays, inner classes
- Advanced usage
  - Threading
  - Proxies
  - Customizers
  - Performance tips

Obviously not something to bite off before 0.7 release, but certainly a goal.

**Comment by marscher** [comment]
Am 21.05.2019 um 23:04 schrieb Karl Nelson:
> My coworker feels that our current guide is poorly organized. It is in 
> random order, doesn't define terms, is compelling, and buries the most 
> important information.
I think he is perfectly right about this.
> 
> He recommends reordering it something like
> ...
makes sense to me!

> Obviously not something to bite off before 0.7 release, but certainly a goal.
Postpone it, this can even wait until 1.0 :)
