### ISSUE TITLE
Environment variables not passed to Java on Cygwin

### ISSUE THREAD

**Issue by Thrameos** [jpype-project/jpype#442]
While testing for another bug, I discovered that Java does not appear to be getting environment variables.  It appears to affect windows/cygwin with openJDK 1.8.  I am not sure if other platforms are affected. As some are vital to operations, this leads to unacceptable behavior on windows as 
``USERPROFILE`` must be set to get a valid temp directory.

**Comment by Thrameos** [comment]
Problem appears to be confined to Cygwin versions of python.

**Comment by marscher** [comment]
So only Cygwin is broken in that sense?

**Comment by Thrameos** [comment]
Appears so.  I can't see any reason for the problem.  Nothing we are doing would affect the environment.  It must be an interaction with cygwin and Java dll.  I am just going to document it and move on.

**Comment by Thrameos** [comment]
I moved this to the limitations. Way to much trouble to figure out how env is moving behind the scenes.
