### ISSUE TITLE
JPype get_default_jvm_path 

### ISSUE THREAD

**Issue by mattomatic** [jpype-project/jpype#452]
I think that the way the trunk looks now we can no longer run:

```
import jpype

path = jpype.get_default_jvm_path()
```

As it now results in this:
```
AttributeError: module 'jpype' has no attribute 'get_default_jvm_path'
```

In 0.6.3 this was runnable and documented, but since #334 the jpype/_core.py __all__ has been refactored so that `get_default_jvm_path` is not exported by default. 

Was this deliberate to move away from get_default_jvm_path -- should we add it back to __all__ to preserve backwards compatibility?

Current:
```
__all__ = [
    'isJVMStarted', 'startJVM', 'attachToJVM', 'shutdownJVM',
    'getDefaultJVMPath', 'getJVMVersion', 'isThreadAttachedToJVM', 'attachThreadToJVM',
    'detachThreadFromJVM'
]
```

Modified???
```
__all__ = [
    'isJVMStarted', 'startJVM', 'attachToJVM', 'shutdownJVM',
    'getDefaultJVMPath', 'getJVMVersion', 'isThreadAttachedToJVM', 'attachThreadToJVM',
    'detachThreadFromJVM','get_default_jvm_path'
]
```

**Comment by Thrameos** [comment]
I am not opposed to exposing an old stub.  Would it be okay if it issues a deprecated warning?   There are other things that have to be broken because the method provided was unsafe, but an old symbol should be fine.

**Comment by Thrameos** [comment]
The symbols was removed as part of the symbol clean up where all symbols that were not intending to be imported on ``from jpype import *`` where killed.  I suppose we can still have the symbol existing in jpype without appearing in the module export list, though that would also break compatibility with users that imported all symbols.  

After the patch I get this result. 

```
$ python3 -Wd test2.py
test2.py:3: DeprecationWarning: jpype._core.get_default_jvm_path is deprecated, use getDefaultJVMPath instead
  path = jpype.get_default_jvm_path()
```

Note that string behavior and ``JException`` are different between JPype 0.6.3 and 0.7.0.  Strings require manual requests to convert to python and the layer of the tree wrapping exceptions were dropped.

BTW thanks for testing with the new code.  Please report any issues.

**Comment by mattomatic** [comment]
Cool, happy for this to have deprecated warning for the next release. I've already updated the code to no longer use that method, but when I first ran into the issue it was not clear to me if it was accidentally or purposefully removed.
