### ISSUE TITLE
JProxy does not handle single interfaces as strings properly

### ISSUE THREAD

**Issue by kyle-downey** [jpype-project/jpype#467]
When _convertInterfaces(intf) in _jproxy checks "if not isinstance(intf, collections.Sequence)" with a single str-typed value of intf, it's not converting it to a list. Consequently it then does "for i in intf" and iterates over the characters in the string, yielding a ClassNotFoundException when it tries to load a class with the name corresponding to the first character in the string.

This is with Python 3.7 and latest cut of 0.7 branch.

**Comment by Thrameos** [comment]
Thanks for the bug report.  Seems like an easy fix to check for str and unicode first, but can you give me a short example so that I can add it to the test bench?

**Comment by kyle-downey** [comment]
Reproducing it is easy: JProxy('java.lang.Runnable', ...) will break; JProxy(['java.lang.Runnable'], ...) will work.

**Comment by Thrameos** [comment]
Hopefully dealt with in #470
