### ISSUE TITLE
Need windows wheels for release

### ISSUE THREAD

**Issue by Thrameos** [jpype-project/jpype#479]
@marscher The deprecation message is forcing people to switch from JPype1-Py3 to JPype1 but we have not yet cut a release which is forcing people to install older versions which is really not our intent.   I think we need to decide what pulls make the 0.7.0 cut and put out the release shortly. 

https://stackoverflow.com/questions/56425722/what-is-the-issue-with-this-attempt-to-install-boilerpipe3-for-python/56461793#56461793

Is there anything I can do to help get the release ready?  Also have we got a plan on how to publish the wheels?  That was the primary driver for people to use the JPype-Py3 branch.

**Comment by marscher** [comment]
I can provide wheels for Linux, but I do not have any intention to do so for windows. Do you have experience with providing them? Maybe we can incorporate the folks of Py3 fork to help us with that?

I'm really sorry for lacking behind to review all of these proposed changes, but I guess you did the right things to improve the overall situation. So I suggest you decide yourself which things you want to include in 0.7 and what to postpone for a major.

**Comment by Thrameos** [comment]
Okay I will look to see what it takes to make a wheel for windows.

**Comment by marscher** [comment]
Karl has built wheels for the last two releases.
