### ISSUE TITLE
Visual C++ 14.0 is required to install JPype1 on Windows 10

### ISSUE THREAD

**Issue by RichardDally** [jpype-project/jpype#510]
Is it a lack of dependencies in package or a bug ? It's such a pain to install all visual studio tools (admin rights are forbidden in my company).

C:\Windows\system32>python -m pip install JPype1
Collecting JPype1
  Using cached https://files.pythonhosted.org/packages/28/63/784834e8a24ec2e1ad7f703c3dc6c6fb372a77cc68a2fdff916e18a4449e/JPype1-0.7.0.tar.gz
Installing collected packages: JPype1
  Running setup.py install for JPype1 ... error
    ERROR: Complete output from command 'C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\XXXXXXX\\AppData\\Local\\Temp\\pip-install-gbwyt_vx\\JPype1\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\XXXXXXX\AppData\Local\Temp\pip-record-mhlfd472\install-record.txt' --single-version-externally-managed --compile:
    ERROR: C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'use_scm_version'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\jpype
    copying jpype\beans.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\imports.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\nio.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\reflect.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\types.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_classpath.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_core.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_cygwin.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_darwin.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_gui.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jarray.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jboxed.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jclass.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jcollection.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jcomparable.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jcustomizer.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jexception.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jinit.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jio.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jobject.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jpackage.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jproxy.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jstring.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jtypes.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_jvmfinder.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_linux.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_pykeywords.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\_windows.py -> build\lib.win-amd64-3.7\jpype
    copying jpype\__init__.py -> build\lib.win-amd64-3.7\jpype
    running build_ext
    running build_java
    Using Jar cache
    creating build\lib
    creating build\lib\org
    creating build\lib\org\jpype
    creating build\lib\org\jpype\classloader
    copying native\jars\org\jpype\classloader\JPypeClassLoader.class -> build\lib\org\jpype\classloader
    copying native\jars\org.jpype.jar -> build\lib
    running build_thunk
    Building thunks
    C:\Users\XXXXXXX\AppData\Local\Temp\pip-install-gbwyt_vx\JPype1\setupext\build_ext.py:85: FeatureNotice: Turned ON Numpy support for fast Java array access
      FeatureNotice)
      including thunk build\lib\org\jpype\classloader\JPypeClassLoader.class
      including thunk build\lib\org.jpype.jar
    building '_jpype' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command "'C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\XXXXXXX\\AppData\\Local\\Temp\\pip-install-gbwyt_vx\\JPype1\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\XXXXXXX\AppData\Local\Temp\pip-record-mhlfd472\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\XXXXXXX\AppData\Local\Temp\pip-install-gbwyt_vx\JPype1\

**Comment by Thrameos** [comment]
Which python installation are you using?  The binary version of JPype is available on windows using anaconda.  Just do a conda install of python and JPype1 package.  

The pip installation builds from source which unfortunately will always require the build tools as most of the code is in C++.  

I currently am not building whl files largely because I do not know which tools are required to construct a wheel installations other than anaconda for which we already provide binaries.  

I can try to produce a Windows wheel file, but I am not sure if the wheel constructed using anaconda will be usable for your system.  It produces a few warnings that seems to indicate there may be issues.  I can post it in the release area.
```
removing build\bdist.win-amd64\wheel
C:\ProgramData\Miniconda3\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'use_scm_version'
  warnings.warn(msg)
F:\nelson85pl\nelson85\devel\open\jpype\setupext\build_ext.py:85: FeatureNotice: Turned ON Numpy support for fast Java array access
  FeatureNotice)
C:\ProgramData\Miniconda3\lib\site-packages\wheel\pep425tags.py:80: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
  warn=(impl == 'cp')):
C:\ProgramData\Miniconda3\lib\site-packages\wheel\pep425tags.py:84: RuntimeWarning: Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
  warn=(impl == 'cp')):
```

Assuming you want to be a guinea pig and tell me if they work I can post it.

**Comment by RichardDally** [comment]
Hello @Thrameos, I'm using raw (i.e. no Anaconda) Python 3.7.3 on Windows 10 64 bits.
I don't mind installing Anaconda on my PC but this will be painful for production deployment in my company...
I can try the wheel file if you are ok with that.

**Comment by Thrameos** [comment]
Okay the wheel files I produced using anaconda are on the release page.  Give them a try and report back.  They should be work for windows 64 bit with numpy installed.  I am worried that version problems between the anaconda and the raw install as well as numpy may cause problems.

**Comment by Mause** [comment]
Those wheels do appear to work, but without them being published to pypi, it's a pain to install them as you must manually find and download them. This is especially a problem when deploying to remote systems or on build machines. Any chance of having them published?

**Comment by Thrameos** [comment]
@marscher Can you push the wheels to pypi?   It appears that I can use anaconda to create them.

**Comment by marscher** [comment]
Sure, I can do that.

**Comment by marscher** [comment]
pypi folks have become anal about checking everything prior uploading: 

```
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: Invalid value for classifiers. Error: 'Programming Language :: Java :: 8' is not a valid choice for this field for url: https://upload.pypi.org/legacy/
```
I remember that I have removed this line locally prior building the linux wheels. I think I can just edit the setup and repack these. But we should definitely remove this line in the repo too.

**Comment by Thrameos** [comment]
Any other wheels that we need to produce?  I can set up some virtual envs as needed.   My local admins are strongly encouraging developers to drop Python 2.7, but I can likely still produce it if we need it.

**Comment by marscher** [comment]
done.

**Comment by zugkraft** [comment]
Hello @Thrameos, first of all thanks for this great lib.
Windows wheels are missing for version 0.7.3 on pypi, so are there any plans to generate and distribute them on pypi for this and future versions.
I also use raw python, like @RichardDally...

**Comment by Thrameos** [comment]
Yes.   I will build the windows binaries over the weekend.  We are still working on a solution to use azure pipelines to build releases.
