### ISSUE TITLE
Setup code coverage

### ISSUE THREAD

**Issue by Thrameos** [jpype-project/jpype#511]
Looking at other repos I see a number of them run code coverage tools.  It may be worth doing the same for that project.  But we are a very mixed language package, so it is less than clear how well these tools will work.  I poked a bit at Codecov, seems like it is simple and free to add at Github market place.

@marscher any opinion on whether Codecov is worth trying here?  Is there an alternative we should consider?

**Comment by marscher** [comment]
I haven't seen any service so far supporting multi-language projects. I'm using Codecov for other Python based projects.

**Comment by Thrameos** [comment]
I am generally of the opinion that some coverage checker is better than no coverage checker.  Thus I guess I should spend some time setting up codecov when I next get a few free cycles.
