### ISSUE TITLE
Installing Into Maya's embedded Python:  DLL load failed: The specified module could not be found. # 

### ISSUE THREAD

**Issue by chonigman** [jpype-project/jpype#519]
Hi, 

First off, thanks for this great project. This is very cool functionality and it works great when I'm running it directly in Python. However, I am running into an issue when I try to add it to a python script that I want to run in Maya's python environment. Unfortunately, Maya does not allow you to pip install packages so "installing" comes down to copying files to a specific folder. I've tried building the package from source and copying over the build files to the location that Maya will load it but I get the following error. 

`Error: ImportError: file C:\Users\Chonigman\Documents\maya\modules\mimic\scripts\extern\jpype\_jpackage.py line 19: DLL load failed: The specified module could not be found. # `

It seems like when the package tries to import _jpype this error is thrown. And I'm not sure why. I noticed in my 27 virtual environment, that there is a _jpype.pyd file one level up from the jpype folder, so I copied those over to the Maya location, but still get the same error. 

I understand this is not the usual use-case but we're hoping to interface with some hardware that only provides a Java SDK and it would be preferable for it to run within Maya. Any guidance would be much appreciated. 

Thanks!

**Comment by Thrameos** [comment]
The pyd file is a dll.  It must match the version of python that you are using both in terms of the version of python, the version of the compiler used to build it, and the architecture of the file (32/64 bit).  It sounds like the python version that you copied the dll from does not match the python executable or the file is not in the search path.

You can see where it is searching using 
```
import sys;
print('\n'.join(sys.path))
```

Did you try just using the setup.py to install the binary for you with ``python setup.py install``?

Unfortunately I have no knowledge of Maya.  It is possible they have disabled dll loading entirely.

**Comment by chonigman** [comment]
Ok, yeah that makes sense. Unfortunately Maya runs python from a zip file which I don't understand. I think I can point it to another version, but I need this to be easily deployed on other people's set up. I will look into this more later but for now I am setting up a TCP server to communicate with a script running jpype outside of maya which seems to be working for me right now. 

Thanks for the help!
