### ISSUE TITLE
Update Java

### ISSUE THREAD

**Issue by JavierLinaresCorporativo** [jpype-project/jpype#524]
Hi,

I'm new with JPype and I need to change DefaultJVMPath after a Java version update. I need to re-install JPype? If not, what is the procedure?

Sorry but my little english. Thanks.

**Comment by Thrameos** [comment]
Sorry for the delay, I was on vacation. 

It should be as simple as setting your JAVA_HOME environment variable.

**Comment by JavierLinaresCorporativo** [comment]
Hi Thrameos,

Thanks you for your answer. JAVA_HOME environment variable was setted sucesfully after Java version update, but jpype.getDefaultJVMPath() returns a 1.6 Java version but we was updated from 1.7 to 1.8.

We was reinstalled JPype but we obtains the same result. We aren't root but we have a sesudo to pip3.3 to install all packages. Can we do something more?

**Comment by Thrameos** [comment]
JPype does not in any way cache the value at the install time so it is a dynamic problem that installing wont fix.  So lets run down how to find the problem.

1) First make sure that when you print the environment variable JAVA_HOME from within Python that you get the correct JVM.  
2) Note that if the path is set improperly  it will go to one of the fall back patterns which may be finding the Java 1.6 version.  Thus verify that it has the stuff one expects in a JAVA_HOME

```
$ ls "$JAVA_HOME"
bin  conf  COPYRIGHT  include  jmods  legal  lib  README.html  release
```

3) The JVM version at JAVA_HOME must match the architecture of Python.  Thus if for example you are running 32 bit Python and Java is 64 bit, it may skip it and try to find another.

4) Assuming that Python has the correct JAVA_HOME and the path points to the root of the tree you will need to trace the loading path.

Depending on the architecture of your machine it will select on of 4 finders.  Determine which one is being loaded.

Lets assume that we are running Linux in which case the finder would have 3 methods.  The first checked if JAVA_HOME is invalid, the second looks to see if there is a java executable on the path and tries to find its home, and the third checks a series of known locations.
```
        # Search methods
        self._methods = (self._get_from_java_home,
                         self._get_from_bin,
                         self._get_from_known_locations)
```

You can get a dump of the whole process by using the python trace command.

Use a simple code like
```
import jpype
print(jpype.getDefaultJVMPath())
```

and run with 
```
$ python -m trace --trace test.py
```

You should be able to jump to the section which starts with `_jvmfinder.py` to see what is happening during the process.  

If for some reason you have a valid JAVA_HOME pointing to a JVM with the right architecture, please copy the portion of the trace where it refused to use it and I will see if we can correct the logic.  As far as I know all the finders are working.  Though darwin tend to be the most problematic.

@marscher Looking through the code I see a section with code that searches for pre vm7 on darwin.  As Java  1.6 is no longer supported, shouldn't we just drop that part of the finder?

**Comment by JavierLinaresCorporativo** [comment]
Hi Thrameos,

We had cheched some of your commands and we discovered the problem inside Jupyter configuration, but outside in command line works fine. At the moment is programmed a change for it, probably must be the solution.

Thanks a lot for your suggestions and your explicit answer.
