### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by boukenka** [jpype-project/jpype#526]
Hello,

When trying to install the jpype component for docker, I am getting the following error below:

Command line: **_docker-compose exec web pipenv install JPype1==0.6.3_**

Is there any workaround? I need to install that component with that version.

Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1992, in do_install
[pipenv.exceptions.InstallError]:       skip_lock=skip_lock,
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Collecting jpype1==0.6.3 (from -r /tmp/pipenv-n2nhr4ft-requirements/pipenv-b6e1jqtw-requirement.txt (line 1))', '  Using cached https://files.pythonhosted.org/packages/c4/4b/60a3e63d51714d4d7ef1b1efdf84315d118a0a80a5b085bb52a7e2428cdc/JPype1-0.6.3.tar.gz', 'Building wheels for collected packages: jpype1', '  Building wheel for jpype1 (setup.py): started', "  Building wheel for jpype1 (setup.py): finished with status 'error'", '  Running setup.py clean for jpype1', 'Failed to build jpype1', 'Installing collected packages: jpype1', '  Running setup.py install for jpype1: started', "    Running setup.py install for jpype1: finished with status 'error'"]
[pipenv.exceptions.InstallError]: ['ERROR: Command errored out with exit status 1:', '   command: /root/.local/share/virtualenvs/web_apis_service-Ge5MDPPQ/bin/python -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/tmp/pip-install-wvplfpar/jpype1/setup.py\'"\'"\'; __file__=\'"\'"\'/tmp/pip-install-wvplfpar/jpype1/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' bdist_wheel -d /tmp/pip-wheel-5sj_081m --python-tag cp37', '       cwd: /tmp/pip-install-wvplfpar/jpype1/', '  Complete output (54 lines):', '  running bdist_wheel', '  running build', '  running build_py', '  creating build', '  creating build/lib.linux-x86_64-3.7', '  creating build/lib.linux-x86_64-3.7/jpype', '  copying jpype/nio.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_jexception.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_linux.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_windows.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_cygwin.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_jwrapper.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_jvmfinder.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/JClassUtil.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_jboxed.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_pykeywords.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/reflect.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_jobject.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_core.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_jpackage.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_jio.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_jproxy.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_jcollection.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_gui.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/imports.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_jclass.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_jarray.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_refdaemon.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_darwin.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/__init__.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_classpath.py -> build/lib.linux-x86_64-3.7/jpype', '  copying jpype/_properties.py -> build/lib.linux-x86_64-3.7/jpype', '  creating build/lib.linux-x86_64-3.7/jpype/awt', '  copying jpype/awt/__init__.py -> build/lib.linux-x86_64-3.7/jpype/awt', '  creating build/lib.linux-x86_64-3.7/jpype/awt/event', '  copying jpype/awt/event/__init__.py -> build/lib.linux-x86_64-3.7/jpype/awt/event', '  copying jpype/awt/event/WindowAdapter.py -> build/lib.linux-x86_64-3.7/jpype/awt/event', '  creating build/lib.linux-x86_64-3.7/jpypex', '  copying jpypex/__init__.py -> build/lib.linux-x86_64-3.7/jpypex', '  creating build/lib.linux-x86_64-3.7/jpypex/swing', '  copying jpypex/swing/AbstractAction.py -> build/lib.linux-x86_64-3.7/jpypex/swing', '  copying jpypex/swing/pyutils.py -> build/lib.linux-x86_64-3.7/jpypex/swing', '  copying jpypex/swing/__init__.py -> build/lib.linux-x86_64-3.7/jpypex/swing', '  warning: build_py: byte-compiling is disabled, skipping.', '  ', '  running build_ext', "  building '_jpype' extension", '  creating build/temp.linux-x86_64-3.7', '  creating build/temp.linux-x86_64-3.7/native', '  creating build/temp.linux-x86_64-3.7/native/common', '  creating build/temp.linux-x86_64-3.7/native/python', '  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Inative/common/include -Inative/python/include -Inative/jni_include -I/usr/local/include/python3.7m -c native/common/jp_jniutil.cpp -o build/temp.linux-x86_64-3.7/native/common/jp_jniutil.o -ggdb', "  unable to execute 'gcc': No such file or directory", "  error: command 'gcc' failed with exit status 1", '  ----------------------------------------', '  ERROR: Failed building wheel for jpype1', '    ERROR: Command errored out with exit status 1:', '     command: /root/.local/share/virtualenvs/web_apis_service-Ge5MDPPQ/bin/python -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/tmp/pip-install-wvplfpar/jpype1/setup.py\'"\'"\'; __file__=\'"\'"\'/tmp/pip-install-wvplfpar/jpype1/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' install --record /tmp/pip-record-ubylnwzs/install-record.txt --single-version-externally-managed --compile --install-headers /root/.local/share/virtualenvs/web_apis_service-Ge5MDPPQ/include/site/python3.7/jpype1', '         cwd: /tmp/pip-install-wvplfpar/jpype1/', '    Complete output (54 lines):', '    running install', '    running build', '    running build_py', '    creating build', '    creating build/lib.linux-x86_64-3.7', '    creating build/lib.linux-x86_64-3.7/jpype', '    copying jpype/nio.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_jexception.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_linux.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_windows.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_cygwin.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_jwrapper.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_jvmfinder.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/JClassUtil.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_jboxed.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_pykeywords.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/reflect.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_jobject.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_core.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_jpackage.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_jio.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_jproxy.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_jcollection.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_gui.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/imports.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_jclass.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_jarray.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_refdaemon.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_darwin.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/__init__.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_classpath.py -> build/lib.linux-x86_64-3.7/jpype', '    copying jpype/_properties.py -> build/lib.linux-x86_64-3.7/jpype', '    creating build/lib.linux-x86_64-3.7/jpype/awt', '    copying jpype/awt/__init__.py -> build/lib.linux-x86_64-3.7/jpype/awt', '    creating build/lib.linux-x86_64-3.7/jpype/awt/event', '    copying jpype/awt/event/__init__.py -> build/lib.linux-x86_64-3.7/jpype/awt/event', '    copying jpype/awt/event/WindowAdapter.py -> build/lib.linux-x86_64-3.7/jpype/awt/event', '    creating build/lib.linux-x86_64-3.7/jpypex', '    copying jpypex/__init__.py -> build/lib.linux-x86_64-3.7/jpypex', '    creating build/lib.linux-x86_64-3.7/jpypex/swing', '    copying jpypex/swing/AbstractAction.py -> build/lib.linux-x86_64-3.7/jpypex/swing', '    copying jpypex/swing/pyutils.py -> build/lib.linux-x86_64-3.7/jpypex/swing', '    copying jpypex/swing/__init__.py -> build/lib.linux-x86_64-3.7/jpypex/swing', '    warning: build_py: byte-compiling is disabled, skipping.', '    ', '    running build_ext', "    building '_jpype' extension", '    creating build/temp.linux-x86_64-3.7', '    creating build/temp.linux-x86_64-3.7/native', '    creating build/temp.linux-x86_64-3.7/native/common', '    creating build/temp.linux-x86_64-3.7/native/python', '    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Inative/common/include -Inative/python/include -Inative/jni_include -I/usr/local/include/python3.7m -c native/common/jp_jniutil.cpp -o build/temp.linux-x86_64-3.7/native/common/jp_jniutil.o -ggdb', "    unable to execute 'gcc': No such file or directory", "    error: command 'gcc' failed with exit status 1", '    ----------------------------------------', 'ERROR: Command errored out with exit status 1: /root/.local/share/virtualenvs/web_apis_service-Ge5MDPPQ/bin/python -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/tmp/pip-install-wvplfpar/jpype1/setup.py\'"\'"\'; __file__=\'"\'"\'/tmp/pip-install-wvplfpar/jpype1/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' install --record /tmp/pip-record-ubylnwzs/install-record.txt --single-version-externally-managed --compile --install-headers /root/.local/share/virtualenvs/web_apis_service-Ge5MDPPQ/include/site/python3.7/jpype1 Check the logs for full command output.']

**Comment by Thrameos** [comment]
It seems like there is no gcc compiler installed.  Seems like the system is trying to build from source as there was no predefined wheel for that system.  But your build system is incomplete.  Not sure that I can help with setting up the docker as that is not really my area.

I suggest you install jpype on a similar system, build the jpype from source to create a binary distribution (`python setup.py bdist` if I remember correctly), then try to install that bdist into your docker.   That should satisfy the other tools requirement.

**Comment by boukenka** [comment]
Thanks for the advice. I am trying to install this package via a Windows command line for a Linux container (the choice of Linux was made via the docker menu running on Windows 10).
Following your recommendation, I had a look how to build a binary distribution. But it seems rather complicated.

**Comment by boukenka** [comment]
The problem is now solved. I now use python: 3.6 instead of python: 3.7-slim as the base image for the definition of the Dockerfile file. This solved the problem. Thanks again for the quick reply. 👍
