### ISSUE TITLE
CharSequence from string

### ISSUE THREAD

**Issue by Thrameos** [jpype-project/jpype#527]
Certain classes use CharSequence rather than string such as the java.time library.   JPype currently does not convert a Python string to this type automatically, thus a forced conversion is required.  This should likely be corrected.

**Comment by Nicolaus93** [comment]
How do you force a conversion? I tried both java.lang.CharSequence("my_string") and java.lang.CharSequence(JString("my_string")) but neither of them worked.

**Comment by Thrameos** [comment]
CharacterSequence is an interface so it can't be created directly which is why both of the lines you tried fail.   If a method requires a CharacterSequence then it must be cast to JString before it can be called.  

Example
```  
import jpype
import jpype.imports
jpype.startJVM(convertStrings=False)
from java.time import Instant
# Create a Python string from an Instant
now = str(Instant.now())
# Convert the String back to Java
then = Instant.parse(now)  
```

Signature of Instant.parse is `public static Instant parse(CharSequence text)`, thus last line fails because Python string is not convertible to CharacterSequence.  

```
TypeError: No matching overloads found for java.time.Instant.parse(str), options are:
        public static java.time.Instant java.time.Instant.parse(java.lang.CharSequence)

        at JPMethod::findOverload(native\common\jp_method.cpp:242)
        at JPMethod::findOverload(native\common\jp_method.cpp:245)
        at JPMethod::invoke(native\common\jp_method.cpp:253)
        at PyJPMethod::__call__(native\python\pyjp_method.cpp:167)
```

If I replace the last line with `then = Instant.parse(jpype.JString(now))` then everything works fine.  
There is no reason for this restriction as we can just define an inherent conversion to `java.lang.String` when we see `java.lang.CharacterSequence` was requested.
