### ISSUE TITLE
Cannot import classes via python modules

### ISSUE THREAD

**Issue by multigrid101** [jpype-project/jpype#535]
I am experiencing a weird problem when trying to use my own custom java classes in my python program.

```python
import jpype
import jpype.imports
from jpype.types import *

# Add my library and system objects
pype.addClassPath("target/system-objects-1.0-SNAPSHOT.jar")
jpype.startJVM()


x = org.asdf.fdsa.MyClass() # this throws an ERROR

# The following lines work
MyClass = jpype.JClass("org.asdf.fdsa.MyClass")
x = MyClass()
x.sayHello() # --> prints smt to stdout
```

The following error is thrown by the indicated line:
```
Traceback (most recent call last):
  File "jpype-test.py", line 28, in <module>
    x = org.asdf.fdsa.MyClass()
NameError: name 'org' is not defined
```

I would appreciate any help.

**Comment by theHamsta** [comment]
Does this work?

```python
pype.addClassPath("target/system-objects-1.0-SNAPSHOT.jar")
jpype.startJVM()

jpype.imports.registerDomain('org')
import org
x = org.asdf.fdsa.MyClass() # this throws an ERROR
```

**Comment by Thrameos** [comment]
There are several options.

You can use imports to import a class you would a Python module.
```
import jpype
import jpype.imports
jpype.addClassPath("target/system-objects-1.0-SNAPSHOT.jar")
jpype.startJVM()

from org.asjf.fdsa import MyClass
x = MyClass()
```

Or directly

```
import jpype
jpype.addClassPath("target/system-objects-1.0-SNAPSHOT.jar")
jpype.startJVM()
x = jpype.JClass("org.asjf.fdsa.MyClass")()
```

**Comment by multigrid101** [comment]
Hey, thanks for the quick replies. A mixture of both of ur answers turned out to be the solution:
My original

```python
import org.asdf.fdsa.MyClass
```
obviously doesn't work (wouldn't work in most python packages as can be seen by trying `import datetime.datetime.now`). Guess I should have figured that out on my own.

But `from org.asdf.fda import MyClass` worked. (thanks @Thrameos )

To get my actual code working, I had to use the trick with `jpype.imports.registerDomain('mydomain')` from @theHamsta (since the top-level domain in my actual code doesn't seem to be among the "default" domains for jpype. I couldn't share the actual code though because it was work-related.

So for anybody with the same problem, here is the final code that worked:
```python
import jpype
import jpype.imports
jpype.addClassPath("target/system-objects-1.0-SNAPSHOT.jar")
jpype.startJVM()

jpype.imports.registerDomain('mydomain')

from mydomain.asdf.fdsa import MyClass

x = MyClass()
```

Thanks a lot for the help.
(From my side, I consider the issue closed)
