### ISSUE TITLE
"and" and other keywords should be added to _pykeywords.py

### ISSUE THREAD

**Issue by rdemaria** [jpype-project/jpype#540]
the keyword "and" is missing in the `KEYWORDS` in _pykeywords.py as well as 
{'False', 'True', 'async', 'await', 'nonlocal', 'with'}

perhaps 
```
import keyword;
KEYWORDS=set(keyword.kwlist)
```
could be used

**Comment by Thrameos** [comment]
Thanks for the report.

I tried using keywords.kwlist previously, but it created the issue that Python2 and Python3 produced different sets of keywords which was a problem for users thus we need our keywords to be superset of both if we want the same behavior on both versions.  Unfortunately when I rolled back the patch I didn’t check the full keyword list that we were using.  I am guessing the original author must have overlooked “and” and “with”.  Of your list I do not see “async” or “await” but they are definitely keywords, thus it appears to be not just our bug but also Pythons.   “True”, “False” and “nonlocal” appear to just be stuff that we have not kept up to date.

Thus for now I will need to just add these to the list.  Once we drop Python 2 support then we will just switch to the keyword supplied assuming they are up to date. (which appears to be questionable)

Python 2.7:
['and', 'as', 'assert', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'exec', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'not', 'or', 'pass', 'print', 'raise', 'return', 'try', 'while', 'with', 'yield']

Python 3.6:
['False', 'None', 'True', 'and', 'as', 'assert', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']

JPype:
_KEYWORDS = set((
    "del", "for", "is", "raise",
    "assert", "elif", "from", "lambda", "return",
    "break", "else", "global", "not", "try",
    "class", "except", "if", "or", "while",
    "continue", "exec", "import", "pass", "yield",
    "def", "finally", "in", "print", "as", "None"
))

Java:
abstract
assert
boolean
break
byte
case
catch
char
class
const
continue
default
do
double
else
enum
extends
final
finally
float
for
goto
if
implements
import
instanceof
int
interface
long
native
new
package
private
protected
public
return
short
static
strictfp
super
switch
synchronized
this
throw
throws
transient
try
void
volatile
while

**Comment by rdemaria** [comment]
Thanks a lot for the quick feedback! Do you plan a bug fix release?

**Comment by Thrameos** [comment]
I will patch it when I get home, but the maintainer will have to do the release.  We are kind of overdue for a maintenance release (0.7.1) anyway.  I am about half way through the August 2020 release for 0.8.0.

**Comment by marscher** [comment]
Didn't we drop support for Python 2.7 in the 0.7 release? I think it should be safe to use the keywords module now. I guess we can assume that this list is always up to date, because it is maintained by CPython itself.

**Comment by Thrameos** [comment]
No we still have support for python 2 in 0.7.0.  I wasnt going to drop Python 2 until we start 0.8.
