### ISSUE TITLE
jpype launching many threads per java thread

### ISSUE THREAD

**Issue by roscherr** [jpype-project/jpype#543]
I am working with jpype 0.7 on Ubuntu 18.04, java 1.8_202, python 3.7, with startJVM options of jpype.getDefaultJVMPath(),"-ea","-Djava.class.path=/myjar.jar","-Xms4G","-Xmx32G". My machine has 36 physical cores, 72 with hyperthreading. I'm using jpype through jupyter notebook, although I've verified the same behavior outside of the notebook.

Whenever I call a java method jpype seems to launch 36 threads per java thread. The result is that running with anything over 2 java threads runs very slowly, much slower than using one thread. There is plenty of memory available, and I have also tried serialGC, but that had no effect.  Running the same method call as a java app runs as expected. The method typically uses 6GB of data and this is independent of number of threads.

Any help would be greatly appreciated.

**Comment by Thrameos** [comment]
Jpype does not have any capability to launch threads internally, thus they must either be launched by Python or by the JVM.  The best I could recommend is calling it directly from Python to see if it is something to do with Jypter.  If it still happens in Python directly then compile with ``--enable-tracing`` to see what JNI calls are being made.  

The only difference between a call made from Python and a call made internally from Java is the caller address.  A few procedures detect this and act differently but those are rare cases.  If you can recompile the JAR you can instrument it to see what is being called.

**Comment by roscherr** [comment]
Thanks for the quick response. I traced the issue to OMP_NUM_THREADS being set to #CPUs by numpy. My code is using BLAS.
