### ISSUE TITLE
Add git tag for 0.7.1 release

### ISSUE THREAD

**Issue by costrouc** [jpype-project/jpype#552]
I am packaging jpype for nixpkgs and need the latest version from github since it includes tests. Right now I an fixing it to a specific commit that is the 0.7.1 release but would be nicer to use a tag instead.

**Comment by Thrameos** [comment]
I think that 0.7.1 was not fully released. 
I cut the binary versions, but there wasnt a release point to attach it to yet.  I think that marscher got busy.  Our usual release usually adds the tags.

 @marscher can you address this?  I am still far from civilization.  Is there something you were waiting on me for?

**Comment by marscher** [comment]
On 1/1/20 4:13 PM, Karl Nelson wrote:
> I think that 0.7.1 was not fully released.
> I cut the binary versions, but there wasnt a release point to attach it to yet.  I think that marscher got busy.  Our usual release usually adds the tags.
> 
>   @marscher can you address this?  I am still far from civilization.  Is there something you were waiting on me for?
> 
I was on vacation. Just pushed the missing tag. Thanks for spotting. As 
already mentioned somewhere, the source archive was uploaded to PyPi.

**Comment by costrouc** [comment]
Thank you!

**Comment by Thrameos** [comment]
Thanks marsher.  I will clean up the pull requests soon.
