### ISSUE TITLE
Ctrl+C Segfault on Python/IPython

### ISSUE THREAD

**Issue by vwxyzjn** [jpype-project/jpype#556]
As indicated in this video https://youtu.be/6_9fqXGT5z8
```
from jpype import *
startJVM(getDefaultJVMPath(), "-ea")
test_varaible = 2
for i in range(10000):
    java.lang.System.out.printf("*")
```

After start running the code and that I pressed Ctrl+C, segfault happens and the variable `test_variable` could no longer be accessed.

**Comment by Thrameos** [comment]
Thank you for the bug report.  I attempted to replicate your error using the script that you provided.  However 10 attempts lead to the expected output without segfaulting.  My spyder did not replicate your output with stars appears on the display so clearly there is some differences going on.  My stars go to the console window that started rather than spyder.

```
>>> run test3.py
Traceback (most recent call last):

  File "C:\cygwin64\home\nelson85\devel\open\jpype\test3.py", line 5, in <module>
    java.lang.System.out.printf("*")

  File "C:\cygwin64\home\nelson85\devel\open\jpype\jpype\_jclass.py", line 209, in _JClassNew
    def _JClassNew(arg, loader=None, initialize=True):

KeyboardInterrupt

>>> run test3.py
Traceback (most recent call last):

  File "C:\cygwin64\home\nelson85\devel\open\jpype\test3.py", line 5, in <module>
    java.lang.System.out.printf("*")

  File "C:\cygwin64\home\nelson85\devel\open\jpype\jpype\_jclass.py", line 209, in _JClassNew
    def _JClassNew(arg, loader=None, initialize=True):

KeyboardInterrupt


>>> run test3.py
Traceback (most recent call last):

  File "C:\cygwin64\home\nelson85\devel\open\jpype\test3.py", line 5, in <module>
    java.lang.System.out.printf("*")

  File "C:\cygwin64\home\nelson85\devel\open\jpype\jpype\_jclass.py", line 209, in _JClassNew
    def _JClassNew(arg, loader=None, initialize=True):

KeyboardInterrupt
>>>
```

Based on the output in the video it is clear that you are running the latest series of JPype so it can't be a problem with an older version.  The usually failure in older versions was a problem with unattached threads.  The current version of JPype automatically connects threads whenever it is contacted from any thread, thus it is fairly unlikely the crash is happening in a JPype routine by design.  That doesn't mean there isn't a path that has a bad interaction.   

In order to debug further I am going to require more version information.  Specifically.
 - What type of machine are you running on, 
 - what version of spyder, 
 - what version of python
 - what version of Jpype
 - do you have any spyder modules installed to redirect the console

Thanks.

**Comment by vwxyzjn** [comment]
Thanks for the prompt reply. I am running the script in Arch Linux.

![image](https://user-images.githubusercontent.com/5555347/71866264-9688c580-30d3-11ea-9a62-dd2479f6af09.png)

I believe I was running a Spyder 3.6, and I just tested on Spyder 4.0 and it produced more meaningful errors as I hit Ctrl + C:

![image](https://user-images.githubusercontent.com/5555347/71866354-cb951800-30d3-11ea-9c06-78489ae0b5cb.png)

The python version is as follow:

Python 3.7.4 (default, Aug 13 2019, 20:35:49) 

```python
jpype.__version__
'0.7.1'
```

I just had vanilla anaconda installed, which comes with spyder

**Comment by Thrameos** [comment]
Thanks I will try to replicate with Ubuntu Disco as it is likely the closest image that I have loaded.

**Comment by Thrameos** [comment]
I was able to replicate the bug on Python 3.7 using Spyder 4 on Ubuntu.  I am not sure yet as to what is the source of the bug.  It does not appear on Python 2.7 nor does it appear on Windows with 3.7.   I am a bit unsure as how to proceed on this one.  It may be a bug in JPype or in Spyder but I will need to research as to how to get a core dump out of spyder console so that I can locate the source.

**Comment by Thrameos** [comment]
Update:  The bug still occurs with JPype 0.7.3 on Ubuntu, but does not appear on other platforms such as windows.  Still not sure if this is a JPype issue or a Spyder one.

**Comment by Thrameos** [comment]
Seems like Spyder is just the victim here.  The problem appears when running ipython directly.  I have updated the title accordingly.

**Comment by Thrameos** [comment]
I have identified the issue and created a PR.   The problem is Java will shutdown when it sees the INTR signal.   I have rerouted it to a more useful behavior.   It now gives... 

```
  File "org.jpype.manager.TypeManager.java", line -1, in org.jpype.manager.TypeManager.findClassForObject
  File "Thread.java", line -2, in java.lang.Thread.sleep
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "broken.py", line 17, in <module>
    o.printf("*")
__main__.InterruptedException: java.lang.InterruptedException: sleep interrupted
```

**Comment by vwxyzjn** [comment]
That's amazing. Thanks for the great work @Thrameos

**Comment by vwxyzjn** [comment]
Hi, please reopen this issue. The problem comes back again. Please see vwxyzjn/gym-microrts#9

**Comment by Thrameos** [comment]
As per the lastest PR, the behavior for Java is now switchable with respect to Ctrl+C.   The default when running interactivity is a "soft" Ctrl+C which can only interrupt if Java code if it is waiting for I/O.   The default when running as a batch process is a "hard" Ctrl+C which can interrupt even in the middle of a callback which may lead to a segmentation fault.   You can select which behavior you want with the "interrupt" keyword to startJVM which allows you to decide which mode you want to operate.

Unfortunately these are the only two modes that Java supports.   Java cannot break out of a thread other than wait interrupted which means that if you have a code which calls Java with a huge processing task and there are no I/O steps there is no way to break it out at all other than having the JVM terminate.   If the JVM does terminate that tends to leave Python hanging with pointers left to incomplete code which for many cases will lead to a segmentation fault.   

I can try to make it better by forcing Java to call Python exit which would prevent this type of segfault, but other than that options are pretty limited.

**Comment by Thrameos** [comment]
I was planning to release 1.1 this weekend, but if that option doesn't work for you or needs additional work please let me know.

**Comment by Thrameos** [comment]
Actually testing further, it appears something has gone wrong in the interactive path.  The Ctrl+C handlers are properly installed but the interrupt flag is not getting cleared which leads to a new segmentation fault.   Likely something in the previous fix has gotten lost and needs to be restored.

**Comment by vwxyzjn** [comment]
Hi @Thrameos , thanks for your kind support. I think the solution you proposed "forcing Java to call Python exit" sounds promising.

**Comment by Thrameos** [comment]
@vwxyzjn Please try the PR and see if it resolves your issue.   Unfortunately interactive Ctrl+C behavior is hard to test in the test bench so it may crop up again.   This was technically a new issue as the mechanism for the new fail was quite different from the previous time.   Unfortunately I have not found a good pattern for triggering the exit, but I will give it additional thought.

**Comment by vwxyzjn** [comment]
Hi @Thrameos , I'd be happy to try out the PR. Is there a link to the built python wheel of the PR I can download?

**Comment by Thrameos** [comment]
Wheels don't get built until it reaches master.   You can pip install if from the repo using the tag (there are some instructions on this, but I don't have access to them right now).   Pip install from source will require build tools to be installed.

As the PR cleared the checks I have put it in for review.  Hopefully, it will be ready shortly.
