### ISSUE TITLE
Publish manylinux wheels for v0.7.1

### ISSUE THREAD

**Issue by RasterBurn** [jpype-project/jpype#557]
`pip install JPype1==0.7.1` requires a compiler toolchain.  If manylinux wheels are published, this requirement is eliminated.

**Comment by Thrameos** [comment]
I can try through I am not very good at using docker.

**Comment by Thrameos** [comment]
I added test wheels to the release.  Please try them out and see if they work for you.

**Comment by RasterBurn** [comment]
works for me!  thank you @Thrameos!

**Comment by Thrameos** [comment]
No problem.  We are still resolving issues with the requirements in #566
