### ISSUE TITLE
Minimum Numpy versions for latest JPYPE version is no longer numpy>=1.6

### ISSUE THREAD

**Issue by MevaeR** [jpype-project/jpype#563]
By using versions between 1.6 and 1.15.4, importing jpype will results in the following error: 

```
>>> import jpype
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/jpype/__init__.py", line 17, in <module>
    import _jpype
ImportError: numpy.core.multiarray failed to import
```

Updating the minimal requirements to numpy>=1.16.0 will solve the issue.

See https://github.com/jpype-project/jpype/blob/afe8a8bc002959ba0a727795d6be68fbd6aabefc/setup.py#L41

**Comment by Thrameos** [comment]
Thanks for the bug report.  We will get it updated.

**Comment by Thrameos** [comment]
@marscher i think this is a flaw in the new build binaries.  The build system is choosing the latest numpy rather than the oldest.  So while the source dist works with insanely old versions, the binary version is stuck at newer.  I suggest we figure out the oldest version that numpy still supplies, made that the requirement, and add a version line to the binary docker builder so that we are built to something reasonable.

**Comment by marscher** [comment]
Yes, this would fix that issue. I would try to start with Numpy-1.8 as a start.

**Comment by Thrameos** [comment]
Okay I will give a try tonight.  Perhaps I can have the bdist_wheel alter the requirements section to match the version of numpy that was used to build it so that it automatically tracks.

**Comment by marscher** [comment]
On 1/14/20 9:51 PM, Karl Nelson wrote:
> Okay I will give a try tonight.  Perhaps I can have the bdist_wheel alter the requirements section to match the version of numpy that was used to build it so that it automatically tracks.
> 
> 

The latter sounds like an evil hack to me. It is non obvious behavior to 
have differing requirements depending on the built distribution.

Usually Python package maintainers just pin it in the build box (or via 
conda-build recipes).

**Comment by Thrameos** [comment]
I am not sure exactly how numpy and python binary compatibility operates in thus respect.   I thought the point of the tags were to help pip decide which version to pull.  If that is the case then the bin build and the source build will often have different requirements.

For example,  python 3.8 support was not added until numpy 1.17.4.  (It may run earlier but I cant tell without testing). Thus the newest version that a binary should require is 1.17.4.  I can try to force everything to build to the same point, though at some point back in time python changes and old numpy may conflict.
