### ISSUE TITLE
array.fromstring was removed in favor of tobytes in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [jpype-project/jpype#570]
https://bugzilla.redhat.com/show_bug.cgi?id=1791951

https://github.com/jpype-project/jpype/blob/49faa31c26a10377ebdeb4fa6a89d5ba9e8f97f5/setupext/build_thunk.py#L36

Thanks for the library!

**Comment by Thrameos** [comment]
Thanks for the bug report.  We will get it fixed shortly.

**Comment by hugovk** [comment]
Please see PR https://github.com/jpype-project/jpype/pull/572.
