### ISSUE TITLE
jpype.startJVM failing with java.lang.ClassNotFoundException: org.jpype.Utility

### ISSUE THREAD

**Issue by ZmeiGorynych** [jpype-project/jpype#573]
Hi,

I try using Jpype (0.7.1) via JayDeBeApi (1.1.1) on python 3.7, JayDeBeAPI installed via pip in a conda environment on Windows 10 Pro, but keep getting the following error.

Any idea how I can fix that?

Thanks,
E.

```
conn = jaydebeapi.connect(
    jdbc_driver_name,
    connection_string,
    {'user': dsn_uid, 'password': dsn_pwd},
    jars=jdbc_driver_loc)

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\pydevd.py", line 1758, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/.../postgres_jdbc_new.py", line 50, in <module>
    jars=jdbc_driver_loc,
  File "C:\Users\...\AppData\Local\conda\conda\envs\py37\lib\site-packages\jaydebeapi\__init__.py", line 381, in connect
    jconn = _jdbc_connect(jclassname, url, driver_args, jars, libs)
  File "C:\Users\...\AppData\Local\conda\conda\envs\py37\lib\site-packages\jaydebeapi\__init__.py", line 176, in _jdbc_connect_jpype
    jpype.startJVM(jvm_path, *args)
  File "C:\Users\...\AppData\Local\conda\conda\envs\py37\lib\site-packages\jpype\_core.py", line 227, in startJVM
    _jpype.startup(jvmpath, tuple(args), ignoreUnrecognized, convertStrings)
RuntimeError: java.lang.ClassNotFoundException: org.jpype.Utility
```

**Comment by Thrameos** [comment]
Something seems odd with your build.  Org.jpype.Utility is an internal class that is compiled into the shared library and loaded by the class loader.  It is possible to get this sort of error if the shared library was incorrectly compiled or perhaps there was another version found.    Do you have anything on your class path that could be interfering with the load process?

**Comment by ZmeiGorynych** [comment]
Tried downgrading jpype, 0.7.0 from either conda or pip lead to [this](https://github.com/baztian/jaydebeapi/issues/99), when I downgrade to 0.6.3 everything runs like a charm; changing back to 0.7.1 leads to the above issue recurring. Didn't change any other parameters such as classpath, just uninstalled jpype1 in that environment and installed the changed version.

**Comment by Thrameos** [comment]
Interesting.  I will try to replicate it locally when I get a chance.  Is there anything I need to do to trigger the problem such as starting switches, architecture other than conda?

**Comment by ZmeiGorynych** [comment]
Nope, vanilla win10Pro, created a fresh environment just now with 
```
conda create -n jpype_test python=3.7
activate jpype_test
pip install JayDeBeApi
pip install numpy
```
and the issue reproduces there.

**Comment by Thrameos** [comment]
I have replicated the problem.  It appears to be a problem with pips build mechanism using the pypi distribution. I pulled it directly from pypi and it has all the required files.  Thus it must be something in the way that pip is doing the install.  

@marscher Not sure I understand this one.  Same files but different results depending on whether pip built it or setup.py built it.  Have you seen anything like this?

**Comment by Thrameos** [comment]
Okay it is clear that it is a bad wheel file.  When I build from the tar.gz the wheel contains org/jpype/Utility.class.  The one on pypi is missing it.

@marsher  Can you pull the file JPype1-0.7.1-cp37-cp37m-win_amd64.whl  from the pypi?

**Comment by evyasonov** [comment]
I have the same issue on windows 10, python 3.7

**Comment by Jason-Kim** [comment]
I had same problem.
pip install JPype1==0.7.0 will help you.

**Comment by xavArtley** [comment]
Hello, same issue python3.7 jpype 0.7.1 installed from pypi
