### ISSUE TITLE
Issue when passing Python implementation of Java Interface back to Python for comparison in HashSet

### ISSUE THREAD

**Issue by peschue** [jpype-project/jpype#574]
Thank you for this great software!

I ran into a problem where I implement a Java interface in Python and then add these objects into a HashSet and try to remove such objects from that HashSet: the remove operation calls equal() / __eq__ and this obtains as first argument nicely the Python object, but as second argument an instance of org.jpype.proxy.JPypeInvocationHandler and this object does not permit to access members of the Python object.

Now I am not sure this should work, but it would be very nice for my use case. I use v0.7.1 built from github.

The following is a minimal example that demonstrates the issue, the real code does more useful stuff.

The idea is that the Test1Class constructor gets two sets of objects and subtracts the second from the first. The Test1Interface serves as the interface for the objects and at the same time as provider of the two sets (to keep the example small).

Test1Interface.java
```
package at.ac.tuwien.kr.hexlite.test;

import java.util.ArrayList;
import java.util.HashSet;

public interface Test1Interface {
   public int hashCode();
   public boolean equals(Object o);
   public String toString();
   public HashSet<ArrayList<Test1Interface> > provide1();
   public HashSet<ArrayList<Test1Interface> > provide2();
};
```

Test1Class.java
```
package at.ac.tuwien.kr.hexlite.test;

import java.util.ArrayList;
import java.util.HashSet;

public class Test1Class {
   public Test1Class(Test1Interface s) {
      HashSet<ArrayList<Test1Interface> > result = new HashSet<ArrayList<Test1Interface> >();
      System.err.println("initial: "+result);
      for(ArrayList<Test1Interface> x : s.provide1()) result.add(x);
      System.err.println("after add: "+result);
      for(ArrayList<Test1Interface> y : s.provide2()) result.remove(y);
      System.err.println("after remove: "+result);
   }
}
```

My Python script:
```
import jpype
jpype.startJVM(convertStrings=False)
from jpype import java
from jpype.types import *

print("Version:"+jpype.__version__)
Test1Interface = JClass("at.ac.tuwien.kr.hexlite.test.Test1Interface")
Test1Class = JClass("at.ac.tuwien.kr.hexlite.test.Test1Class")

@jpype.JImplements(Test1Interface)
class Test1Implementation:
	def __init__(self, something):
		self.something = something

	@jpype.JOverride
	def hashCode(self):
		return int(hash(self.something) & 0x7FFFFFFF)

	@jpype.JOverride
	def provide1(self):
		s = java.util.HashSet()
		
		tup1 = java.util.ArrayList()
		tup1.add(Test1Implementation("foo"))
		s.add(tup1)

		tup2 = java.util.ArrayList()
		tup2.add(Test1Implementation("bar"))
		s.add(tup2)
		return s

	@jpype.JOverride
	def provide2(self):
		s = java.util.HashSet()
		
		tup1 = java.util.ArrayList()
		tup1.add(Test1Implementation("bar"))
		s.add(tup1)

		tup2 = java.util.ArrayList()
		tup2.add(Test1Implementation("baz"))
		s.add(tup2)
		return s

	def __eq__(self, other):
		print("__eq__ repr(self)=%s vs repr(other)=%s", repr(self), repr(other))
		print("__eq__ str(self)=%s vs str(other)=%s", str(self), str(other))

		# does not work, other seems to be a Java-only-usable object - can I cast other to Test1Implementation?
		return self.something == other.something

	@jpype.JOverride
	def equals(self, other):
		return self.__eq__(other)

	def __str__(self):
		return str(self.something)

	@jpype.JOverride
	def toString(self):
		return str(self.something)

i = Test1Implementation("nothing")
c = Test1Class(i)
jpype.shutdownJVM()
```

This fails with:

```
Version:0.7.1
initial: []
after add: [[bar], [foo]]
__eq__ repr(self)=%s vs repr(other)=%s <__main__.Test1Implementation object at 0x7f2825bda8d0> <jpype._jclass.org.jpype.proxy.JPypeInvocationHandler object at 0x7f2825be3d90>
__eq__ str(self)=%s vs str(other)=%s bar bar
Traceback (most recent call last):
...
  File ".../test1minimal.py", line 64, in <module>
    c = Test1Class(i)
  File ".../python3.7/site-packages/jpype/_jobject.py", line 95, in __init__
    jv = self.__class__.__javaclass__.newInstance(*args)
jpype._jclass.RuntimeException: java.lang.RuntimeException: Python exception thrown: AttributeError: 'org.jpype.proxy.JPypeInvocationHandler' object has no attribute 'something'
```

I would appreciate any help what I could do differently or whether this is actually should work as I try to use it.

**Comment by Thrameos** [comment]
Thanks for the detailed bug report.  I will look over it this weekend and get back to you with a solution.

**Comment by Thrameos** [comment]
It appears to be a bug in the type system in JProxy.  Rather than calling the converter for the actually incoming type, it calls the converter for the declared type.  As the equals is taking a java.lang.Object it is getting a very general purpose converter rather than the one for the JProxy.  I think this can be resolved with checking the types.

The reason for the current implementation as we need primitives to actually get unpacked from Objects which are required.  I think the fix is to check to see if the requested type is a non-null object and if it is call the correct conversion code.  I am going to see if I can boil your example down into something that directly replicates that exact path so I can make a test and fix.

**Comment by peschue** [comment]
Thank you very much.
Please do not hesitate to ask me for further information or for testing on some branch of jpype.

**Comment by Thrameos** [comment]
Should be fixed in the linked pull request.  We should include it in the next release.

Thanks again for the bug report with test code.

**Comment by peschue** [comment]
The bugfix also makes my original project run without exceptions. Thank you very much!
