### ISSUE TITLE
[docs] Readthedocs build fails

### ISSUE THREAD

**Issue by marscher** [jpype-project/jpype#593]
https://readthedocs.org/projects/jpype/builds/10525115/

I think we should not import Jpype inside Sphinx conf.py, as it leads to some strange errors (e.g. due to a missing installation). Before you refactored so many things, this used to work, but now we rely on the jar being in place. So I guess we need to obtain the version info somehow differently now.

@Thrameos Do you think it would be feasible to do an AST parsing of the package init to obtain the version?

**Comment by Thrameos** [comment]
Sorry, I think I can take care of this one.  It is race condition between the customizer and  class.  That particular error should never have occurred as it is not possible to have an object live at that point.   But the current mock pattern doesn't know to respond correctly.

 If I add a few more mock lines to the conf.py it should work just fine.  But lets see if I can replicate it first.  As for AST parsing I think that we are likely getting more than just the version number, so the mock pattern is likely better.    Unfortunately, as I have moved so much stuff back into ``_jpype`` it is very possible that some of our docs are no longer reachable.

**Comment by marscher** [comment]
If we can mock it correctly I would greatly favour that solution.
