### ISSUE TITLE
0.7.x upgrade and threading question

### ISSUE THREAD

**Issue by adtrsa** [jpype-project/jpype#595]
We are using jpype via JayDeBeApi to access OsiSoft PI over JDBC.
So far it worked if used from single-threaded context.

From what I could gather from the jpype project page and stackoverflow etc. it should be OK to use
jpype in multi-threaded context with the appropriate thread types and if the following is done:
1) Ensure JVM is started once (assume prior to thread creation otherwise JVM start check has to be protected by a lock).
2) Ensure thread is attached to JVM prior to opening connection etc.

Examples of the above (not sure about the correctness of all of them) can be found here:
https://www.programcreek.com/python/example/107852/jpype.startJVM

Q1: Assuming conditions 1) and 2) are met, it should be OK for each thread to create its own jpype connection instance, correct?

Q2: I sometimes run into the following error when opening a jpype 0.6.3 connection from a thread:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f7300736aeb, pid=19803, tid=19827
#
# JRE version: OpenJDK Runtime Environment (14.0+18) (build 14-ea+18-Ubuntu-1)
# Java VM: OpenJDK 64-Bit Server VM (14-ea+18-Ubuntu-1, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [_jpype.cpython-36m-x86_64-linux-gnu.so+0x46aeb]  JPMethodOverload::ensureTypeCache() const+0x1b
```

What is the typical cause of this error?

Q3: So, I tried upgrading to 0.7.2 to see if the error goes away, but then run into the following error when opening a connection:
```
Traceback (most recent call last):
  File "$HOME/.pyenv/versions/3.6.10/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "$HOME/.pyenv/versions/3.6.10/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "pi_importer.py", line 161, in import_data_worker
    conn = jaydebeapi.connect("com.osisoft.jdbc.Driver", jdbc_conn, [jdbc_user, jdbc_pass], "PIJDBCDriver.jar")
  File "$HOME/.pyenv/versions/3.6.10/envs/stan/lib/python3.6/site-packages/jaydebeapi/__init__.py", line 381, in connect
    jconn = _jdbc_connect(jclassname, url, driver_args, jars, libs)
  File "$HOME/.pyenv/versions/3.6.10/envs/stan/lib/python3.6/site-packages/jaydebeapi/__init__.py", line 182, in _jdbc_connect_jpype
    for i in types.__javaclass__.getClassFields():
AttributeError: type object 'java.sql.Types' has no attribute '__javaclass__'
```

Any idea what causes this?  Bad configuration or use of jpype connection instance? Issue with the 3rd-party JDBC driver?

jpype.startJVM calls used (taken from one of the examples at previously mentioned URL):
```python
if jpype_version.startswith("0.6"):
    logging.debug("using jpype <= 0.6.x compatible JVM start")
    jpype.startJVM(jvm_path, args)
else:
    logging.debug("using jpype >= 0.7.x compatible JVM start")
    jpype.startJVM(jvm_path, args, ignoreUnrecognized=True, convertStrings=True)
```

Environment/platform details:
- Thread type: ```threading.Thread```
- OS: Ubuntu 19.10
- Python: 3.6.10
- JVM/JDK: openjdk 14-ea 2020-03-17

**Comment by Thrameos** [comment]
Thanks for the bug report.

The first issue has to do with caching problem that appears in JPype versions prior to the current master.  JPype does not have an internal synchronizer for its load methods command.  If the main thread touches all the types by importing them or using JClass to instantiate prior to creating the threads then the cache will be filled properly.  If not then each thread will try to fill the cache independently which can result in a race condition where one thread is filling the methods while another is attempting to use.   It is the race condition being triggered that is causing the fault.

The work around is simply to make sure that the master thread pulls each java class that is used.   We recently did a rewrite of the core to force everything through a synchronized Java method which should solve this problem going forward.  But that code is still working its way through review and bug hunt.

As for the second issue, that is jaydbeapi accessing a private structure in JPype which was removed when we applied a speed patch which internalized all of our structures to improve speed.  I will have to work with the author to see if I can find a workaround.

**Comment by adtrsa** [comment]
Thanks for clearing that up and the prompt reply, much appreciated.

So, if I understand correctly, issue 1 can be resolved by doing ```import jpype.JInt``` etc. for each of the expected Java types that my query results will contain? Luckily there aren't that many, so this is more than acceptable to ensure the cache crash is avoided.

Issue 2 is then a people scheduling problem, so I'll close this bug report/info request once I have tested the type import/JClass workaround.

**Comment by adtrsa** [comment]
OK, so I did a quick test...
opening a connection in main thread, and doing trivial queries like the following to hit the 2 'tables' my threads will be accessing did indeed get rid of the crash in the worker threads:

```
conn = create_connection(jdbc_conn, jdbc_user,jdbc_pass)
curs = conn.cursor()
curs.execute('select top 1 * from pipoint2')
curs.fetchall()
curs.execute('select top 1 * from picomp2')
curs.fetchall()
curs.close()
conn.close()
```

**Comment by Thrameos** [comment]
Good to here that workaround fixed it.  I tagged that bug during code review about 2 years ago but you are the first person that actually managed to replicate it.   The good news is that it will be fixed in the next release as the lazy method caching method was already scheduled for removal.

**Comment by adtrsa** [comment]
Always good when a bug can be moved from "Cannot reproduce" to "Confirmed".  Appreciate the help ;)
