### ISSUE TITLE
Conda-forge is serving the wrong version of JPype1 

### ISSUE THREAD

**Issue by Thrameos** [jpype-project/jpype#610]
One of my coworkers tried to pull JPype1 using conda-forge and was getting very strange behavior when using OSX.

If he specified one of the channels explicitly and used upgrade he got 0.6.3.  If he did another channel he got 0.7 install.  If he tried to force 0.7.2 it appears to have hung for a very long time.  (Perhaps it was building from source.)

I think the missing digit on the version number for 0.7.0 is haunting us as it seemed to always prefer ``osx-64/jpype1-0.7-py36hbf1eeb5_0.tar.bz2`` over ``osx-64/jpype1-0.7.2-py38ha1b3eb9_0.tar.bz2`` .  Perhaps it is having problem matching '.' against '-'.  Or there is some other problem upstream.  None of the options appears to pull the current version in his testing.   Talking through the office another user with OSX detected the same thing.

@marscher any chance you can look into this one?   I am not sure how to even start with this type of issue.

**Comment by marscher** [comment]
This should be fixed already. The build hasn't been triggered by github. So I asked some conda-forge admon to start it.

Am 11. März 2020 05:23:15 MEZ schrieb Karl Nelson <notifications@github.com>:
>One of my coworkers tried to pull JPype1 using conda-forge and was
>getting very strange behavior when using OSX.
>
>If he specified one of the channels explicitly and used upgrade he got
>0.6.3.  If he did another channel he got 0.7 install.  If he tried to
>force 0.7.2 it appears to have hung for a very long time.  (Perhaps it
>was building from source.)
>
>I think the missing digit on the version number for 0.7.0 is haunting
>us as it seemed to always prefer
>``osx-64/jpype1-0.7-py36hbf1eeb5_0.tar.bz2`` over
>``osx-64/jpype1-0.7.2-py38ha1b3eb9_0.tar.bz2`` .  Perhaps it is having
>problem matching '.' against '-'.  Or there is some other problem
>upstream.  None of the options appears to pull the current version in
>his testing.   Talking through the office another user with OSX
>detected the same thing.
>
>@marscher any chance you can look into this one?   I am not sure how to
>even start with this type of issue.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jpype-project/jpype/issues/610

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Thrameos** [comment]
Thanks.  I will ask them to test again when they are available.

**Comment by marscher** [comment]
https://github.com/conda-forge/jpype1-feedstock/issues/15
https://anaconda.org/conda-forge/jpype1/badges
