### ISSUE TITLE
importing the .py use Jpype will be reported as error

### ISSUE THREAD

**Issue by Wastexin** [jpype-project/jpype#652]
my question is I have competed a example.py with Jpype and it works well。
I want to import the  example.py  to test.py, use the function in example.py,but the pycharm report that '' jpype._jclass.NoClassDefFoundError: java.lang.NoClassDefFoundError: org/openscience/cdk/smiles/SmilesParser ''
i want to know how to fix it 
thank you

**Comment by Thrameos** [comment]
I would need to see a code snippet to see if you were using JPackage, jpype.imports, or JClass.  I suspect the problem is either an extra space in "SmilesParser " or a bad class path.

**Comment by Wastexin** [comment]
> I would need to see a code snippet to see if you were using JPackage, jpype.imports, or JClass. I suspect the problem is either an extra space in "SmilesParser " or a bad class path.

thank you for replying me !
these are my code:
1. example.py
```
from jpype import *
import jpype.imports
from jpype.types import *
import os.path
import numpy as np

jpype.addClassPath('cdk-2.3.jar')
startJVM(getDefaultJVMPath(), "-ea")
SmilesParser = jpype.JClass('org.openscience.cdk.smiles.SmilesParser')
IChemObjectBuilder = jpype.JClass('org.openscience.cdk.interfaces.IChemObjectBuilder')

........the function i define using the class  Above
def function1():
    ........


shutdownJVM()
```

2. test.py
```
from example.py import *
.....
```

**Comment by Wastexin** [comment]
if i put the two .py file into a .py, it works well, but i don't know why importing the example.py as a module it will be reported error.

**Comment by Thrameos** [comment]
I suspect you may be having issues with file paths.   Python and Java have different concepts of file locations.   Instead of importing a local jar file try using an absolute path.

```
jpype.startJVM('-ea', classpath=os.path.abspath(os.path.join(os.path.dirname(__file__), 'cdk-2.3.jar')))
```

So if your jar file is in a different directory it will still be picked up.

**Comment by Wastexin** [comment]
> I suspect you may be having issues with file paths. Python and Java have different concepts of file locations. Instead of importing a local jar file try using an absolute path.
> 
> ```
> jpype.startJVM('-ea', classpath=os.path.abspath(os.path.join(os.path.dirname(__file__), 'cdk-2.3.jar')))
> ```
> 
> So if your jar file is in a different directory it will still be picked up.

Using the method you say, I successfully ran the .py file, thank you. I haven't learned java, I thought they searched for packages the same way. Thanks again.
