### ISSUE TITLE
jp_classhints memleaks JPAttributeConversion

### ISSUE THREAD

**Issue by marscher** [jpype-project/jpype#654]
Just found it during valgrinding the direct buffer branch. In JPClassHints::addAttributeConversions a JPAttributeConversion pointer is created, which is never deleted (jp_classhints.cpp:188)

**Comment by Thrameos** [comment]
I am not sure that classhints themselves can every be released.  They are currently held in a Python table that never get cleared because the base module is does not have a load/unload method.  But I can add a handler pretty easy.

#655
