### ISSUE TITLE
convertStrings=True ignored in 0.7.2

### ISSUE THREAD

**Issue by thytterdal** [jpype-project/jpype#664]
Hello, I am having some issues with jpype version 0.7.2. 

Even if I have specified `convertStrings=True` when starting the JVM via `startJVM`, java strings are not automatically cast to python strings like in the previous versions. 

Is this a known issue?

**Comment by Thrameos** [comment]
Nothing in the test bench is showing an issue on this code path...

```
import jpype
from jpype.types import *
jpype.startJVM(convertStrings=True, classpath=["test/classes"])
fixture = JClass('jpype.common.Fixture')()
print(type(fixture.callString("hello")))
```

Returns type ``str`` as expected.

**Comment by thytterdal** [comment]
Ok, thank you for your answer. The issue I'm seeing must be caused by something else.
