### ISSUE TITLE
how to monitor the time of function running? if overtime then exit.

### ISSUE THREAD

**Issue by autodataming** [jpype-project/jpype#669]
how to monitor the time of function running? if overtime then exit.

 SmilesParser is JAVA class

code as the following:
```py
smilesParser = SmilesParser(DefaultChemObjectBuilder.getInstance())



 
# coding:utf8
import time
import signal

class TimeoutError(Exception):
    def __init__(self, msg):
        super(TimeoutError, self).__init__()
        self.msg = msg
 
 
def time_out(interval, callback):
    def decorator(func):
        def handler(signum, frame):
            raise TimeoutError("run func timeout")
 
        def wrapper(*args, **kwargs):
            try:
                signal.signal(signal.SIGALRM,handler)
                signal.alarm(interval)       # interval秒后向进程发送SIGALRM信号
                result = func(*args, **kwargs)
                signal.alarm(0)              # 函数在规定时间执行完后关闭alarm闹钟
                return result
            except TimeoutError as e:
                callback(e)
        return wrapper
    return decorator
 
def timeout_callback(e):
    print(e.msg)
    return "time out"


@time_out(5, timeout_callback)
def addmapbyRDT(rxnsmi):
#     time.sleep(2)
    reactionSM = rxnsmi
    cdkReaction = smilesParser.parseReactionSmiles(reactionSM)
#     cdkReaction.setID("test")
    forceMapping = True        #;//Overrides any mapping present int the reaction
    generate2D = True          #;//2D perception of the stereo centers
    generate3D = False         #;//2D perception of the stereo centers
    standardizeReaction = StandardizeReaction()  #; //Standardize the reaction
    rmt = ReactionMechanismTool(cdkReaction, forceMapping, generate2D, generate3D, standardizeReaction)
    s = rmt.getSelectedSolution()           #;//Fetch the AAM Solution
    reaction = s.getReaction()              #;//Fetch Mapped Reaction
    
    
    performAtomAtomMapping = reaction
    return sg.create(performAtomAtomMapping)


rxnsmi = "CC(=O)C=C.CC=CC=C>>CC1CC(CC=C1)C(C)=O"
rxnsmi = 'BrB(Br)Br.O=C(COCc1ccccc1)N1CCCc2sc(-c3ccc(O[C@@H]4C[C@@H](N5CCCCC5)C4)cc3)nc21.O>>O=C(CO)N1CCCc2sc(-c3ccc(O[C@@H]4C[C@@H](N5CCCCC5)C4)cc3)nc21'

addmapbyRDT(rxnsmi)  
```

**Comment by Thrameos** [comment]
Not quite sure if this is a question?  I would recommend not trying to do this with signals as the interactions between Java and signals is fairly platform dependent.   The easier approach would be to let Java handle interrupting.  Simply use ``JImplements`` to convert the method into a ``Callable`` then ask Java to create a ``FutureTask`` from the callable.   You then call ``run()`` and then call ``get()`` with a timeout.  If the result isn't needed because it went too long call ``cancel()``.

https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/FutureTask.html

**Comment by Thrameos** [comment]
I would do something like this...
```

def limit(method, timeout):
    """ Convert a Java method to asynchronous call with a specified timeout. """
    def f(*args):
        @jpype.JImplements('java.util.concurrent.Callable')
        class g(object):
            @jpype.JOverride
            def call(self):
                method(*args)
                return "YES"
        future = jpype.JClass("java.util.concurrent.FutureTask")(g())
        jpype.JClass('java.lang.Thread')(future).start()
        try:
            return future.get(int(timeout*1000), jpype.JClass('java.util.concurrent.TimeUnit').MILLISECONDS)
        except jpype.JClass('java.util.concurrent.TimeoutException') as ex:
            future.cancel(True)
            raise RuntimeError("canceled", ex)
    return f

Thread = jpype.JClass('java.lang.Thread')
print(limit(Thread.sleep, timeout=1)(200))
print(limit(Thread.sleep, timeout=1)(20000))
```

**Comment by autodataming** [comment]
> def limit(method, timeout):
>     """ Convert a Java method to asynchronous call with a specified timeout. """
>     def f(*args):
>         @jpype.JImplements('java.util.concurrent.Callable')
>         class g(object):
>             @jpype.JOverride
>             def call(self):
>                 method(*args)
>                 return "YES"
>         future = jpype.JClass("java.util.concurrent.FutureTask")(g())
>         jpype.JClass('java.lang.Thread')(future).start()
>         try:
>             return future.get(int(timeout*1000), jpype.JClass('java.util.concurrent.TimeUnit').MILLISECONDS)
>         except jpype.JClass('java.util.concurrent.TimeoutException') as ex:
>             future.cancel(True)
>             raise RuntimeError("canceled", ex)
>     return f
> 
> Thread = jpype.JClass('java.lang.Thread')
> print(limit(Thread.sleep, timeout=1)(200))
> print(limit(Thread.sleep, timeout=1)(20000))

Thank you for your help.
I runed your code. it report 
```
AttributeError: module 'jpype' has no attribute 'JImplements'
```
jpype.__version__   '0.6.3'

**Comment by Thrameos** [comment]
Not much help i can offer for version 0.6.3.   That version is rather out of date and contains a lot of bugs.

**Comment by autodataming** [comment]
Thank you for your help. I have updated the jpype to the version 0.7.2. It solved my problem by your solution.

by the way, for python35 conda environment, the high version of jpype is 0.6.3.
```py
conda install -c conda-forge jpype1
```

I use the pip to update the jpype
```py
python -m pip install  JPype1 
```

**Comment by autodataming** [comment]
for the case, it will report an error.

```py
rxnsmi ='BrB(Br)Br.O=[N+]([O-])c1cnc2[nH]nc(COCc3ccccc3)c2c1.O=C([O-])O.CCOC(C)=O>>O=[N+]([O-])c1cnc2[nH]nc(CO)c2c1'
result2 = limit(addmapbyRDT, timeout=1)(rxnsmi)
print("result2",result2)
```

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f99f20ae480, pid=9507, tid=0x00007f99fdd61740
#
# JRE version: OpenJDK Runtime Environment (8.0_152-b12) (build 1.8.0_152-release-1056-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.152-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [_jpype.cpython-35m-x86_64-linux-gnu.so+0x60480]  JPypeTracer::trace1(char const*)+0x1a0
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/zgong/jupyternotebook/hs_err_pid9507.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

but directly run the function,it will not report the above error.
```
addmapbyRDT(rxnsmi)
```

**Comment by Thrameos** [comment]
Please try to install from git directly.  I believe this bug was addressed already.

```
python -m pip install git+https://github.com/jpype-project/jpype.git
```

That should address the issue.   We will have a release with the fix included shortly.

**Comment by autodataming** [comment]
> 
> 
> Please try to install from git directly. I believe this bug was addressed already.
> 
> ```
> python -m pip install git+https://github.com/jpype-project/jpype.git
> ```
> 
> That should address the issue. We will have a release with the fix included shortly.

Thank you! It solved the above problem.  I try to use the Pool to speed up the process of calculation. But it failed.

```py
text = phase3csv.readlines()

from multiprocessing import Pool

results =[]
def task(line):
    idd,rxnsmi = line.strip().split(',')
    result2 = limit(addmapbyRDT, timeout=2)(rxnsmi)
    newline = "%s,%s,%s"%(idd,rxnsmi,result2)
    print(newline)

pool =Pool()
pool.map(task,text[1:100])
```
can you give me some help?

**Comment by Thrameos** [comment]
Please refer to the userguide under the section "Working with Multiprocessing".  Beyond that I have no specific guidance on using multiple processes.  I have not used pool.

https://jpype.readthedocs.io/en/latest/userguide.html
