### ISSUE TITLE
--disable-numpy not working in pip install?

### ISSUE THREAD

**Issue by slbayer** [jpype-project/jpype#671]
I'm trying to install jpype1 version 0.7.2 using pip in Python 3.7.3 on macOS 10.15.4. I don't want the dependency on NumPy, and I'm trying to install it, as the documentation suggests, as follows:

```
$ pip install --global-option='–-disable-numpy' jpype1
```
But I get an error ```invalid command name --disable-numpy```. I've downloaded a zip of the current master branch, and I can't find any mention of this option in the code. Is it even available anymore?

**Comment by Thrameos** [comment]
It has been removed.  We were using numpy to support buffer protocol transfers, but we now have an implementation that does not require numpy for that purpose.   Numpy was causing a lot of problems due to binary incompatibility. 

We will need to update the documentation.
