### ISSUE TITLE
Modification of __repr__

### ISSUE THREAD

**Issue by petrushy** [jpype-project/jpype#698]
Hi, testing jPype and looks rgood!

I am mostly using ipython/jupyter and the __repr__ string is then important as one is very interactive with the objects. Is there a way to change all __repr__ strings for objects, I can do it on a single class with JImplementationFor(classname) but would like to do it for all classes or a set of them? Adding a method like:

def __repr__(self):
        return f"<{self.getClass().getSimpleName()}: {self.toString()}>"

**Comment by Thrameos** [comment]
Let see what we are currently doing....

```
print("Class wrapper ", repr(jpype.JClass("java.lang.Object")))
print("Class instance ", repr(jpype.JClass("java.lang.Object").class_))
print("Object ", repr(jpype.JClass("java.lang.Object")()))
print("String ", repr(jpype.JClass("java.lang.String")("contents")))
print("List ", repr(jpype.JClass("java.util.ArrayList")()))
```

Gives:
```
Class wrapper  <java class 'java.lang.Object'>
Class instance  <jpype._jclass.java.lang.Class object at 0x7f4a7b2c29f0>
Object  <jpype._jclass.java.lang.Object object at 0x7f4a7b2c29f0>
String  'contents'
List  <jpype._jclass.java.util.ArrayList object at 0x7f4a60015090>
```

So it looks like we are missing repr on objects.  Hmm I though that was in place.  Oh well.

Here is the monkey patch to give the correct behavior.

```
# define a repr function
def _JObjectRepr(obj):
    return "<java object '%s'>"%type(obj).__name__
# Monkey patch the base class
import _jpype
_jpype._JObject.__repr__ = _JObjectRepr
```

which produces

```
Class wrapper  <java class 'java.lang.Object'>
Class instance  <java object 'java.lang.Class'>
Object  <java object 'java.lang.Object'>
String  'contents'
List  <java object 'java.util.ArrayList'>
```

The reason this works is all JPype classes are heap types so they can be modified as needed which is all that JImplementationFor is doing.

Does that work for you?

**Comment by petrushy** [comment]
Hi! It seems to work well to monkey-patch that way, great! 

In my case I prefer to have the toString as part of the repr, but in this way it is easily customized for the needs.

Many thanks!
