### ISSUE TITLE
Call a class that extends javax.swing

### ISSUE THREAD

**Issue by jeesang7** [jpype-project/jpype#730]
My question about JPackage and JFrame using jpype.
Is it able to support swing or awt on current jpype version ?
For example,
```
<test.java>
package com.gui;

import java.awt.*;
import javax.swing.*;

public class foo extends javax.swing.JFrame {
   ....
}
```

```
<test.py>
from jpype import *

def test
   startJVM()
   pkg = JPackage('com').gui
   testclass = pkg.foo
```

My testing above some code results nothing happen and without any output log.
So, I think that current jpype version is not support the javax.swing.JFrame package.
Any some opinion about jpype using javax.swing or JFrame ?

Thanks.

**Comment by Thrameos** [comment]
Thanks for the bug report.  I will need to investigate and get back to you.   As far as I know there is nothing specifically required to use JFrame.   However, you do need to spin up an event loop to service the events.   I don't have that recipe on hand, so I will have to do some research.

**Comment by Thrameos** [comment]
A simple hello world works fine with master.   (Though I have one warning about reference issues that I need to track down.)  This would not work in previous versions of JPype as the shutdown would terminate the gui prematurely.  In older versions of JPype, you would need to communicate the desire to shutdown using wait/notify on an object. 

```
import jpype
import jpype.imports

jpype.startJVM()
import java
import javax
from javax.swing import *

def createAndShowGUI():
    frame = JFrame("HelloWorldSwing")
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE)
    label = JLabel("Hello World")
    frame.getContentPane().add(label)
    frame.pack()
    frame.setVisible(True)

# Start an event loop thread to handling gui events
@jpype.JImplements(java.lang.Runnable)
class Launch:
    @jpype.JOverride
    def run(self):
        createAndShowGUI()
javax.swing.SwingUtilities.invokeLater(Launch())
```
