### ISSUE TITLE
How to use jpype on pyspark 2.4.0

### ISSUE THREAD

**Issue by JWenBin** [jpype-project/jpype#758]
First, I saw classpath in startJVM like this：
def startJVM(*args, **kwargs):
"""classpath (str,[str]): Set the classpath for the jvm.
        This will override any classpath supplied in the arguments
        list. A value of None will give no classpath to JVM.
   .......
"""

Second, I could use jpype locally like this:
[hadoop@ip-192-168-1-78 ~]$ pyspark --master local[2] --driver-memory 2G
Python 3.6.10 (default, Feb 10 2020, 19:55:14) 
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.4.0
      /_/

Using Python version 3.6.10 (default, Feb 10 2020 19:55:14)
SparkSession available as 'spark'.
>>> jarpath ='/home/hadoop/tmp/test-1.0.jar'
>>> import jpype
>>> jvmPath = jpype.getDefaultJVMPath()
>>> jpype.startJVM(jvmPath,"-ea", "-Djava.class.path=%s" % (jarpath))
/home/hadoop/.local/lib/python3.6/site-packages/jpype/_core.py:209: UserWarning: 
-------------------------------------------------------------------------------
Deprecated: convertStrings was not specified when starting the JVM. The default
behavior in JPype will be False starting in JPype 0.8. The recommended setting
for new code is convertStrings=False.  The legacy value of True was assumed for
this session. If you are a user of an application that reported this warning,
please file a ticket with the developer.
-------------------------------------------------------------------------------

  """)
>>> javaClass = jpype.JClass("jutil.SerializeUtil")
>>>

Third, I don't know how to set classpath while my .jar file is on HDFS or S3, I tried like this  but failed：
[hadoop@ip-192-168-1-78 ~]$ pyspark --master local[2] --driver-memory 2G
Python 3.6.10 (default, Feb 10 2020, 19:55:14) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.4.0
      /_/

Using Python version 3.6.10 (default, Feb 10 2020 19:55:14)
SparkSession available as 'spark'.
>>> import jpype
>>> jarpath = 's3://test/test-1.0.jar'
>>> jvmPath = jpype.getDefaultJVMPath()
>>> jpype.startJVM(jvmPath,"-ea", "-Djava.class.path=%s" % (jarpath))
/home/hadoop/.local/lib/python3.6/site-packages/jpype/_core.py:209: UserWarning: 
-------------------------------------------------------------------------------
Deprecated: convertStrings was not specified when starting the JVM. The default
behavior in JPype will be False starting in JPype 0.8. The recommended setting
for new code is convertStrings=False.  The legacy value of True was assumed for
this session. If you are a user of an application that reported this warning,
please file a ticket with the developer.
-------------------------------------------------------------------------------

  """)
>>> javaClass = jpype.JClass("jutil.SerializeUtil")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hadoop/.local/lib/python3.6/site-packages/jpype/_jclass.py", line 96, in __new__
    return _jpype._getClass(jc)
TypeError: Class jutil.SerializeUtil is not found

Could you tell me how to use  jpype on pyspark 2.4.0？Thanks!

**Comment by Thrameos** [comment]
It appears to have failed finding ``jutil.SerializeUtil``.  I am not aware of such a class,   It seems like it is from ``jarpath = 's3://test/test-1.0.jar'``

From the error messages it appears the developer has not updated this since the old 0.6.3 days.  

So first step find out if test-1.0.jar is in place and loadable.   I unfortunately have no idea what ``s3:`` means there

The line i would expect for the startup give then dialog is
```
import jpype
jpype.startJVM("-ea", classpath='s3://test/test-1.0.jar', convertStrings=False)
```
