### ISSUE TITLE
Issue installing on Alpine Linux 0.7.3 -> current (0.7.5)

### ISSUE THREAD

**Issue by dm-ion** [jpype-project/jpype#759]
**High level description:**
JPype1 (0.7.3 -> current) is unable to install correctly on Alpine Linux

**Steps to reproduce:**
1. docker run --rm -it --entrypoint=sh alpine:latest
2. apk add python3-dev gcc build-base
3. pip3 install JPype1

**Expected Result**
- Installation Success 

**Actual Result**
- Install fails due to alpine's musl libc not including mallinfo (which is used in your jp_gc.cpp). mallinfo is apparently a GNU glibc addition and thus not in alpine's implementation.

**Comment by Thrameos** [comment]
Thanks for the bug report.   Do you know of a suitable replacement for mallinfo on that system?  This particular code is for triggering the Java GC whenever the Python has exceeded a certain memory allocation (implying java is holding resources).   Unfortunately, Python does not have any internal memory tracking so I have to fall back to system tools.  

Also how do I recognize if the installation is alpine so that I can trigger an alternative.

**Comment by dm-ion** [comment]
Unfortunately I don't know enough about this off the top of my head to really comment. It looks like a fairly common problem that lots of different libraries people have run into.

A search of mallinfo alpine turns up quite a few relevant results.

I'm not really sure when I'll have time to dig any deeper, just figured I would open the bug report as others could be effected.

Thanks for the quick response!!

**Comment by Thrameos** [comment]
I did some poking as well.  The most common response is "just comment it out as it is just for auditing information."  

Unfortunately, that is not the case with JPype.    I guess the long term solution would be to try to twist the arms on Python folks to see about adding something that helps in collecting statistics on the total memory that Python has out.   They have trace facility but they delete the memory before they call tracer so there is no way to find out how big the freed memory was.   So I could track how much was allocated and not how much was being freed which wasn't very useful for coupling garbage collectors.   

So lets start with the short term solution.  If you can research some DEFINE that is unique to that system that I can test on then I can add logic to disable the GC linker on that system.   We ran without it for years so it would be a fairly minor defect.

**Comment by dm-ion** [comment]
That seems like a reasonable approach, sounds good.

**Comment by Thrameos** [comment]
@dm-ion I have create a PR to test your issue.  I don't know enough to get a working JDK on alpine, but i was able to get everything to compile.  Please give it a test so that I can merge it.

**Comment by dm-ion** [comment]
Oh dang, awesome! I think I should have time to give it a test in the next couple of days.

FYI to get a working JDK it is sufficient to type apk --update add openjdk8

**Comment by dm-ion** [comment]
Hey @Thrameos this compiles and runs on alpine no problem.

I haven't reviewed your code at all (and I'm not sure I'd have the time to do it justice), so not sure if it actually doesn't want you want.

**Steps**:
1. docker run --rm -it --entrypoint=sh alpine:latest
2. apk add python3-dev gcc build-base py3-pip openjdk8
3. pip3 install --upgrade pip setuptools
4. Pull source, apply patch from merge request
5. python3 setup.py build
6. python3 setup.py install
7. Run python apps that require JPype1 to function (In my case JayDeBeApi)

**Comment by Thrameos** [comment]
Unfortunately my docker image does not appear to be working while following your detailed instructions.  I always fail when building as it can't find javac.  So I set JAVA_HOME to the openjdk8 installation, but then I get the following:
```
/io # python3 test.py
Error occurred during initialization of VM
Unable to load native library: Error loading shared library libjvm.so: No such file or directory (needed by /usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/libjava.so)
```

But given that your image is working, there is a specific script required to test this issue.   Here is an example I ran on another linux machine (not alpine) run from the root directory of JPype after a build in place.

```
$ PYTHONPATH=. python project/utility/testMemoryExh.py

created= 1   destroyed= 0   delta= 1   current= 1895235584   min= 1408544256   max= 1895168000   triggered= 2
created= 1001   destroyed= 0   delta= 1001   current= 1898086400   min= 1408544256   max= 1897953280   triggered= 2
created= 2001   destroyed= 0   delta= 2001   current= 1900901376   min= 1408544256   max= 1900796928   triggered= 2
created= 3001   destroyed= 0   delta= 3001   current= 1903692800   min= 1408544256   max= 1903625216   triggered= 2
created= 4001   destroyed= 0   delta= 4001   current= 1906484224   min= 1408544256   max= 1906416640   triggered= 2
created= 5001   destroyed= 545   delta= 4456   current= 1908474880   min= 1408544256   max= 1908333568   triggered= 2
created= 6001   destroyed= 4675   delta= 1326   current= 1908081664   min= 1408544256   max= 1908474880   triggered= 2
created= 7001   destroyed= 4675   delta= 2326   current= 1908081664   min= 1408544256   max= 1908474880   triggered= 2
created= 8001   destroyed= 4675   delta= 3326   current= 1908212736   min= 1408544256   max= 1908474880   triggered= 2
created= 9001   destroyed= 4675   delta= 4326   current= 1908409344   min= 1408544256   max= 1908474880   triggered= 2
created= 10001   destroyed= 4675   delta= 5326   current= 1910178816   min= 1408544256   max= 1910043648   triggered= 2
created= 11001   destroyed= 4675   delta= 6326   current= 1912973312   min= 1408544256   max= 1912838144   triggered= 2
created= 12001   destroyed= 4686   delta= 7315   current= 1915748352   min= 1662094592   max= 1915644928   triggered= 3
created= 13001   destroyed= 11947   delta= 1054   current= 1915158528   min= 1662094592   max= 1915748352   triggered= 3
created= 14001   destroyed= 11947   delta= 2054   current= 1915158528   min= 1662094592   max= 1915748352   triggered= 3
```

This important point here is the ``destroyed`` column.  If GC is running properly then it will trigger objects to be destroyed at semi-regular intervals.  If it fails then Python will exhaust memory as Java is holding pointers to Python memory but because Java only is counting its memory towards the memory total and the pointers are small.

If you can perform that test successfully then it is working correctly.

**Comment by dm-ion** [comment]
Hah oops I forgot that I added java home and modified the path manually...

I can give your test a try

**Comment by dm-ion** [comment]
Alright so I revised my steps above (I had some things in my base alpine image I was using) and then ran the following:

pip3 install numpy jedi pytest
PYTHONPATH=. python3 project/utility/testMemoryExh.py

and this doesn't work to launch the tests. I get **TypeError: Class jpype.common.Fixture is not found**

I'm sure I'm missing something really obvious to get this test running. I can probably debug it / go through code / doc to see how to do it tomorrow, unless you're gracious enough to tell me what I'm doing wrong :D

**Comment by Thrameos** [comment]
Sorry.  Before the test can be run the harness needs to be build.  I thought that you had gotten the test harness built but I see you missed that step.

To create the harness use:
```
   python3 setup.py test_java
```

It should create test/classes with the harness classes.   You may need to adjust the build script (setupext/test_java.py) as I have not tested it on your configuration.

**Comment by dm-ion** [comment]
created= 1   destroyed= 0   delta= 1   current= 2552553472   min= 1269960704   max= 2539921408   triggered= 1
created= 1001   destroyed= 11   delta= 990   current= 2555248640   min= 1911257088   max= 2555155456   triggered= 2
created= 2001   destroyed= 11   delta= 1990   current= 2558061568   min= 1911257088   max= 2557966336   triggered= 2
created= 3001   destroyed= 76   delta= 2925   current= 2560713728   min= 2398153216   max= 2560529408   triggered= 4
created= 4001   destroyed= 2924   delta= 1077   current= 2560517120   min= 2398153216   max= 2560529408   triggered= 4
created= 5001   destroyed= 2924   delta= 2077   current= 2560582656   min= 2398153216   max= 2560582656   triggered= 4
created= 6001   destroyed= 3231   delta= 2770   current= 2561665024   min= 2479557888   max= 2561665024   triggered= 5
created= 7001   destroyed= 5747   delta= 1254   current= 2561665024   min= 2479557888   max= 2561665024   triggered= 5
created= 8001   destroyed= 5747   delta= 2254   current= 2561665024   min= 2479557888   max= 2561665024   triggered= 5
created= 9001   destroyed= 5747   delta= 3254   current= 2561730560   min= 2479557888   max= 2561730560   triggered= 5
created= 10001   destroyed= 5747   delta= 4254   current= 2563696640   min= 2479557888   max= 2563567616   triggered= 5
created= 11001   destroyed= 5747   delta= 5254   current= 2566536192   min= 2479557888   max= 2566338560   triggered= 5
created= 12001   destroyed= 5747   delta= 6254   current= 2569313280   min= 2479557888   max= 2569181184   triggered= 5
created= 13001   destroyed= 5747   delta= 7254   current= 2572099584   min= 2479557888   max= 2571967488   triggered= 5
created= 14001   destroyed= 5747   delta= 8254   current= 2574900224   min= 2479557888   max= 2574767104   triggered= 5
created= 15001   destroyed= 5747   delta= 9254   current= 2577713152   min= 2479557888   max= 2577579008   triggered= 5
created= 16001   destroyed= 5747   delta= 10254   current= 2580526080   min= 2479557888   max= 2580389888   triggered= 5
created= 17001   destroyed= 6579   delta= 10422   current= 2581675008   min= 2530530432   max= 2581622784   triggered= 6
created= 18001   destroyed= 16349   delta= 1652   current= 2580691968   min= 2530530432   max= 2581622784   triggered= 6
created= 19001   destroyed= 16349   delta= 2652   current= 2580691968   min= 2530530432   max= 2581622784   triggered= 6
created= 20001   destroyed= 16349   delta= 3652   current= 2580691968   min= 2530530432   max= 2581622784   triggered= 6
created= 21001   destroyed= 16349   delta= 4652   current= 2580691968   min= 2530530432   max= 2581622784   triggered= 6
created= 22001   destroyed= 16349   delta= 5652   current= 2580691968   min= 2530530432   max= 2581622784   triggered= 6
created= 23001   destroyed= 16349   delta= 6652   current= 2580888576   min= 2530530432   max= 2581622784   triggered= 6
created= 24001   destroyed= 16349   delta= 7652   current= 2581085184   min= 2530530432   max= 2581622784   triggered= 6
created= 25001   destroyed= 16349   delta= 8652   current= 2581281792   min= 2530530432   max= 2581622784   triggered= 6
created= 26001   destroyed= 16349   delta= 9652   current= 2581478400   min= 2530530432   max= 2581622784   triggered= 6
created= 27001   destroyed= 16349   delta= 10652   current= 2581675008   min= 2530530432   max= 2581675008   triggered= 6
created= 28001   destroyed= 17544   delta= 10457   current= 2582393856   min= 2569123872   max= 2582393856   triggered= 8
created= 29001   destroyed= 27192   delta= 1809   current= 2581804032   min= 2569123872   max= 2582393856   triggered= 8
created= 30001   destroyed= 27192   delta= 2809   current= 2581804032   min= 2569123872   max= 2582393856   triggered= 8
created= 31001   destroyed= 27192   delta= 3809   current= 2581804032   min= 2569123872   max= 2582393856   triggered= 8
created= 32001   destroyed= 27192   delta= 4809   current= 2581804032   min= 2569123872   max= 2582393856   triggered= 8
created= 33001   destroyed= 27192   delta= 5809   current= 2581804032   min= 2569123872   max= 2582393856   triggered= 8
created= 34001   destroyed= 27192   delta= 6809   current= 2581804032   min= 2569123872   max= 2582393856   triggered= 8
created= 35001   destroyed= 27192   delta= 7809   current= 2581804032   min= 2569123872   max= 2582393856   triggered= 8
created= 36001   destroyed= 27192   delta= 8809   current= 2582000640   min= 2569123872   max= 2582393856   triggered= 8
created= 37001   destroyed= 27192   delta= 9809   current= 2582197248   min= 2569123872   max= 2582393856   triggered= 8
created= 38001   destroyed= 27192   delta= 10809   current= 2582393856   min= 2569123872   max= 2582393856   triggered= 8
created= 39001   destroyed= 27192   delta= 11809   current= 2584936448   min= 2569123872   max= 2584802304   triggered= 8

**Comment by Thrameos** [comment]
Looks good to me.  I will start the review process to have it included in the next release.  Thanks again for the bug report taking the time to follow through.

**Comment by dm-ion** [comment]
No worries, glad I could help. Thanks for doing 90% of the work! :D
