### ISSUE TITLE
JPickler example doesn't work.

### ISSUE THREAD

**Issue by baiyin** [jpype-project/jpype#772]
below is the example copied from [api reference doc](https://jpype.readthedocs.io/en/latest/api.html#jpype-pickle-module) .

```
myobj = jpype.JClass('java.util.ArrayList')
myobj.add("test")

from jpype.pickle import JPickler, JUnpickler
with open("test.pic", "wb") as fd:
  JPickler(fd).dump(myobj)

with open("test.pic", "rb") as fd:
  newobj = JUnpickler.load(fd)
```

there were some errors when I reimplement this example.
first, there was an error in line 2. 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-fa7672e2920a> in <module>
      1 myobj = jpype.JClass('java.util.ArrayList')
----> 2 myobj.add('test')

TypeError: No matching overloads found for java.util.ArrayList.add(str), options are:
	public void java.util.ArrayList.add(int,java.lang.Object)
	public boolean java.util.ArrayList.add(java.lang.Object)
```
which seems that I need to initialize the array like 
`List<String> myobj = new ArrayList<>();` instead of List myojb = new ArrayList(); But I don't know how to express it using JPype. 

I deleted the line 2 and retry the example, then it reported another error.
```
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
<ipython-input-7-86da8adfd3a4> in <module>
      1 with open('test.pic', 'wb') as fd:
----> 2     JPickler(fd).dump(myobj)

PicklingError: Can't pickle <java class 'java.util.ArrayList'>: attribute lookup java.util.ArrayList on jpype._jclass failed
```

the versions of my environment were JPype 0.7.5 and Python 3.6.10

**Comment by Thrameos** [comment]
Thanks for the bug report.   This worked for me...
```
import jpype
jpype.startJVM()
myobj = jpype.JClass('java.util.ArrayList')()    #   myobj = new java.util.ArrayList()
myobj.add("test")
from jpype.pickle import JPickler, JUnpickler
with open("test.pic", "wb") as fd:
      JPickler(fd).dump(myobj)
with open("test.pic", "rb") as fd:
      newobj = JUnpickler(fd).load()
```

There were two typos in the example.   There are more examples of this in action in test/jpypetest/test_pickle.py.  Please take a few minutes to look over the quick start guide.  It will help you see how to convert from Java to Python.

**Comment by baiyin** [comment]
@Thrameos thanks very much, it worked after I fixed the typos in the example as you mentioned.
