### ISSUE TITLE
Import from Java package that has no subdirectories causes import error

### ISSUE THREAD

**Issue by IowU** [jpype-project/jpype#781]
Hello,
I'm using Jpype to call methods from a Java library (.jar). The library has of course packages in it, but one type is causing me import problems. 

There are some packages with the following structure:

- com
  - sun
    -Util.class

(inside the **com** directory there is the **sun** directory which contains the **Util.class**). In this case I can successfully import the class (from python)  by using

`from com.sun import Util`

But in case I have the following structure 
- com.google
  - SoftwareUtility.class

( so there is a **SINGLE** package named **com.google** that contains the class; the google subdirectory doesn't exist) I get an import error if I do

`from com.google import SoftwareUtility`

`ModuleNotFoundError: No module named 'com'`

How can I solve this?
Thanks

**Comment by Thrameos** [comment]
Java requires packages to be in directories with a separate directory for each level.   Barring creating your own classloader, this organizational structure is required.  You will need to either move the com.google to com/google or built all of the class files into a jar file so they can all be picked up at once.

See https://docs.oracle.com/javase/tutorial/java/package/managingfiles.html

**Comment by IowU** [comment]
> 
> 
> Java requires packages to be in directories with a separate directory for each level. Barring creating your own classloader, this organizational structure is required. You will need to either move the com.google to com/google or built all of the class files into a jar file so they can all be picked up at once.
> 
> See https://docs.oracle.com/javase/tutorial/java/package/managingfiles.html

Thank you for the reply. I'll see what I can do
