### ISSUE TITLE
TypeError when importing JPype in Python 3.8.4

### ISSUE THREAD

**Issue by John-Hennig** [jpype-project/jpype#787]
With the latest bug-fix release for Python, version 3.8.4 published two days ago, I get the following error when importing JPype on Window 10:

```pycon
$ python
Python 3.8.4 (tags/v3.8.4:dfa645a, Jul 13 2020, 16:46:45) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import jpype
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\temp\Py384\Python\lib\site-packages\jpype\__init__.py", line 20, in <module>
    from ._core import *
  File "D:\temp\Py384\Python\lib\site-packages\jpype\_core.py", line 20, in <module>
    from . import types as _jtypes
  File "D:\temp\Py384\Python\lib\site-packages\jpype\types.py", line 38, in <module>
    from ._jarray import *
  File "D:\temp\Py384\Python\lib\site-packages\jpype\_jarray.py", line 213, in <module>
    _jcustomizer._applyCustomizerPost(_jpype._JArray, _JArrayProto)
  File "D:\temp\Py384\Python\lib\site-packages\jpype\_jcustomizer.py", line 166, in _applyCustomizerPost
    _applyCustomizerImpl(cls.__dict__, proto, sticky,
  File "D:\temp\Py384\Python\lib\site-packages\jpype\_jcustomizer.py", line 148, in _applyCustomizerImpl
    setter(p, v)
  File "D:\temp\Py384\Python\lib\site-packages\jpype\_jcustomizer.py", line 167, in <lambda>
    lambda p, v: type.__setattr__(cls, p, v))
TypeError: can't apply this __setattr__ to _jpype._JClass object
```

This occurs with JPype 0.7.5, the release currently available on PyPI, as well as the latest release 1.0.0, installed directly from the wheel as provided here on GitHub.

No such error occurs on the same machine with Python 3.8.3, on an equally clean install (no other packages) of JPype 0.7.5 or 1.0.0. Same for Python 3.7.8, tested on two other machines running Windows 7. So this seems to be specific to Python 3.8.4 and, possibly, Windows.

Is this error reproducible?

**Comment by Thrameos** [comment]
I have not seen this particular error though it seems likely that it is the result of a problem in Python.   _jpype._JClass is definitely derived from type as it is a metaclass.  Thus, the base type setattr method should apply (we are deliberately bypassing the class implementation version as it enforces closed class behaviors.)    It seems like they must have somehow closed that path off.   

I will need to replicate it to see if I can find a work around.

**Comment by Thrameos** [comment]
Python 3.8.4 is does not really seem like a bug fix release.  They changed multiple behaviors in ways that will be challenging to work around.  Real bummer that this was discovered just after the JPype release, but that is life.

**Comment by Thrameos** [comment]
Okay I can confirm the issue on Linux.  The issue appears to be that they rewrote the "hackcheck" so that it now is catching the JPype customizer code.

Diff 3.8.3 to 3.8.4
```
static int
 hackcheck(PyObject *self, setattrofunc func, const char *what)
 {
     PyTypeObject *type = Py_TYPE(self);
-    while (type && type->tp_flags & Py_TPFLAGS_HEAPTYPE)
-        type = type->tp_base;
-    /* If type is NULL now, this is a really weird type.
-       In the spirit of backwards compatibility (?), just shut up. */
-    if (type && type->tp_setattro != func) {
-        PyErr_Format(PyExc_TypeError,
-                     "can't apply this %s to %s object",
-                     what,
-                     type->tp_name);
-        return 0;
+    PyObject *mro = type->tp_mro;
+    if (!mro) {
+        /* Probably ok not to check the call in this case. */
+        return 1;
+    }
+    assert(PyTuple_Check(mro));
+    Py_ssize_t i, n;
+    n = PyTuple_GET_SIZE(mro);
+    for (i = 0; i < n; i++) {
+        PyTypeObject *base = (PyTypeObject*) PyTuple_GET_ITEM(mro, i);
+        if (base->tp_setattro == func) {
+            /* 'func' is the earliest non-Python implementation in the MRO. */
```

In the old version they skip all HeapType objects to check to see if the type setattr slot is valid.  All JPype types are HeapType so no problem everything works.  After the rewrite it checks the mro regardless of whether it is a heap type or not.  Thus, we get the class closed setattr as the first valid setattr.  That doesn't match the type one so no go.  

This was challenging to work around as all paths that I can access from within Python will likely hit this hackcheck code.  Thus the best I can do is give an alternative method to setattr which the customizer can use to perform the class customization.   This should be workable but that depends where the hack check is applied.
