### ISSUE TITLE
Recent upgrade from 0.7.5 to 1.0.1 raise exception at runtime

### ISSUE THREAD

**Issue by ikus060** [jpype-project/jpype#796]
I'm using jpype trought JayDeBeApi.
At runtime, when executing the python script, it raise an exception.

```
jpype.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PySlice_Unpack)
```
This is on Debian Stretch 64bits with `java-8-openjdk-amd64` version `8u252-b09-1~deb9u1` with python3

**Comment by Thrameos** [comment]
That is odd.   I would check if the version of the wheel matches the Python version.  PySlice_Unpack is a Python API symbol.   Please send the full Python version info and I will see about fixing it.

**Comment by ikus060** [comment]
I can reproduce the problem rather easily from a docker image I'm using.
```
ikus060@ikus060-laptop:~$ docker run -it -v `pwd`:/build ikus060/docker-debian-py2-py3:stretch
root@9ac51b93120f:/# 
root@9ac51b93120f:/# 
root@9ac51b93120f:/# pip install jaydebeapi
Collecting jaydebeapi
  Downloading JayDeBeApi-1.2.3-py3-none-any.whl (26 kB)
Collecting JPype1; python_version > "2.7" and platform_python_implementation != "Jython"
  Downloading JPype1-1.0.1-cp35-cp35m-manylinux2010_x86_64.whl (3.8 MB)
     |████████████████████████████████| 3.8 MB 3.6 MB/s 
Collecting typing-extensions; python_version < "3.8"
  Downloading typing_extensions-3.7.4.2-py3-none-any.whl (22 kB)
Installing collected packages: typing-extensions, JPype1, jaydebeapi
Successfully installed JPype1-1.0.1 jaydebeapi-1.2.3 typing-extensions-3.7.4.2
WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
root@9ac51b93120f:/# 
root@9ac51b93120f:/# 
root@9ac51b93120f:/# python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jaydebeapi
>>> jaydebeapi.connect("org.h2.Driver", "jdbc:h2:%s;MV_STORE=FALSE;IFEXISTS=TRUE")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/jaydebeapi/__init__.py", line 412, in connect
    jconn = _jdbc_connect(jclassname, url, driver_args, jars, libs)
  File "/usr/local/lib/python3.5/dist-packages/jaydebeapi/__init__.py", line 168, in _jdbc_connect_jpype
    import jpype
  File "/usr/local/lib/python3.5/dist-packages/jpype/__init__.py", line 18, in <module>
    import _jpype
ImportError: /usr/local/lib/python3.5/dist-packages/_jpype.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PySlice_Unpack
```

**Comment by Thrameos** [comment]
Thanks for the info.  The logs show this to be Python 3.5  which is in the test matrix, so it should be failing.  I will have to see if I can figure out why that symbol is missing (or patch around it.)

**Comment by ikus060** [comment]
Thanks alot for this quick response. Meanwhile, I revert back to 0.7.5

**Comment by Thrameos** [comment]
Looks like some problem in the build process.  Python 3.6 introduced PySlice_Unpack so it has no business being called in a 3.5 release.  But we are using a 3.5 manylinux build pattern that hasn't changed since 0.7.5.   So the problem has to be coming from the manylinux build environment.  It may take me a few days to sort this one out I will have to replicate the release chain.

**Comment by Thrameos** [comment]
I found the bug and will issue a patch shortly.   Appears that the Python 3.5 in the build system has a later patch release of 3.5 allowing for code that should have been caught as a compiler error to make it through.

**Comment by Thrameos** [comment]
Your issue has been addressed and will be corrected in the next patch release.  Thanks for the bug report.

**Comment by ikus060** [comment]
Very effective !
Thanks alot !
