### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by keithsun80** [jpype-project/jpype#81]
i found a bug.

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f8968afe1b6, pid=18623, tid=140228174546752

 JRE version: OpenJDK Runtime Environment (7.0_55-b14) (build 1.7.0_55-b14)
 Java VM: OpenJDK 64-Bit Server VM (24.51-b03 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [_jpype.so+0x3e1b6]  JPJavaEnv::CallVoidMethod(_jobject_, _jmethodID_)+0x26

 Core dump written. Default location: /home/keith/wiwide/project/system/branches/RSA/WiwideOP/core or core.18623

 An error report file with more information is saved as:
 /home/keith/wiwide/project/system/branches/RSA/WiwideOP/hs_err_pid18623.log

 If you would like to submit a bug report, please include
 instructions on how to reproduce the bug and visit:
   http://icedtea.classpath.org/bugzilla

and code in below

```
# encoding=utf8
   2 import jpype
   3 import settings
   4 import time
   5 
   6 CLASS_PATH = "%s/authapi-8.5.jar:%s/commons-logging-1.1.1.jar:%s/cryptoj-6.1.jar:%s/log4j-1.2.12rsa-1.jar:%s/xmlsec-1.5.5.jar" % (("%s/lib
   7 
   8 if __name__ == "__main__":
   9     if not jpype.isJVMStarted():
  10         jpype.startJVM(jpype.getDefaultJVMPath(), "-Djava.class.path=%s" % CLASS_PATH)
  11         print "first start jvm"
  12     jpype.shutdownJVM()
  13     time.sleep(2)
  14     jpype.shutdownJVM()
  15     AuthSessionFactory = jpype.JClass("com.rsa.authagent.authapi.AuthSessionFactory")
  16     if not jpype.isJVMStarted():
  17         jpype.startJVM(jpype.getDefaultJVMPath(), "-Djava.class.path=%s" % CLASS_PATH)
  18         print "second start jvm"
  19     jpype.shutdownJVM()

```

first time to use it , is okay ! but when i use it again , JVM throw a Exception

so how can i fix it ! 

help me plz, this is very important things

system and java information in below.

java version "1.7.0_55"
OpenJDK Runtime Environment (IcedTea 2.4.7) (7u55-2.4.7-1ubuntu1)
OpenJDK 64-Bit Server VM (build 24.51-b03, mixed mode)

**Comment by lbenharz** [comment]
Hi Keithsun,

Please could you share this jar file : authapi-8.5.jar
I need it for my java project to do the authtication.

Thanks if you cloud do this
Lazhar
