### ISSUE TITLE
Cannot start JVM

### ISSUE THREAD

**Issue by toprakfirat** [jpype-project/jpype#837]
Even though I set up the correct paths it says "RuntimeError: Unable to start JVM". I downloaded MAC OSX version of Java SE DK 8.

**Comment by Thrameos** [comment]
Unfortunately, without some further diagnostics I can't be much assistance.

What version of JPype?
What is the setting of JAVA_HOME?
What are the contents of directory where you pointed JAVA_HOME?
What is the output of getDefaultJVMPath() when called prior to starting the JVM?
What is the integer size of the JVM and Python (32 or 64)?
