### ISSUE TITLE
Release timeline for v1.0.3 / v1.1.0

### ISSUE THREAD

**Issue by pelson** [jpype-project/jpype#853]
It looks like there has been some great progress since v1.0.2 (https://github.com/jpype-project/jpype/compare/v1.0.2...master). Indeed, at this point, I'm excited to say that, for the libraries that I support, master is better than any release that has been made of JPype to date (it properly does JVM cleanup *and* it doesn't core-dump! :partying_face:).

It looks like there hasn't been an effort to maintain a patch version branch for v1.0.x, which suggests the intention is to go straight for ``v1.1.0``, though it also looks like some of the work that has been merged isn't yet finished (the android stuff?).

All of this leads me to ask the question - is master in a state where it could be released, and if not, is the [v1.1.0 milestone](https://github.com/jpype-project/jpype/milestone/10) reflective of what is necessary for the release, or just the wishlist?

I'd love to be able to drop support in my libraries for JPype v0.x, but at this point there isn't a *release* of v1.x which I can reliably use (FWIW I systematically test against master and am very happy with it).

**Comment by Thrameos** [comment]
I don’t think we are that far from being able to release a 1.1.   There are a few PRs on the queue I would like to see in, but we could cut a 1.1 release by next week.

**Comment by pelson** [comment]
Ok, let's remove this in favour of #861
