### ISSUE TITLE
Is it possible to map Python str to Java String instead of reporting Ambiguous overloads found for char[]

### ISSUE THREAD

**Issue by hankcs** [jpype-project/jpype#854]
Hi jpype team,

I have a Java method supporting both String and char[], it worked perfectly with jpype==0.7.0. However, with the lastest version, the following exception occurs:

```
TypeError: Ambiguous overloads found for com.hankcs.hanlp.seg.Segment.seg(str) between:
	public java.util.List com.hankcs.hanlp.seg.Segment.seg(char[])
	public java.util.List com.hankcs.hanlp.seg.Segment.seg(java.lang.String)
```

I'm wondering if there is an option to force python str to be mapped to java.lang.String regardless of the exsistance of a char[] overload.

Thanks.

**Comment by Thrameos** [comment]
Unfortunately customization at that level is not currently supported using the type system.   If two methods have valid conversions then both will be matched.   Currently the matcher has only 4 levels of matching:   Exact, Implicit, Explicit and None.   However it is possible for one method to hide another method,  currently this is done only if if there is inheritance when creating the tables of order.   Each method in the dispatch has a list of methods which have precedence over each other on the basis of Java rules.   


So how to resolve this issue....  I would recommend using the method customizers.   For example

```
@JImplementationFor
class SegmentProto(object):
    @JOverride
    def seg(self, arg):
        if (instanceof(arg, str)):
            return self._seg(JString(arg))
        return self._seg(arg)
```

I know this a bit cumbersome if you have many classes with problematic methods, but it does provide a workable solution for certain cases.   Here we are reimplementing the seg method (which renames the method ``_seg``) and then checking the type.  If the type is str then cast it to the preferred overload, else let it be resolved normally.

I can add some customization options into the process, but then it would impose new rules on the process which potentially can lead to unexpected results.   For example if I universally added Objects over Arrays then this sort of ambiguity would be resolved, but would it work universally in all cases.   I could also add mechanisms that allow one to get the list of methods that are in a dispatch and manually set one method to have precedence.  But that means provided a lot of reflection capabilities.  Thus the difficulty that it will impose a lot of interactions which I can't easily achieve until I have better integrated Python into the Java framework.

**Comment by hankcs** [comment]
Thank you so much @Thrameos . I got the idea. Fortunately only a couple of methods need to be disambiguated.
