### ISSUE TITLE
JPype 1.0.2 - ModuleNotFoundError: No module named 'jpype.dbapi2' ?

### ISSUE THREAD

**Issue by gdubya** [jpype-project/jpype#859]
I'm trying to use a jdbc driver with [sqlalchemy-drill](https://github.com/JohnOmernik/sqlalchemy-drill). I have jpype 1.0.2 installed, however when i try to create a connection the program throws a ModuleNotFoundError:
```
... snip...
  File "/path/to/project/venv/lib/python3.8/site-packages/sqlalchemy_drill/jdbc.py", line 25, in <module>
    import jpype.dbapi2 as dbapi2
ModuleNotFoundError: No module named 'jpype.dbapi2' 
```

It looks like the dbapi2 folder isn't part of the 1.0.2 distribution?

**Comment by Thrameos** [comment]
Dbapi2 is targeted for release in 1.1.

**Comment by gdubya** [comment]
Ah ok. I tried pip installing from github but that's a bit more complicated than a normal pip install. So, looking forwards to [the 1.1 release](853)! 😄 🤞 👍
