### ISSUE TITLE
Failed to load multiple jar packages

### ISSUE THREAD

**Issue by sanderchen** [jpype-project/jpype#862]
jar_path1 = './lib/A.jar'
jar_path2 = './lib/B.jar'
jar_path = "-Djava.class.path=%s;%s"%(jar_path1,jar_path2)

TypeError: Class com.XXX.XXX.XXX is not found

How can I further position？Thanks！！！

**Comment by sanderchen** [comment]
Confirm that the class path is correct

**Comment by sanderchen** [comment]
Additional informations：

jar_path1 = './lib/gmssl/security-0.0.1-SNAPSHOT-jar-with-dependencies.jar'
jar_path2 = './lib/gmssl/welink-java-sdk.jar'
jar_path = "-Djava.class.path=%s;%s"%(jar_path1,jar_path2)

jvmpath = jpype.getDefaultJVMPath()
if not jpype.isJVMStarted():
	jpype.startJVM(jvmpath, "-ea", jar_path)


TypeError: Class com.XXX.XXX.XXX is not found

**Comment by Thrameos** [comment]
Did you try 
```
jpype.startJVM('-ea', classpath=['path1', 'path2'])
print(jpype.java.lang.System.getProperty('java.class.path'))
```

**Comment by sanderchen** [comment]
it’s work! thanks！

jpype.startJVM('-ea', classpath=['path1', 'path2'])
print(jpype.java.lang.System.getProperty('java.class.path'))

**Comment by Thrameos** [comment]
The old method that required people to formulate the java.class.path manually was too error prone and resulted in code that did not work across platforms (windows/linux) so I added the list form keyword which is much safer.
