### ISSUE TITLE
Implement a more userfriendly API

### ISSUE THREAD

**Issue by baztian** [jpype-project/jpype#88]
We should provide a more userfriendly API to JPype. Currently users often report more or less the same kind of errors regarding classpath setup, jvm startup/shutdown and the like.

I started to write a [Whitepaper for a userfriendly JPype API in the wiki](../wiki/UserfriendlyApiWhitepaper) (very early draft). Feel free to add your comments or enhance it as you like.

**Comment by Thrameos** [comment]
The problem with using `with` to control scope of jpype is that would only work in the `__main__`.  It is better not make jpype so different from other python packages.  We have a pull to simplify the start up procedure, so I think this enhancement should be closed for now.
