### ISSUE TITLE
JPype1 1.1.2 - win_amd64.whl - cp39 missing -

### ISSUE THREAD

**Issue by MarcoDeckers** [jpype-project/jpype#881]
The Python 3.9 Windows wheel-file 'JPype1-1.1.2-cp39-cp39-win_amd64.whl - cp39' is missing from the download-section.

-----

Question send to cooperate@originell.org (date: 06.11.2020)

Hello,
 
I have a question about JPype1 1.1.2.
 
I’m working on a offline environment (so pip install is not possible) - using Windows10 (64bit) with programming language Python 3.9 - and need JPype1 to install JayDeBeApi (bridge from JDBC database drivers to Python DB-API).
I tried downloading the wheel-file (JPype1-1.1.2-cp38-cp38-win_amd64.whl (1.6 MB) - cp38) and I was hoping I could install this cp38 release, but unfortunately (but was to be expected) I received an error:
 
ERROR: JPype1-1.1.2-cp38-cp38-win_amd64.whl is not a supported wheel on this platform.
 
Do you know when a Windows 64bit release for Python 3.9 will be available on Pypi.org?

Marco

-----

Answer from Luis (date: 06.11.2020)

Hey Marco,
I would suggest you post this question on the official issue tracker: https://github.com/jpype-project/jpype/issues
You will get the most qualified answer there. Personally, I have passed maintenance on to much more qualified people for the job.

I shortly investigated though and it looks like the pypi release is missing a cp39 wheel for windows. 

Feel free to quote our email conversation there!
Hope you are staying healthy and safe. Have a great day,
Luis

-----

**Comment by marscher** [comment]
The PyPI wheels for this system and Python version are indeed missing yet, because our release pipeline does not yet include Python-3.9 yet. The only option for this combination is to build from source.

**Comment by marscher** [comment]
@Thrameos it seems like Python-3.9 has been added in the meantime (e.g. https://github.com/microsoft/azure-pipelines-tasks/issues/13708). So we could trigger a build for 3.9 as well, right?
