### ISSUE TITLE
JPype crashes when JIT compilation is enabled

### ISSUE THREAD

**Issue by s-babelprime** [jpype-project/jpype#884]
Hi,

I'm running into an issue where JPype crashes when JIT compilation is enabled, I am forced to use `-Xint` when starting the JVM to prevent the failure, which can happen in arbitrary places.

It is hard for me to tell which environment crashes first: the JVM or the Python process, see error message below. I've tried on different JREs (Oracle 1.8.0_151 & 1.8.0_172, OpenJDK 11.0.1) and the problem remains. I am on MacOSX 10.14.6 and uses Jpype 1.1.2 on Python 3.8.6.

I don't know if and why that could be the issue but the Java code I'm running is written originally in Kotlin. Is there anything I can try to reenable JIT compilation, since without it performances are extremely poor?

Thank you,
Karl

Error message:
```
Fatal Python error: Bus error
Thread 0x000070000261d000 (most recent call first):
<no Python frame>
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (sharedRuntime.cpp:549), pid=9833, tid=0x0000000000000307
#  guarantee(cb != NULL && cb->is_nmethod()) failed: safepoint polling: pc must refer to an nmethod
#
Fatal Python error: Aborted
```

**Comment by karllessard** [comment]
oops, was logged in with wrong username, recreated the issue in #885
