### ISSUE TITLE
Two test errors on openSUSE Tumbleweed with OpenJDK 15

### ISSUE THREAD

**Issue by jayvdb** [jpype-project/jpype#891]
Two test errors on openSUSE Tumbleweed with OpenJDK 15 on x86_64 and i686
Builds currently at https://build.opensuse.org/package/show/devel:languages:python/python-JPype1

```py
[  152s] _____________________________ test_memory_leak_fix _____________________________
[  152s] 
[  152s]     def test_memory_leak_fix():
[  152s]         """
[  152s]         This test raises java.lang.VirtualMachineErrorPyRaisable
[  152s]         (java.lang.OutOfMemoryError: Java heap space) if the memory leak
[  152s]         is present.
[  152s]     
[  152s]         """
[  152s]         #   Check memory settings.
[  152s]         rt = jpype.java.lang.Runtime.getRuntime()
[  152s] >       assert rt.maxMemory() == MAX_JVM_HEAP_SIZE_BYTES
[  152s] E       assert 134217728 == 128647168
[  152s] E         +134217728
[  152s] E         -128647168
[  152s] 
[  152s] examples/stubs/test_jarray_fixes.py:43: AssertionError
[  152s] __________________________ test_jarray_slice_copy_fix __________________________
[  152s] 
[  152s]     def test_jarray_slice_copy_fix():
[  152s]         jl1 = JavaDoubleArray([1., 2., 3.])
[  152s]         pl1 = jl1[:]
[  152s] >       assert list(jl1) == pl1
[  152s] E       AssertionError: assert [1.0, 2.0, 3.0] == <java array 'double[]'>
[  152s] E         +[1.0, 2.0, 3.0]
[  152s] E         -<java array 'double[]'>
[  152s] E         Full diff:
[  152s] E         - <java array 'double[]'>
[  152s] E         + [1.0, 2.0, 3.0]
```

**Comment by marscher** [comment]
Seems to be Python version 3.8.5

On November 16, 2020 3:26:49 AM UTC, John Vandenberg <notifications@github.com> wrote:
>Two test errors on openSUSE Tumbleweed with OpenJDK 15 on x86_64 and
>i686
>Builds currently at
>https://build.opensuse.org/package/show/home:jayvdb:py-bridge/python-JPype1
>
>```py
>[  152s] _____________________________ test_memory_leak_fix
>_____________________________
>[  152s] 
>[  152s]     def test_memory_leak_fix():
>[  152s]         """
>[  152s]         This test raises
>java.lang.VirtualMachineErrorPyRaisable
>[  152s]         (java.lang.OutOfMemoryError: Java heap space) if the
>memory leak
>[  152s]         is present.
>[  152s]     
>[  152s]         """
>[  152s]         #   Check memory settings.
>[  152s]         rt = jpype.java.lang.Runtime.getRuntime()
>[  152s] >       assert rt.maxMemory() == MAX_JVM_HEAP_SIZE_BYTES
>[  152s] E       assert 134217728 == 128647168
>[  152s] E         +134217728
>[  152s] E         -128647168
>[  152s] 
>[  152s] examples/stubs/test_jarray_fixes.py:43: AssertionError
>[  152s] __________________________ test_jarray_slice_copy_fix
>__________________________
>[  152s] 
>[  152s]     def test_jarray_slice_copy_fix():
>[  152s]         jl1 = JavaDoubleArray([1., 2., 3.])
>[  152s]         pl1 = jl1[:]
>[  152s] >       assert list(jl1) == pl1
>[  152s] E       AssertionError: assert [1.0, 2.0, 3.0] == <java array
>'double[]'>
>[  152s] E         +[1.0, 2.0, 3.0]
>[  152s] E         -<java array 'double[]'>
>[  152s] E         Full diff:
>[  152s] E         - <java array 'double[]'>
>[  152s] E         + [1.0, 2.0, 3.0]
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jpype-project/jpype/issues/891

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jayvdb** [comment]
These appear to be fixed now.

**Comment by marscher** [comment]
thanks for reportin back.
