### ISSUE TITLE
update MANIFEST.in to ignore binary Java files (.class and .jar) in sdist archive creation

### ISSUE THREAD

**Issue by marscher** [jpype-project/jpype#898]
Currently (1.2.0) the sdist command will include the org.jpype.jar and compiled test classes. We do not want that in a pure source archive IMHO.

**Comment by Thrameos** [comment]
Isnt that correct behavior as we want the resulting sdist not to require jdk but just jre?   I believe that was required to build the manylinux unless we add java to docker image.

**Comment by marscher** [comment]
Ah we got rid of JDK, you're right. I'm really confused today.. sorry.
