### ISSUE TITLE
[question] Can this be used to read/pull variables out of a groovy script?

### ISSUE THREAD

**Issue by red8888** [jpype-project/jpype#903]
I have a groovy file I want to read with python. 

It looks like this:
```
@Library('my-shared-library') _

def somevar = [
   "aaaaa",
   "bbbbb",
   "ccccc"
]

mypipeline ([
    'some-param': "sldkjlkdjlsdjf",
    'some-param-two': "blbhablhablhab",
])
```

I don't need to execute it I want to read the closure and the vars into python to use the values in a python script. Can jpype help me do this?

**Comment by Thrameos** [comment]
I don't do much with groovy so this may be incorrect.  

JPype operates though reflection to access live objects in the jvm.  Thus to get ahold of groovy resourses you would need to have groovy running, ask groovy to parse the file, and then use reflection to get to the variables you want to access.  But I am not sure how groovy exposes things in a closure, so it may not be possible even then.

**Comment by red8888** [comment]
ah thanks. sounds like i might be barking up the wrong tree
