### ISSUE TITLE
Wheel support for linux aarch64[arm64]

### ISSUE THREAD

**Issue by odidev** [jpype-project/jpype#907]
**Summary**
Installing jpype on aarch64 via pip using command "pip3 install jpype" tries to build wheel from source code

**Problem description**
jpype doesn't have wheel for aarch64 on PyPI repository. So, while installing jpype via pip on aarch64, pip builds wheel for same resulting in it takes more time to install jpype. Making wheel available for aarch64 will benefit aarch64 users by minimizing jpype installation time.

**Expected Output**
Pip should be able to download jpype wheel from PyPI repository rather than building it from source code.

@jpype-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make jpype wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by marscher** [comment]
Do you feel like sending us a PR for this? You can take a look into .azure/release.yaml for the build steps of the release pipeline.
There is a manylinux docker image available for ARM64, so this should be usable and easy to integrate (https://quay.io/repository/pypa/manylinux2014_aarch64)

**Comment by odidev** [comment]
@marscher Thanks for your quick response, I will start working on it and will raise a PR.

**Comment by Thrameos** [comment]
I believe this was resolved with #910
