### ISSUE TITLE
pyi files missing from wheels

### ISSUE THREAD

**Issue by michi42** [jpype-project/jpype#915]
Thanks a lot for including the stubs in the 1.2 release!
Unfortunately, they appear to be missing in the binary distributions/wheels.
Could they be added for a future release?

**Comment by marscher** [comment]
Sorry for the missing file. Where does the ide expect the file. We need to add it to the data_files section in setup.py.
I'd be happy to accept a PR for this.

On December 30, 2020 2:11:21 PM UTC, Michi <notifications@github.com> wrote:
>Thanks a lot for including the stubs in the 1.2 release!
>Unfortunately, they appear to be missing in the binary
>distributions/wheels.
>Could they be added for a future release?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jpype-project/jpype/issues/915

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by michi42** [comment]
The .pyi files should just be next to the .py files, where they also are in the repository.
