### ISSUE TITLE
JDK8 "Unable to start JVM" exception

### ISSUE THREAD

**Issue by SilentSys** [jpype-project/jpype#923]
Hello,

I'm getting a `Unable to start JVM` exception whenever I try starting the JVM.

Here are some of the combinations I've tried:

- Windows 10
     - jpype: 0.6.3, 0.7.5, 1.2.1
     - OpenJDK 1.8.0.275-b01, JDK 8u202
     - Python 3.7.6
- Ubuntu 18.04.5
     - jpype: 0.6.3, 0.7.5, 1.2.1
     - OpenJDK 8u275-b01
     - Python 3.7.9

Please let me know if there's any more info I can provide.

Cheers.

**Comment by Thrameos** [comment]
All of those configurations should work.     Unless you have Python with the wrong architecture (32 bit Python calling 64 bit Java) it should just work.   What error are you getting?

```
import jpype
import jpype.imports
import platform
print(platform.architecture())
print(jpype.getDefaultJVMPath())
jpype.startJVM()
```

**Comment by SilentSys** [comment]
Ubuntu:
```
('64bit', '')
/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
```

Windows:
```
('64bit', 'WindowsPE')
C:\Program Files\Java\jre1.8.0_202\bin\server\jvm.dll
```

**Comment by SilentSys** [comment]
Seeing as it didn't raise the exception though, I believe this may be the result of the presence of another package.

**Comment by Thrameos** [comment]
What is the failure mode if not an exception?

**Comment by SilentSys** [comment]
Sorry, what I meant was that if I run the script that you sent me as is, I don't get an exception. I only get the exception when I run another script I found that uses jpype.

As a minimal reproducible example, all I have to do is add `import jnius` before `jpype.startJVM()`:

```
import jnius
import jpype
jpype.startJVM()
```

Produces:
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    jpype.startJVM()
  File "jpype/_core.py", line 222, in startJVM
    ignoreUnrecognized, convertStrings, interrupt)
RuntimeError: Unable to start JVM
```

My guess is this has something to do with not being able to start the JVM twice?

Sorry, I didn't realize this script I'm trying to use uses both jpype and jnius... Looks like I'll have to modify it and remove jnius.

I guess this issue can be closed. Although, it would be nice if the exception somehow indicated that the JVM has already been started as I'm sure this could come up in other ways as well.

**Comment by Thrameos** [comment]
Jnius and jpype both try to start the jvm and the jvm can only be started once.  Those two modules are not compatable.  That is unlikely to change as they do very similar functions so running both is not very useful.
