### ISSUE TITLE
Enable Python's built-in pickle to pickle Java classes & objects

### ISSUE THREAD

**Issue by pelson** [jpype-project/jpype#935]
It looks like JPype has its own pickle module to allow pickling of Java classes and objects (https://jpype.readthedocs.io/en/latest/api.html?jpype-pickle-module). Technically, I think it is entirely achievable to implement the [necessary interfaces](https://stackoverflow.com/a/11493777/741316) to allow the built-in pickle module to serialise and deserialise appropriate Java classes & instances.

I hacked together a prototype:

```
import io
from pathlib import Path
import pickle
import typing

import jpype as jp
import jpype.pickle

def _junpickle_bytes(bytes):
    # Turns bytes serialised with JPickler back into objects through JUnpickler.
    fd = io.BytesIO()
    fd.write(bytes)
    fd.seek(0)
    return jp.pickle.JUnpickler(fd).load()


def __reduce__(self):
    # A method on a JClass (and all subclasses) which knows how to turn a Java object
    # into a byte-string. The nature of the __reduce__ interface means that we also
    # provide the function which knows how to turn this byte-string back into an object.
    result = io.BytesIO()
    jp.pickle.JPickler(result).dump(self)
    result.seek(0)
    # Return a thing that knows how to unpickle Java objects (a function + raw bytes)
    return _junpickle_bytes, (result.read(), )


def example():
    jp.startJVM()
    # JPickle & JUnpickle use the imports system. No support for plain-old JClass currently.
    import jpype.imports
    import java.util

    jpype.JClass.__reduce__ = __reduce__
    java.util.ArrayList.__reduce__ = __reduce__

    myobj = jpype.JClass('java.util.ArrayList')()
    myobj.add("test")

    with open("test.pic", "wb") as fd:
        pickle.dump(myobj, fd)

    with open("test.pic", "rb") as fd:
        newobj = pickle.load(fd)

    print("Unpickled:", newobj)
```

At the same time, it would be nice to remove the limitation that you have to have the import hooks enabled (see discussion in #933).

**Comment by Thrameos** [comment]
The issue here is that if there is more than one java object is in the pickle or the same is referenced from another, it wont be linked up but instead there will be 2 copies.  The issue being that each JPickle is stateful and remembers all objects already serialied so it can link then up.

Pickle does the same trick but they hid this detail from the ``__reduce__`` method so cant get at the pickle state to store the java cacher.

**Comment by pelson** [comment]
I just updated my example to the following:

```
    myobj = jpype.JClass('java.util.ArrayList')()
    myobj.add("test")
    myobj.add(myobj)
    myobj.add(myobj)
    myobj2 = jpype.JClass('java.util.ArrayList')()
    myobj2.add("test")
    myobj.add(myobj2)

    with open("test.pic", "wb") as fd:
        pickle.dump(myobj, fd)

    with open("test.pic", "rb") as fd:
        newobj = pickle.load(fd)
    print("Unpickled:", newobj)
```

And get the following output:

```
Unpickled: [test, (this Collection), (this Collection), [test]]
```

Have I misunderstood?

**Comment by pelson** [comment]
Aha, I think I have it:

```
    with open("test.pic", "wb") as fd:
        pickle.dump([myobj, myobj2], fd)

    with open("test.pic", "rb") as fd:
        newobj = pickle.load(fd)
    print("Unpickled:", newobj)

    print(newobj[0][-1] is newobj[1])  # reports False
```

The two things aren't the same object.

**Comment by Thrameos** [comment]
Yeah it is a bug in pickle model that the pickler instance did not get passed to reduce.    The whole concept where the serialize instance has caches and is hidden is flawed.  You can pitch going to reduce_ex but it would be hard to get enough support.  I have been trying to rally for string like objects to solve the JString issue.  But I cant sign the Python contributor agreement so i am stuck.  And this is even more of an edge case.

**Comment by pelson** [comment]
:thinking: - looks like there is a loophole for the global dispatch_table from copy-reg: https://github.com/python/cpython/blob/b74396c3167cc780f01309148db02709bc37b432/Lib/pickle.py#L560 (called with the ``_Pickler`` instance as the first argument). I think it would be reasonable to inject a dispatch for JPype types.

Otherwise, I think the problem is that Java needs to have the whole object to have context of what to serialize as a reference, yet Python is expecting collections to return individual items to be serialized. Certainly not trivial! Closing for now.

**Comment by Thrameos** [comment]
Yeah.  I looked very closely at that part.   Python3 doesn't actually use the Python implementation but rather a C one.  I was able at one point to get the Python one to work, but I was unable to get the C version to work.  

This one definitely requires a modification in Python to make it work.
