### ISSUE TITLE
Unable to create interface from Java

### ISSUE THREAD

**Issue by jain18aditya** [jpype-project/jpype#943]
I am trying to implement callback from java using JProxy
but while using it gives error 

```
Traceback (most recent call last):
  File "/home/jaiadi/TestDS/env/Test-Automation-1.0/runtime/bin/test_ds", line 11, in <module>
    load_entry_point('TestDS-Automation==1.0', 'console_scripts', 'test_ds')()

  File "/home/jaiadi/TestDS/env/TestDS-Automation-1.0/runtime/lib/python3.7/site-packages/testds/ds_init/DataStoreInit.py", line 116, in main
    o.test_setup_ds()

  File "/home/jaiadi/TestDS/env/TestDS-Automation-1.0/runtime/lib/python3.7/site-packages/testds/ds_init/DataStoreInit.py", line 105, in test_setup_ds

    javaPackage.put(jLang.String("Pi"), 3, expiryType, jLang.String(" "), proxy)

TypeError: No matching overloads found for 

javaPackage.put(java.lang.String,int,javaPackage.Dat
aExpiryType,java.lang.String,proxy.jproxyTest), options are:

        public void javaPackage.put(java.lang.String,boolean,javaPackage.DataExpiryType,java.la
ng.String,javaPackage.PutResultCallback)

        public void javaPackage.put(java.lang.String,int,javaPackage.DataExpiryType,java.lang.S
tring,javaPackage.PutResultCallback)

        public void 
javaPackage.put(java.lang.String,java.lang.String,javaPackage.DataExpiryTyp
e,java.lang.String,javaPackage.PutResultCallback)`

```
Java code is an Interface which required implementing in Python

My code in Python looks like this:
```
            @JImplements("javaPackage.PutResultCallback")
            class jproxyTest:
                @JOverride
                def onSuccess(self) :
                    print ("result")

                @JOverride
                def onFailure(self, err) :
                    print ("err")

            j = jproxyTest()
            # d = { 'onSuccess' : _onSuccess, 'onFailure' : _onFailure, }
            # proxy = jpype.JProxy("javaPackage.PutResultCallback", inst=j, convert=True)
            javaPackage.put(jLang.String("Pi"), 3, expiryType, jLang.String(" "), j)
```
Any ways to implement this functionality?

**Comment by Thrameos** [comment]
Your code is a bit confused.  You are mixing old and new style proxies.  The value j is the required proxy.

**Comment by jain18aditya** [comment]
Sorry, I dont know which is new style. Can you point it out so that i can remove another?

**Comment by jain18aditya** [comment]
@Thrameos Updated with new style code, Still getting the same error.

**Comment by Thrameos** [comment]
It seems like it is getting confused between boolean and int.  Add casting for each argument until you can isolate it.  You can also cast the proxy to the correct type.  Also make sure the method is actually static.    I think the proxy is a red herring; this is a simple argument type  mismatch.

**Comment by jain18aditya** [comment]
Yes the issue is because of proxy but i am not able to cast it to correct type. This is certainly not due to boolean, int and string as i have already tried removing 2 methods and was getting the same error.
How to cast proxy? Probably this will solve the issue.

**Comment by Thrameos** [comment]
Cast with the casting operator ``com.amazon.alexa.datastore.client.PutResultCallback@j``.  You can use JInt to cast to Java int.   Assuming all the arguments are the correct type is should call properly.  I don't see anything else that could be.   If that fails create a stub that takes a bunch of java Object types, and passes them back and examine the type of each object.   There must be a mismatch of some kind as it has overloads enumerated, it just doesnt see an exact match.

**Comment by jain18aditya** [comment]
@Thrameos I added type casting now still getting the error when all the params are same

```
Traceback (most recent call last):
  File "/home/jaiadi/SarasDS/env/SarasDS-Automation-1.0/runtime/bin/saras_ds", line 11, in <module>
    load_entry_point('SarasDS-Automation==1.0', 'console_scripts', 'saras_ds')()

  File "/home/jaiadi/SarasDS/env/SarasDS-Automation-1.0/runtime/lib/python3.7/site-packages/sarasds/ds_init/DataStoreInit.py", line 114, in main

    o.test_setup_ds()

  File "/home/jaiadi/SarasDS/env/SarasDS-Automation-1.0/runtime/lib/python3.7/site-packages/sarasds/ds_init/DataStoreInit.py", line 103, in test_setup_ds

    javaPackage.DataStoreTestClient.put(jLang.String("Pi"), jLang.String("Test"), expiryType, None, jclass@proxy)

TypeError: No matching overloads found for com.amazon.alexa.datastore.client.DataStoreTestClient.put(java.lang.String,java.lang.String,com.amazon.alexa.datasto
re.client.DataExpiryType,NoneType,com.amazon.alexa.datastore.client.PutResultCallback), 
options are:
        public void com.amazon.alexa.datastore.client.DataStoreTestClient.put(java.lang.String,boolean,com.amazon.alexa.datastore.client.DataExpiryType,java.la
ng.String,com.amazon.alexa.datastore.client.PutResultCallback)

        public void com.amazon.alexa.datastore.client.DataStoreTestClient.put(java.lang.String,int,com.amazon.alexa.datastore.client.DataExpiryType,java.lang.S
tring,com.amazon.alexa.datastore.client.PutResultCallback)

        public void com.amazon.alexa.datastore.client.DataStoreTestClient.put(java.lang.String,java.lang.String,com.amazon.alexa.datastore.client.DataExpiryTyp
e,java.lang.String,com.amazon.alexa.datastore.client.PutResultCallback)
```

I added typecasting as 

```
jclass = jpype.JClass("com.amazon.alexa.datastore.client.PutResultCallback")

javaPackage.DataStoreTestClient.put(jLang.String("Pi"), 3, expiryType, jLang.String(" "), jclass@j)
```

**Comment by Thrameos** [comment]
It still looks like you are attempting to call a method as a static.  Is DataStoreTestClient an object or a class?

**Comment by jain18aditya** [comment]
DataStoreTestClient is Class, None of the methods are static as of now, I am making them now to test if it works with that. 
Does it needs to be static or not?

**Comment by Thrameos** [comment]
As you have written in the test code they would have to be static.   Consider ``java.lang.String.substring(1) `` vs ``java.lang.String("foo").substring(1) ``.  The first trys to call the static method substring on class String the second calls the instance method on object foo.

It seems like your jpype may be out of date as we addex logic to print the word ``*static*`` in the error message.

**Comment by jain18aditya** [comment]
Thanks issue is with static reference and solved after changing that.
