### ISSUE TITLE
Crash on array operations

### ISSUE THREAD

**Issue by Thrameos** [jpype-project/jpype#944]
The following code was found to crash jpype version 1.2.1 under linux with open JDK 11.   It is not clear if it is simply memory exhaustion, a reference counting issue, or a memory overrun in an array operation.  The error log indicates some type of garbage collection issue.

```
import jpype
import numpy as np

jpype.startJVM()

gamma = jpype.JDouble[:](np.array(range(0,256)))
for i in range(100000):
    gamma2 = jpype.JDouble[512]
    gamma2[0:256] = gamma
    gamma2[256:] = 0.5*np.array(gamma)
```

**Comment by rapgro** [comment]
That seems somehow related to 32 bits architecture but no idea why.
