### ISSUE TITLE
Exposing protected class fields/methods to python

### ISSUE THREAD

**Issue by astrelsky** [jpype-project/jpype#962]
I'm trying to find a way to expose the protected fields and methods of a Java class to python. I would be able to do this easily in java with reflection but I am looking to make it work in python as if the field/method had been public. Would this be possible to do with jpype? I figured I could hack up a way to do it by leveraging the classes `__dict__` but this doesn't seem possible due to the use of `__slots__`.

**Comment by Thrameos** [comment]
You can do this with reflection pre-Java 9.   After Java 9 the API is more protected and you can’t use setAccessable on a field.  Just use the “getClass()” on an object or “class_” on a class to access the Java reflection API.

**Comment by astrelsky** [comment]
> 
> You can do this with reflection pre-Java 9.   After Java 9 the API is more protected and you can’t use setAccessable on a field.  Just use the “getClass()” on an object or “class_” on a class to access the Java reflection API.
> 
> 
> 
> 

I see. You can make it accessible in java 11. I ended up doing some black magic on the python end by extending a dict and using that as a global with `exec` when launching another script. From the new one the fields can just be accessed as if they were public but it is being done via reflection under the hood.
