### ISSUE TITLE
sql shutdown

### ISSUE THREAD

**Issue by kysko** [jpype-project/jpype#983]
Don't know if this is a JPype issue, or one for HSQLDB (2.6.0). I'm a bit new to JPype, so I hope this isn't a triviality I missed in the docs.

This isn't about shutting down the JVM.

I needed a way to shut down an hsqldb server remotely. Server was started on its host with:

```
java -cp lib\hsqldb.jar org.hsqldb.server.Server --database.0 file:db;readonly=true --dbname.0 dbremote
```

Let's say for now the db host is on `192.168.2.100`. I connect to it in `python/JPype` with:

```
with jpype.dbapi2.connect("jdbc:hsqldb:hsql://192.168.2.110/dbremote") as cx:
    with cx.cursor() as cur:

    #
    # do some stuff with cur
    #
```

It works.

But let's say one wants to remotely shutdown that database through `python/JPype`, for *whatever* reason.

Usually one would do a `cur.execute("shutdown")` (or with `shutdown immediate`) within the above code. It *does work*, the remote database is shutdown... but a connection error is also given out, that can be traced back to the closing of the implicit prepared statement that JPype does in the background (`cur._statement.close()`).

I won't give the whole traceback, just the main initial cause:
```
Traceback (most recent call last):
  File "org.hsqldb.jdbc.JDBCPreparedStatement.java", line -1, in org.hsqldb.jdbc.JDBCPreparedStatement.close
  File "org.hsqldb.ClientConnection.java", line -1, in org.hsqldb.ClientConnection.execute
  File "org.hsqldb.error.Error.java", line -1, in org.hsqldb.error.Error.error
  File "org.hsqldb.error.Error.java", line -1, in org.hsqldb.error.Error.error
org.hsqldb.HsqlException: <exception str() failed>
```

I *guess* that when we come out of the cursor's `with`, when the "cleanup" is done, the prepared statement's `close()` method tries to communicate with the database for some maintenance, but isn't there anymore. Or something else I don't know.

Fortunately, JPype is flexible enough to let us have a workaround: rather than `cur.execute("shutdown")`, one can dig a bit more and use a simple (non prepared) statement:

```
# First, provoke a cleanup that will also set `cur._statement = None`,
# and prevent further call to `cur._statement.close()`
# (if no other prepared statement done)
cur._finish()

# Ultimately, avoid dbapi2's `execute`, and rather
# call hsqldb's `createStatement` and execute simple SQL
cur._jcx.createStatement().execute("shutdown")

# After the above, we still have `cur._statement = None`,
# and coming out of `with` won't trigger
# the problematic closing of `cur._statement`
```

Not certain if this is "clean" though... `_finish` is almost closing `cur` (`cur._closed` not put to `True`).
Perhaps better to reconnect to the db after the connection is closed just to do the shutdown. (?)

Is there a better way to do a non-prepared query statement?

The above is an edge case, probably not something one would normally do, but here it is anyway, in case someone else stumbles on the same problem.

**Comment by Thrameos** [comment]
I likely did not consider that case of something causing the connection to close before the statement is complete.   The result is when JPype closes the “with” statement it will try to communicate with the closed connection which is likely generating the error you see.

It is a bit of edge case.   It doesn’t seem like closing a prepared statement should have generated an exception as there is no way to know it the user code shut the connection from under you.

From the Java documentation.  Shutdown closes the connection and from PreparedStatement

Calling the method close on a Statement object that is already closed has no effect.
Thus it seems like the exception is being improperly thrown by the database driver as Exception!=”no effect”.

**Comment by Thrameos** [comment]
So what is the best solution for this?

- Have JPype ignore all exceptions when calling implicit ``close()``.  This may be reasonable as when used as part of a with statement there may already be an exception on the stack so generating a second is a bad idea.  Is there ever a case where the close statement from with can legitimately generate a useful exception?
- Report the HSQLDB that calling a close on a closed statement should not have thrown an exception.  Maybe but this solution is not guaranteed to work and all previous versions will still generate bugs.
- Both?

Opinions?

**Comment by kysko** [comment]
Just an additional note for now:

Right after a `cur.execute("shutdown")`, `cur._jcx.isClosed()` is `False`...
But `cur._jcx.isValid(1)` is `True` before, and `False` after.
So maybe this would be another way to check (only for this edge case!?).

see [isValid](https://www.javadoc.io/doc/org.hsqldb/hsqldb/latest/org/hsqldb/jdbc/JDBCConnection.html#isValid(int))

But as you say, I feel it should have been recognized by the driver already.

**Comment by kysko** [comment]
On a fresh morning...
I compiled a shutdown routine in java with `shutdown` as a prepared statement, and it gave the same error on closing the prep (directly, or indirectly through a `try`)...

_So not a JPype issue after all._

Should have tested that first, sorry.
Well, we know about it now at least...

**Comment by Thrameos** [comment]
Sounds like no action is required on the part of JPype.   Perhaps I bug report should be issued upstream.   The requirements of dbapi2 and  HSQLDB are definitely in conflict.   

I am still wondering if suppressing of errors on close is a good idea or bad idea.   I can check to see if there is currently an exception and eat the new one, but that wouldn't really address this problem.

**Comment by kysko** [comment]
No action required. It's one of those "undefined behaviors" by the dbapi2 mentioned in the doc.
But at least the information will be documented here if one needs it.

**Comment by Thrameos** [comment]
Okay I will add a mention to the JPype dbapi2 documentation.  I wrote bit of it up, but I really don't like accessing private fields.   Thus perhaps we should come up with a better solution.

How about this...

```
@jpype.JImplements(java.sql.Statement)
class MyStatement(object):
   def close(self):
        # Skip calling close if the connect is no longer valid
        if not self.getConnection().isValid():
             return
        return self.close_()  # When we override a method in Python the old method is renamed with underbar
```

Can you check this and see if it is workable for you?  This shows the use a class customizer to add behaviors in Python so that the close statement gets skipped if a shutdown was executed.

**Comment by kysko** [comment]
Hmmm... Seems I'm a bit too green yet to jpype, will have to read more on Implements.

I put this after `import java` (after `startJVM`, with usual imports at beginning of script), but it complains the `java.sql.Statement` interface require to implement `execute`.
So I implemented a quick dummy `execute` method, but it then complains about requiring to implement other methods...
It might ask me to re-implement all of `Statement` interface at this point!

What am I doing wrong? Where exactly should I put your code? I also added `@JOverride` before the `def close` to no avail.

(also, `isValid` needs an `int`, timeout in seconds to wait; for hsqldb, 0 means 60 seconds IIRC...)

**Comment by Thrameos** [comment]
Sorry my bad.   I gave you bad code (been a long day).  Please try

```
@jpype.JImplementationFor("java.sql.PreparedStatement")
class MyStatement(object):
    @jpype.JOverride(sticky=True, rename='_close')
    def close(self):
        if not self.getConnection().isValid(100):
            return
        return self._close()
```

This code may be included before the JVM is started or after, but must appear before the first usage of a Statement.  The ``sticky`` flag makes sure that the method will attach to all copies including the HSQLDB specific implementation.  You can add a second customizer to "java.sql.Connection" if you need.   When Python goes to call the close method it will be redirected to this implementation.   See ``jpype/_jcollection.py`` for more examples of how customizers can be used to attach Python behavior to Java classes.

**Comment by kysko** [comment]
Worked from the get-go this time.
(And it didn't complain when I put before the JVM.)
