### ISSUE TITLE
What are the differences between importing and loading as JClass?

### ISSUE THREAD

**Issue by Midnighter** [jpype-project/jpype#987]
I'll start with a disclaimer that I only began using jpype yesterday and don't know much about Java either. So it might be very obvious.

After some struggle, I was able to import my desired class using the Python import mechanism. So in general, I'm quite happy.

```py
from chemaxon.formats import MolImporter
```

However, part of my struggle was that on the `PYTHONPATH` there was a directory called `chemaxon` which, even though it did not contain an `__init__.py` module, was messing up my import attempts. Since I am developing a Python package that will be distributed, I have no control over the users' path. Thus I am wondering if it is better to use

```py
MolImporter = JClass("chemaxon.formats.MolImporter")
```

instead as that circumvents the Python import mechanism? Being a Java newbie, I'm not sure if I have to provide `JClass` with more options for the call to be equivalent to the import statement?

Thank you for your insights.

**Comment by Thrameos** [comment]
The rules for importing are set by Python not JPype.   Thus if there is a directory in the Path with the same name as a Java package it will always prefer importing that package even if it lacks a ``__init__`` method.

So as for options you have found one of the three alternatives already.  Using a ``JClass`` is a good way to avoid a conflict.   Alternatively you can use ``chemaxon = JPackage("chemaxon")``  which will allow you access to any class in the package.   Last you can register an alias to rename the Java package as ``chemaxonx`` then use the import system.  Further details are in the users manual.

The only advantage of the import system is that it fails like the usual Python import statement.   It is just a front end that calls JClass or JPackage under the hood.

**Comment by Midnighter** [comment]
Thank you for the clarification. I think my first mental note after reading the following paragraph was that I should try to avoid `JClass` if possible. Upon second reading it sounds less scary.

> The last mechanism for looking up a class is through the use of the JClass factory. This is a low level API allowing the loading of any class available using the forName mechanism in Java. The JClass method can take up to three arguments corresponding to arguments of the forName method and can be used with alternative class loaders. The majority of the JPype test bench uses JClass so that the tests are only evaluating the desired functionality and not the import system. But this does not imply that JClass is the preferred mechanic for importing classes. The first argument can be a string or a Java class instance. There are two keyword arguments loader and initialize. The loader can point to an alternative ClassLoader which is handy when loading custom classes through mechanisms such as over the web. A False initialize argument loads a class without loading dependencies nor populating static fields. This option is likely not useful for ordinary users. It was provided when calling forName was problematic due to caller sensitive issues.

**Comment by Thrameos** [comment]
Yeah there is no reason to avoid ``JClass`` other than it doesn't look very Pythonic.   The import front end is simply my effort to try to make Java look more familiar to the Python user.   Unfortunately, that does have conflicts with actually Python packages or things that are mistaken as Python packages.   

JPype operates entirely through the Java reflection API.   Python asks Java what capabilities some class or method provides and then constructs a runtime front end in Python which presents those same capabilities.   Behind the scenes JPype is managing lifetimes, providing converters and such.   There are many low level API pieces like JClass which do specific tasks that are then assembled to create the Python functionality.  If for some reason the higher level API has problems it is often possible to call the low level API to directly execute the functionality.  It doesn't quite conform to the Python philosophy that there should be one obvious way, as we can't make the high level API a perfect match to Python so we have fall back to low level API at times.  Rough edges exist like Java strings are not compatible with Python strings is a good example.  But hopefully JPype will be useful to your project.

**Comment by Midnighter** [comment]
I spent some more time learning about arrays and failed to use a Python managed buffer as provided [in the documentation](https://jpype.readthedocs.io/en/latest/userguide.html?highlight=memoryview#buffer-backed-numpy-arrays)

```py
bb = bytearray(80)
jb = jpype.nio.convertToDirectBuffer(bb)
db = jb.asDoubleBuffer()
a = np.asarray(db)
```

because the function expected a `double[]` argument and I couldn't figure out how to cast it properly. That's not a show stopper for me, though, and I managed to build prototypes for all the functionality that I need. So I'm very happy with jpype. Next step will be a proper Python package and a nicer implementation. I'll post a link when there's something to show.

**Comment by Thrameos** [comment]
What you are describing is one of the limitations of Java.  You can share a native byte array to Java as a direct byte buffer but you may not actually map it into an array type.  Buffers and arrays are distinct types.  It is possible to back a buffer with an array or a native memory but it is either one or the other and thus when you try to get the array() of a memory native or ask an array to give native access it will fail.

There is the concept of "unsafe" operations that could allow one to get at the memory but because the JVM does not support "pinning" so that also has issues in that you wouldn't be able to hold the memory longer than a critical section.   

So the best that can be achieved is to create a numpy array and share its memory as a Java buffer.   You can access the elements and such but if you want to pass it to something requiring an array it has to be copied.

**Comment by Midnighter** [comment]
It's still work-in-progress but basically everything in the [chemaxon subpackage](https://gitlab.com/equilibrator/equilibrator-cheminfo/-/tree/main/src/equilibrator_cheminfo/chemaxon) are wrapper classes around a Java API. I used a singleton pattern for [managing the JVM](https://gitlab.com/equilibrator/equilibrator-cheminfo/-/blob/main/src/equilibrator_cheminfo/chemaxon/chemaxon_manager.py) which I'm quite happy about. The actual communication with Java turned out to be quite contained and straight forward after getting to know JPype a bit better.

I was previously calling the Java code through a CLI and this is orders of magnitude faster. Thank you for your work on JPype 🙂

**Comment by Thrameos** [comment]
Good to hear that JPype is working well for you.   JPype sometimes gets a lot of mockery as to why anyone would want to have more that one virtual machine running at once, but there are definitely use cases where direct communication between Python and Java is the fastest and easiest option.
